//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel052;
int xdim1_opensbliblock00Kernel052;
int xdim2_opensbliblock00Kernel052;
int xdim3_opensbliblock00Kernel052;
int xdim4_opensbliblock00Kernel052;
int xdim5_opensbliblock00Kernel052;
int xdim6_opensbliblock00Kernel052;
int xdim7_opensbliblock00Kernel052;
int xdim8_opensbliblock00Kernel052;
int xdim9_opensbliblock00Kernel052;
int xdim10_opensbliblock00Kernel052;


//user function



void opensbliblock00Kernel052_c_wrapper(
  double * restrict x0_B0_p,
  double * restrict x1_B0_p,
  double * restrict D00_B0_p,
  double * restrict D01_B0_p,
  double * restrict D10_B0_p,
  double * restrict D11_B0_p,
  double * restrict detJ_B0_p,
  double * restrict wk0_B0_p,
  double * restrict wk1_B0_p,
  double * restrict wk2_B0_p,
  double * restrict wk3_B0_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      const ptr_double x0_B0 = { x0_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel052*1, xdim0_opensbliblock00Kernel052};
      const ptr_double x1_B0 = { x1_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel052*1, xdim1_opensbliblock00Kernel052};
      ptr_double D00_B0 = { D00_B0_p + n_x*1 + n_y * xdim2_opensbliblock00Kernel052*1, xdim2_opensbliblock00Kernel052};
      ptr_double D01_B0 = { D01_B0_p + n_x*1 + n_y * xdim3_opensbliblock00Kernel052*1, xdim3_opensbliblock00Kernel052};
      ptr_double D10_B0 = { D10_B0_p + n_x*1 + n_y * xdim4_opensbliblock00Kernel052*1, xdim4_opensbliblock00Kernel052};
      ptr_double D11_B0 = { D11_B0_p + n_x*1 + n_y * xdim5_opensbliblock00Kernel052*1, xdim5_opensbliblock00Kernel052};
      ptr_double detJ_B0 = { detJ_B0_p + n_x*1 + n_y * xdim6_opensbliblock00Kernel052*1, xdim6_opensbliblock00Kernel052};
      ptr_double wk0_B0 = { wk0_B0_p + n_x*1 + n_y * xdim7_opensbliblock00Kernel052*1, xdim7_opensbliblock00Kernel052};
      ptr_double wk1_B0 = { wk1_B0_p + n_x*1 + n_y * xdim8_opensbliblock00Kernel052*1, xdim8_opensbliblock00Kernel052};
      ptr_double wk2_B0 = { wk2_B0_p + n_x*1 + n_y * xdim9_opensbliblock00Kernel052*1, xdim9_opensbliblock00Kernel052};
      ptr_double wk3_B0 = { wk3_B0_p + n_x*1 + n_y * xdim10_opensbliblock00Kernel052*1, xdim10_opensbliblock00Kernel052};
      
   double d1_x0_dx = 0.0;
   double d1_x0_dy = 0.0;
   double d1_x1_dx = 0.0;
   double d1_x1_dy = 0.0;
    d1_x0_dy = invDelta1block0*((idx[1] == 0) ? (
   3.0*OPS_ACC(x0_B0, 0,1) + 0.333333333333333*OPS_ACC(x0_B0, 0,3) - 1.5*OPS_ACC(x0_B0, 0,2) -
      1.83333333333333*OPS_ACC(x0_B0, 0,0)
)
: ((idx[1] == 1) ? (
   0.0394168524399447*OPS_ACC(x0_B0, 0,2) +
      0.00571369039775442*OPS_ACC(x0_B0, 0,4) + 0.719443173328855*OPS_ACC(x0_B0, 0,1) - 0.322484932882161*OPS_ACC(x0_B0, 0,0) -
      0.0658051057710389*OPS_ACC(x0_B0, 0,3) - 0.376283677513354*OPS_ACC(x0_B0, 0,-1)
)
: ((idx[1] == 2) ? (

      0.197184333887745*OPS_ACC(x0_B0, 0,0) + 0.521455851089587*OPS_ACC(x0_B0, 0,1) + 0.113446470384241*OPS_ACC(x0_B0, 0,-2) -
      0.00412637789557492*OPS_ACC(x0_B0, 0,3) - 0.0367146847001261*OPS_ACC(x0_B0, 0,2) - 0.791245592765872*OPS_ACC(x0_B0, 0,-1)
)
: ((idx[1] == 3)
      ? (
   0.0451033223343881*OPS_ACC(x0_B0, 0,0) + 0.652141084861241*OPS_ACC(x0_B0, 0,1) + 0.121937153224065*OPS_ACC(x0_B0, 0,-2) -
      0.00932597985049999*OPS_ACC(x0_B0, 0,-3) - 0.727822147724592*OPS_ACC(x0_B0, 0,-1) - 0.082033432844602*OPS_ACC(x0_B0, 0,2)
)
: (

      -(2.0/3.0)*OPS_ACC(x0_B0, 0,-1) - (1.0/12.0)*OPS_ACC(x0_B0, 0,2) + ((1.0/12.0))*OPS_ACC(x0_B0, 0,-2) + ((2.0/3.0))*OPS_ACC(x0_B0, 0,1)
)))));

    d1_x0_dx = invDelta0block0*((idx[0] == 0) ? (
   3.0*OPS_ACC(x0_B0, 1,0) + 0.333333333333333*OPS_ACC(x0_B0, 3,0) - 1.5*OPS_ACC(x0_B0, 2,0) -
      1.83333333333333*OPS_ACC(x0_B0, 0,0)
)
: ((idx[0] == 1) ? (
   0.0394168524399447*OPS_ACC(x0_B0, 2,0) +
      0.00571369039775442*OPS_ACC(x0_B0, 4,0) + 0.719443173328855*OPS_ACC(x0_B0, 1,0) - 0.322484932882161*OPS_ACC(x0_B0, 0,0) -
      0.0658051057710389*OPS_ACC(x0_B0, 3,0) - 0.376283677513354*OPS_ACC(x0_B0, -1,0)
)
: ((idx[0] == 2) ? (

      0.197184333887745*OPS_ACC(x0_B0, 0,0) + 0.521455851089587*OPS_ACC(x0_B0, 1,0) + 0.113446470384241*OPS_ACC(x0_B0, -2,0) -
      0.00412637789557492*OPS_ACC(x0_B0, 3,0) - 0.0367146847001261*OPS_ACC(x0_B0, 2,0) - 0.791245592765872*OPS_ACC(x0_B0, -1,0)
)
: ((idx[0] == 3)
      ? (
   0.0451033223343881*OPS_ACC(x0_B0, 0,0) + 0.652141084861241*OPS_ACC(x0_B0, 1,0) + 0.121937153224065*OPS_ACC(x0_B0, -2,0) -
      0.00932597985049999*OPS_ACC(x0_B0, -3,0) - 0.727822147724592*OPS_ACC(x0_B0, -1,0) - 0.082033432844602*OPS_ACC(x0_B0, 2,0)
)
: ((idx[0] == -1
      + block0np0) ? (
   1.5*OPS_ACC(x0_B0, -2,0) + 1.83333333333333*OPS_ACC(x0_B0, 0,0) - 3.0*OPS_ACC(x0_B0, -1,0) -
      0.333333333333333*OPS_ACC(x0_B0, -3,0)
)
: ((idx[0] == -2 + block0np0) ? (
   0.322484932882161*OPS_ACC(x0_B0, 0,0) +
      0.0658051057710389*OPS_ACC(x0_B0, -3,0) + 0.376283677513354*OPS_ACC(x0_B0, 1,0) - 0.0394168524399447*OPS_ACC(x0_B0, -2,0) -
      0.00571369039775442*OPS_ACC(x0_B0, -4,0) - 0.719443173328855*OPS_ACC(x0_B0, -1,0)
)
: ((idx[0] == -3 + block0np0) ? (

      0.00412637789557492*OPS_ACC(x0_B0, -3,0) + 0.0367146847001261*OPS_ACC(x0_B0, -2,0) + 0.791245592765872*OPS_ACC(x0_B0, 1,0) -
      0.197184333887745*OPS_ACC(x0_B0, 0,0) - 0.521455851089587*OPS_ACC(x0_B0, -1,0) - 0.113446470384241*OPS_ACC(x0_B0, 2,0)
)
: ((idx[0] == -4 +
      block0np0) ? (
   0.00932597985049999*OPS_ACC(x0_B0, 3,0) + 0.727822147724592*OPS_ACC(x0_B0, 1,0) + 0.082033432844602*OPS_ACC(x0_B0, -2,0) -
      0.0451033223343881*OPS_ACC(x0_B0, 0,0) - 0.652141084861241*OPS_ACC(x0_B0, -1,0) - 0.121937153224065*OPS_ACC(x0_B0, 2,0)
)
: (

      -(2.0/3.0)*OPS_ACC(x0_B0, -1,0) - (1.0/12.0)*OPS_ACC(x0_B0, 2,0) + ((1.0/12.0))*OPS_ACC(x0_B0, -2,0) + ((2.0/3.0))*OPS_ACC(x0_B0, 1,0)
)))))))));

    d1_x1_dy = invDelta1block0*((idx[1] == 0) ? (
   3.0*OPS_ACC(x1_B0, 0,1) + 0.333333333333333*OPS_ACC(x1_B0, 0,3) - 1.5*OPS_ACC(x1_B0, 0,2) -
      1.83333333333333*OPS_ACC(x1_B0, 0,0)
)
: ((idx[1] == 1) ? (
   0.0394168524399447*OPS_ACC(x1_B0, 0,2) +
      0.00571369039775442*OPS_ACC(x1_B0, 0,4) + 0.719443173328855*OPS_ACC(x1_B0, 0,1) - 0.322484932882161*OPS_ACC(x1_B0, 0,0) -
      0.0658051057710389*OPS_ACC(x1_B0, 0,3) - 0.376283677513354*OPS_ACC(x1_B0, 0,-1)
)
: ((idx[1] == 2) ? (

      0.197184333887745*OPS_ACC(x1_B0, 0,0) + 0.521455851089587*OPS_ACC(x1_B0, 0,1) + 0.113446470384241*OPS_ACC(x1_B0, 0,-2) -
      0.00412637789557492*OPS_ACC(x1_B0, 0,3) - 0.0367146847001261*OPS_ACC(x1_B0, 0,2) - 0.791245592765872*OPS_ACC(x1_B0, 0,-1)
)
: ((idx[1] == 3)
      ? (
   0.0451033223343881*OPS_ACC(x1_B0, 0,0) + 0.652141084861241*OPS_ACC(x1_B0, 0,1) + 0.121937153224065*OPS_ACC(x1_B0, 0,-2) -
      0.00932597985049999*OPS_ACC(x1_B0, 0,-3) - 0.727822147724592*OPS_ACC(x1_B0, 0,-1) - 0.082033432844602*OPS_ACC(x1_B0, 0,2)
)
: (

      -(2.0/3.0)*OPS_ACC(x1_B0, 0,-1) - (1.0/12.0)*OPS_ACC(x1_B0, 0,2) + ((1.0/12.0))*OPS_ACC(x1_B0, 0,-2) + ((2.0/3.0))*OPS_ACC(x1_B0, 0,1)
)))));

    d1_x1_dx = invDelta0block0*((idx[0] == 0) ? (
   3.0*OPS_ACC(x1_B0, 1,0) + 0.333333333333333*OPS_ACC(x1_B0, 3,0) - 1.5*OPS_ACC(x1_B0, 2,0) -
      1.83333333333333*OPS_ACC(x1_B0, 0,0)
)
: ((idx[0] == 1) ? (
   0.0394168524399447*OPS_ACC(x1_B0, 2,0) +
      0.00571369039775442*OPS_ACC(x1_B0, 4,0) + 0.719443173328855*OPS_ACC(x1_B0, 1,0) - 0.322484932882161*OPS_ACC(x1_B0, 0,0) -
      0.0658051057710389*OPS_ACC(x1_B0, 3,0) - 0.376283677513354*OPS_ACC(x1_B0, -1,0)
)
: ((idx[0] == 2) ? (

      0.197184333887745*OPS_ACC(x1_B0, 0,0) + 0.521455851089587*OPS_ACC(x1_B0, 1,0) + 0.113446470384241*OPS_ACC(x1_B0, -2,0) -
      0.00412637789557492*OPS_ACC(x1_B0, 3,0) - 0.0367146847001261*OPS_ACC(x1_B0, 2,0) - 0.791245592765872*OPS_ACC(x1_B0, -1,0)
)
: ((idx[0] == 3)
      ? (
   0.0451033223343881*OPS_ACC(x1_B0, 0,0) + 0.652141084861241*OPS_ACC(x1_B0, 1,0) + 0.121937153224065*OPS_ACC(x1_B0, -2,0) -
      0.00932597985049999*OPS_ACC(x1_B0, -3,0) - 0.727822147724592*OPS_ACC(x1_B0, -1,0) - 0.082033432844602*OPS_ACC(x1_B0, 2,0)
)
: ((idx[0] == -1
      + block0np0) ? (
   1.5*OPS_ACC(x1_B0, -2,0) + 1.83333333333333*OPS_ACC(x1_B0, 0,0) - 3.0*OPS_ACC(x1_B0, -1,0) -
      0.333333333333333*OPS_ACC(x1_B0, -3,0)
)
: ((idx[0] == -2 + block0np0) ? (
   0.322484932882161*OPS_ACC(x1_B0, 0,0) +
      0.0658051057710389*OPS_ACC(x1_B0, -3,0) + 0.376283677513354*OPS_ACC(x1_B0, 1,0) - 0.0394168524399447*OPS_ACC(x1_B0, -2,0) -
      0.00571369039775442*OPS_ACC(x1_B0, -4,0) - 0.719443173328855*OPS_ACC(x1_B0, -1,0)
)
: ((idx[0] == -3 + block0np0) ? (

      0.00412637789557492*OPS_ACC(x1_B0, -3,0) + 0.0367146847001261*OPS_ACC(x1_B0, -2,0) + 0.791245592765872*OPS_ACC(x1_B0, 1,0) -
      0.197184333887745*OPS_ACC(x1_B0, 0,0) - 0.521455851089587*OPS_ACC(x1_B0, -1,0) - 0.113446470384241*OPS_ACC(x1_B0, 2,0)
)
: ((idx[0] == -4 +
      block0np0) ? (
   0.00932597985049999*OPS_ACC(x1_B0, 3,0) + 0.727822147724592*OPS_ACC(x1_B0, 1,0) + 0.082033432844602*OPS_ACC(x1_B0, -2,0) -
      0.0451033223343881*OPS_ACC(x1_B0, 0,0) - 0.652141084861241*OPS_ACC(x1_B0, -1,0) - 0.121937153224065*OPS_ACC(x1_B0, 2,0)
)
: (

      -(2.0/3.0)*OPS_ACC(x1_B0, -1,0) - (1.0/12.0)*OPS_ACC(x1_B0, 2,0) + ((1.0/12.0))*OPS_ACC(x1_B0, -2,0) + ((2.0/3.0))*OPS_ACC(x1_B0, 1,0)
)))))))));

   OPS_ACC(wk0_B0, 0,0) = d1_x0_dx;

   OPS_ACC(wk1_B0, 0,0) = d1_x0_dy;

   OPS_ACC(wk2_B0, 0,0) = d1_x1_dx;

   OPS_ACC(wk3_B0, 0,0) = d1_x1_dy;

   OPS_ACC(detJ_B0, 0,0) = d1_x0_dx*d1_x1_dy - d1_x0_dy*d1_x1_dx;

   OPS_ACC(D00_B0, 0,0) = d1_x1_dy/(d1_x0_dx*d1_x1_dy - d1_x0_dy*d1_x1_dx);

   OPS_ACC(D01_B0, 0,0) = -d1_x0_dy/(d1_x0_dx*d1_x1_dy - d1_x0_dy*d1_x1_dx);

   OPS_ACC(D10_B0, 0,0) = -d1_x1_dx/(d1_x0_dx*d1_x1_dy - d1_x0_dy*d1_x1_dx);

   OPS_ACC(D11_B0, 0,0) = d1_x0_dx/(d1_x0_dx*d1_x1_dy - d1_x0_dy*d1_x1_dx);


    }
  }
}
