//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_opensbliblock00Kernel009;
int xdim1_opensbliblock00Kernel009;
int xdim2_opensbliblock00Kernel009;
int xdim3_opensbliblock00Kernel009;

//user function
inline 
 void opensbliblock00Kernel009(const ptr_double rhoN2_B0,
  const ptr_double rhoN_B0,
  const ptr_double rhou0_B0,
  ptr_double u0_B0)
{
   OPS_ACC(u0_B0, 0) = OPS_ACC(rhou0_B0, 0)/(OPS_ACC(rhoN_B0, 0) + OPS_ACC(rhoN2_B0, 0));

}


void opensbliblock00Kernel009_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double *p_a3,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2,p_a3)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    const ptr_double ptr0 = {  p_a0 + n_x*1*1 };
    const ptr_double ptr1 = {  p_a1 + n_x*1*1 };
    const ptr_double ptr2 = {  p_a2 + n_x*1*1 };
    ptr_double ptr3 = {  p_a3 + n_x*1*1 };
    opensbliblock00Kernel009( ptr0, ptr1, ptr2, ptr3);
  }
}
