//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel034;
int xdim1_opensbliblock00Kernel034;


//user function



void opensbliblock00Kernel034_c_wrapper(
  double * restrict T_B0_p,
  double * restrict wk6_B0_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      const ptr_double T_B0 = { T_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel034*1, xdim0_opensbliblock00Kernel034};
      ptr_double wk6_B0 = { wk6_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel034*1, xdim1_opensbliblock00Kernel034};
      
    OPS_ACC(wk6_B0, 0,0) = inv_1*((idx[1] == 0) ? (
   (rc32)*OPS_ACC(T_B0, 0,4) - rc34*OPS_ACC(T_B0, 0,3) +
      (rc35)*OPS_ACC(T_B0, 0,2) - rc36*OPS_ACC(T_B0, 0,1) + (rc37)*OPS_ACC(T_B0, 0,0)
)
: ((idx[1] == 1) ? (

      -rc11*OPS_ACC(T_B0, 0,3) + (rc32)*OPS_ACC(T_B0, 0,-1) + (rc24)*OPS_ACC(T_B0, 0,2) + (rc14)*OPS_ACC(T_B0, 0,1)
      - rc19*OPS_ACC(T_B0, 0,0)
)
: (
   -rc11*OPS_ACC(T_B0, 0,-2) + (rc8)*OPS_ACC(T_B0, 0,-1) -
      rc11*OPS_ACC(T_B0, 0,2) + (rc8)*OPS_ACC(T_B0, 0,1) - rc38*OPS_ACC(T_B0, 0,0)
)));


    }
  }
}
