//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel043;
int xdim1_opensbliblock00Kernel043;


//user function



void opensbliblock00Kernel043_c_wrapper(
  double * restrict u1_B0_p,
  double * restrict wk15_B0_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      const ptr_double u1_B0 = { u1_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel043*1, xdim0_opensbliblock00Kernel043};
      ptr_double wk15_B0 = { wk15_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel043*1, xdim1_opensbliblock00Kernel043};
      
    OPS_ACC(wk15_B0, 0,0) = inv_3*((idx[1] == 0) ? (
   -rc29*OPS_ACC(u1_B0, 0,1) + (rc30)*OPS_ACC(u1_B0, 0,0) +
      (rc27)*OPS_ACC(u1_B0, 0,4) - rc31*OPS_ACC(u1_B0, 0,3) + (rc32)*OPS_ACC(u1_B0, 0,2)
)
: ((idx[1] == 1) ? (

      (rc10)*OPS_ACC(u1_B0, 0,1) - rc13*OPS_ACC(u1_B0, 0,0) - rc8*OPS_ACC(u1_B0, 0,3) + (rc27)*OPS_ACC(u1_B0, 0,-1)
      + (rc18)*OPS_ACC(u1_B0, 0,2)
)
: ((idx[1] == block0np1 - 1) ? (
   -rc31*OPS_ACC(u1_B0, 0,-3) +
      (rc27)*OPS_ACC(u1_B0, 0,-4) + (rc30)*OPS_ACC(u1_B0, 0,0) + (rc32)*OPS_ACC(u1_B0, 0,-2) -
      rc29*OPS_ACC(u1_B0, 0,-1)
)
: ((idx[1] == block0np1 - 2) ? (
   -rc8*OPS_ACC(u1_B0, 0,-3) +
      (rc27)*OPS_ACC(u1_B0, 0,1) - rc13*OPS_ACC(u1_B0, 0,0) + (rc18)*OPS_ACC(u1_B0, 0,-2) +
      (rc10)*OPS_ACC(u1_B0, 0,-1)
)
: (
   (rc33)*OPS_ACC(u1_B0, 0,1) - rc34*OPS_ACC(u1_B0, 0,0) +
      (rc33)*OPS_ACC(u1_B0, 0,-1) - rc8*OPS_ACC(u1_B0, 0,-2) - rc8*OPS_ACC(u1_B0, 0,2)
)))));


    }
  }
}
