//
// auto-generated by ops.py//

#include "./OpenACC/opensbli_common.h"
#include <math.h>
#include "ops_macros.h"
#include <openacc.h>

//user kernel files
#include "opensbliblock00Kernel010_openacc_kernel_c.c"
#include "opensbliblock00Kernel008_openacc_kernel_c.c"
#include "opensbliblock00Kernel009_openacc_kernel_c.c"
#include "opensbliblock00Kernel003_openacc_kernel_c.c"
#include "opensbliblock00Kernel005_openacc_kernel_c.c"
#include "opensbliblock00Kernel001_openacc_kernel_c.c"
#include "opensbliblock00Kernel000_openacc_kernel_c.c"
#include "opensbliblock00Kernel006_openacc_kernel_c.c"
#include "opensbliblock00Kernel011_openacc_kernel_c.c"
