//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_opensbliblock00Kernel010;
int xdim1_opensbliblock00Kernel010;
int xdim2_opensbliblock00Kernel010;
int xdim3_opensbliblock00Kernel010;

//user function
inline 
void opensbliblock00Kernel010(ptr_double x0_B0,
  ptr_double rhou0_B0,
  ptr_double rho_B0,
  ptr_double rhoE_B0,
  const int *idx)
{
   double d = 0.0;
   double x0 = 0.0;
   double u0 = 0.0;
   double p = 0.0;
   x0 = Delta0block0*idx[0] - 5.0;

   OPS_ACC(x0_B0, 0) = x0;

   u0 = ((x0 < -4.0) ? (
   2.629369
)
: (
   0.0
));

   p = ((x0 < -4.0) ? (
   10.33333
)
: ((x0 >= -4.0) ? (
   1.0
)
: (
   0.0
)));

   d = ((x0 < -4.0) ? (
   3.857143
)
: ((x0 >= -4.0) ? (
   0.2*sin(5*x0) + 1.0
)
: (
   0
)));

   OPS_ACC(rho_B0, 0) = d;

   OPS_ACC(rhou0_B0, 0) = d*u0;

   OPS_ACC(rhoE_B0, 0) = 0.5*d*pow(u0, 2.0) + p/(gama - 1.0);

}


void opensbliblock00Kernel010_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double *p_a3,
  int *p_a4,
  int arg_idx0,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2,p_a3)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    int arg_idx[] = {arg_idx0+n_x};
    ptr_double ptr0 = {  p_a0 + n_x*1*1 };
    ptr_double ptr1 = {  p_a1 + n_x*1*1 };
    ptr_double ptr2 = {  p_a2 + n_x*1*1 };
    ptr_double ptr3 = {  p_a3 + n_x*1*1 };
    opensbliblock00Kernel010( ptr0,
          ptr1,ptr2,
          ptr3,arg_idx );

  }
}
