//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel017;
int xdim1_opensbliblock00Kernel017;
int xdim2_opensbliblock00Kernel017;
int xdim3_opensbliblock00Kernel017;
int xdim4_opensbliblock00Kernel017;
int xdim5_opensbliblock00Kernel017;


//user function



void opensbliblock00Kernel017_c_wrapper(
  double * restrict rhoE_B0_p,
  double * restrict rhoN2_B0_p,
  double * restrict rhoN_B0_p,
  double * restrict rho_B0_p,
  double * restrict rhou0_B0_p,
  double * restrict x0_B0_p,
  int * restrict idx,
  int arg_idx0, 
  int x_size) {
  #pragma omp parallel for
  for ( int n_x=0; n_x<x_size; n_x++ ){
    int idx[] = {arg_idx0+n_x};
    ptr_double rhoE_B0 = { rhoE_B0_p + n_x*1};
    ptr_double rhoN2_B0 = { rhoN2_B0_p + n_x*1};
    ptr_double rhoN_B0 = { rhoN_B0_p + n_x*1};
    ptr_double rho_B0 = { rho_B0_p + n_x*1};
    ptr_double rhou0_B0 = { rhou0_B0_p + n_x*1};
    ptr_double x0_B0 = { x0_B0_p + n_x*1};
    
   double dN = 0.0;
   double dN2 = 0.0;
   double p = 0.0;
   double u0 = 0.0;
   OPS_ACC(x0_B0, 0) = Delta0block0*idx[0];

   u0 = 0.0;

   p = ((OPS_ACC(x0_B0, 0) < 0.5) ? (
   1.0
)
: (
   0.1
));

   dN = ((OPS_ACC(x0_B0, 0) < 0.5) ? (
   0.8
)
: (
   0.2
));

   dN2 = ((OPS_ACC(x0_B0, 0) < 0.5) ? (
   0.2
)
: (
   0.8
));

   OPS_ACC(rho_B0, 0) = dN + dN2;

   OPS_ACC(rhoN_B0, 0) = dN;

   OPS_ACC(rhoN2_B0, 0) = dN2;

   OPS_ACC(rhou0_B0, 0) = u0*(dN + dN2);

   OPS_ACC(rhoE_B0, 0) = p/(-1.0 + gama) + (u0*u0)*(0.5*dN + 0.5*dN2);


  }
}
