//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_opensbliblock00Kernel011;
int xdim1_opensbliblock00Kernel011;

//user function
inline 
void opensbliblock00Kernel011(const ptr_double T_B0,
  ptr_double wk5_B0,
  const int *idx)
{
   if (idx[1] == 0){

       OPS_ACC(wk5_B0, 0,0) = (3.0*OPS_ACC(T_B0, 0,1) + 0.333333333333333*OPS_ACC(T_B0, 0,3) - 1.5*OPS_ACC(T_B0, 0,2) -
            1.83333333333333*OPS_ACC(T_B0, 0,0))*invDelta1block0;

   }

   else if (idx[1] == 1){

       OPS_ACC(wk5_B0, 0,0) = (0.0394168524399447*OPS_ACC(T_B0, 0,2) + 0.00571369039775442*OPS_ACC(T_B0, 0,4) + 0.719443173328855*OPS_ACC(T_B0, 0,1) -
            0.322484932882161*OPS_ACC(T_B0, 0,0) - 0.0658051057710389*OPS_ACC(T_B0, 0,3) - 0.376283677513354*OPS_ACC(T_B0, 0,-1))*invDelta1block0;

   }

   else if (idx[1] == 2){

       OPS_ACC(wk5_B0, 0,0) = (0.197184333887745*OPS_ACC(T_B0, 0,0) + 0.521455851089587*OPS_ACC(T_B0, 0,1) + 0.113446470384241*OPS_ACC(T_B0, 0,-2) -
            0.00412637789557492*OPS_ACC(T_B0, 0,3) - 0.0367146847001261*OPS_ACC(T_B0, 0,2) -
            0.791245592765872*OPS_ACC(T_B0, 0,-1))*invDelta1block0;

   }

   else if (idx[1] == 3){

       OPS_ACC(wk5_B0, 0,0) = (0.0451033223343881*OPS_ACC(T_B0, 0,0) + 0.652141084861241*OPS_ACC(T_B0, 0,1) + 0.121937153224065*OPS_ACC(T_B0, 0,-2) -
            0.00932597985049999*OPS_ACC(T_B0, 0,-3) - 0.727822147724592*OPS_ACC(T_B0, 0,-1) -
            0.082033432844602*OPS_ACC(T_B0, 0,2))*invDelta1block0;

   }

   else if (idx[1] == -1 + block0np1){

       OPS_ACC(wk5_B0, 0,0) = (1.5*OPS_ACC(T_B0, 0,-2) + 1.83333333333333*OPS_ACC(T_B0, 0,0) - 3.0*OPS_ACC(T_B0, 0,-1) -
            0.333333333333333*OPS_ACC(T_B0, 0,-3))*invDelta1block0;

   }

   else if (idx[1] == -2 + block0np1){

       OPS_ACC(wk5_B0, 0,0) = (0.322484932882161*OPS_ACC(T_B0, 0,0) + 0.0658051057710389*OPS_ACC(T_B0, 0,-3) + 0.376283677513354*OPS_ACC(T_B0, 0,1) -
            0.0394168524399447*OPS_ACC(T_B0, 0,-2) - 0.00571369039775442*OPS_ACC(T_B0, 0,-4) -
            0.719443173328855*OPS_ACC(T_B0, 0,-1))*invDelta1block0;

   }

   else if (idx[1] == -3 + block0np1){

       OPS_ACC(wk5_B0, 0,0) = (0.00412637789557492*OPS_ACC(T_B0, 0,-3) + 0.0367146847001261*OPS_ACC(T_B0, 0,-2) + 0.791245592765872*OPS_ACC(T_B0, 0,1) -
            0.197184333887745*OPS_ACC(T_B0, 0,0) - 0.521455851089587*OPS_ACC(T_B0, 0,-1) - 0.113446470384241*OPS_ACC(T_B0, 0,2))*invDelta1block0;

   }

   else if (idx[1] == -4 + block0np1){

       OPS_ACC(wk5_B0, 0,0) = (0.00932597985049999*OPS_ACC(T_B0, 0,3) + 0.727822147724592*OPS_ACC(T_B0, 0,1) + 0.082033432844602*OPS_ACC(T_B0, 0,-2) -
            0.0451033223343881*OPS_ACC(T_B0, 0,0) - 0.652141084861241*OPS_ACC(T_B0, 0,-1) - 0.121937153224065*OPS_ACC(T_B0, 0,2))*invDelta1block0;

   }

   else{

       OPS_ACC(wk5_B0, 0,0) = (-(2.0/3.0)*OPS_ACC(T_B0, 0,-1) - (1.0/12.0)*OPS_ACC(T_B0, 0,2) + ((1.0/12.0))*OPS_ACC(T_B0, 0,-2) +
            ((2.0/3.0))*OPS_ACC(T_B0, 0,1))*invDelta1block0;

   }

}


void opensbliblock00Kernel011_c_wrapper(
  double *p_a0,
  double *p_a1,
  int *p_a2,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_y=0; n_y<y_size; n_y++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      const ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_opensbliblock00Kernel011*1*1, xdim0_opensbliblock00Kernel011};
      ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_opensbliblock00Kernel011*1*1, xdim1_opensbliblock00Kernel011};
      opensbliblock00Kernel011( ptr0,
          ptr1,arg_idx );

    }
  }
}
