#!/bin/bash

make clean
rm -rf MPI_* Op* opensbli_ops.cpp CUDA/ HIP/ bashout.log opensbli_mpi opensbli_output.h5 output.log
python $OPS_TRANSLATOR/ops.py opensbli.cpp
var1=$1

if [ "$var1" = "write" ]; then
    make opensbli_mpi &> bashout.log
    rm output.log
    mpirun -np 4 ./opensbli_mpi > output.log
else
    make opensbli_mpi
    rm output.log
    mpirun -np 4 ./opensbli_mpi
fi