//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_opensbliblock00Kernel067;
int ydim0_opensbliblock00Kernel067;
int xdim1_opensbliblock00Kernel067;
int ydim1_opensbliblock00Kernel067;
int xdim2_opensbliblock00Kernel067;
int ydim2_opensbliblock00Kernel067;
int xdim3_opensbliblock00Kernel067;
int ydim3_opensbliblock00Kernel067;
int xdim4_opensbliblock00Kernel067;
int ydim4_opensbliblock00Kernel067;
int xdim5_opensbliblock00Kernel067;
int ydim5_opensbliblock00Kernel067;
int xdim6_opensbliblock00Kernel067;
int ydim6_opensbliblock00Kernel067;
int xdim7_opensbliblock00Kernel067;
int ydim7_opensbliblock00Kernel067;

//user function
inline 
 void opensbliblock00Kernel067(ptr_double rhoE_B0,
  ptr_double rho_B0,
  ptr_double rhou0_B0,
  ptr_double rhou1_B0,
  ptr_double rhou2_B0,
  ptr_double x0_B0,
  ptr_double x2_B0,
  ptr_double x1_B0,
  const int *idx)
{
   double T = 0.0;
   double rho = 0.0;
   double rhou0 = 0.0;
   double rhou1 = 0.0;
   OPS_ACC(x0_B0, 0,0,0) = Delta0block0*idx[0];

    OPS_ACC(x1_B0, 0,0,0) = ((1.0/20.0))*H*exp(-((-(1.0/2.0)*L + Delta0block0*idx[0])*(-(1.0/2.0)*L +
      Delta0block0*idx[0]))*inv2a) + (-(1.0/20.0)*H*exp(-((-(1.0/2.0)*L + Delta0block0*idx[0])*(-(1.0/2.0)*L +
      Delta0block0*idx[0]))*inv2a) + H)*sinh(b*invH*Delta1block0*idx[1])/sinh(b);

   OPS_ACC(x2_B0, 0,0,0) = Delta2block0*idx[2];

    rhou0 = ((OPS_ACC(x1_B0, 0,0,0) < 3.47434743474347) ? (
   -9.17067018165446e-7 + 1.04904785912717e-12*pow(OPS_ACC(x1_B0, 0,0,0), 32)
      + 1.93885271233942e-8*pow(OPS_ACC(x1_B0, 0,0,0), 24) + 1.89852844373312e-11*pow(OPS_ACC(x1_B0, 0,0,0), 29) +
      3.37370804774424*pow(OPS_ACC(x1_B0, 0,0,0), 9) + 0.0359510928126198*pow(OPS_ACC(x1_B0, 0,0,0), 11) +
      1.76866484703332e-11*pow(OPS_ACC(x1_B0, 0,0,0), 30) + 8.55538618337689e-18*pow(OPS_ACC(x1_B0, 0,0,0), 41) +
      1.24379952358685*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) +
      1.76792777158731e-20*pow(OPS_ACC(x1_B0, 0,0,0), 47) + 0.00017691036378445*pow(OPS_ACC(x1_B0, 0,0,0), 17) +
      5.89461687058746e-12*pow(OPS_ACC(x1_B0, 0,0,0), 31) + 1.24225192775816e-7*pow(OPS_ACC(x1_B0, 0,0,0), 23) +
      0.137059939944025*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) + 2.35704636892935e-22*pow(OPS_ACC(x1_B0, 0,0,0), 50) +
      5.38134402885701e-16*pow(OPS_ACC(x1_B0, 0,0,0), 38) + 4.89915999852604*pow(OPS_ACC(x1_B0, 0,0,0), 7) +
      0.000614017778541162*pow(OPS_ACC(x1_B0, 0,0,0), 16) + 2.86778862696949e-16*pow(OPS_ACC(x1_B0, 0,0,0), 39) +
      5.55514524457723e-22*pow(OPS_ACC(x1_B0, 0,0,0), 48) + 3.24118837721475e-7*pow(OPS_ACC(x1_B0, 0,0,0), 22) +
      7.78685163399157e-17*pow(OPS_ACC(x1_B0, 0,0,0), 40) + 0.0951694369630824*pow(OPS_ACC(x1_B0, 0,0,0), 12) +
      4.28094523966535e-20*pow(OPS_ACC(x1_B0, 0,0,0), 46) + 0.423485026937325*OPS_ACC(x1_B0, 0,0,0) -
      3.82231789496219e-14*pow(OPS_ACC(x1_B0, 0,0,0), 33) - 0.00596081896192219*pow(OPS_ACC(x1_B0, 0,0,0), 13) -
      1.03761285206079e-13*pow(OPS_ACC(x1_B0, 0,0,0), 34) - 2.01042980423323e-21*pow(OPS_ACC(x1_B0, 0,0,0), 49) -
      3.04338937551007*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) -
      0.00843501466200706*pow(OPS_ACC(x1_B0, 0,0,0), 14) - 2.10203301192962e-18*pow(OPS_ACC(x1_B0, 0,0,0), 43) -
      5.69178037573737e-19*pow(OPS_ACC(x1_B0, 0,0,0), 44) - 9.50679806994433e-15*pow(OPS_ACC(x1_B0, 0,0,0), 36) -
      6.17136538416838e-6*pow(OPS_ACC(x1_B0, 0,0,0), 18) - 1.09599584261102e-7*pow(OPS_ACC(x1_B0, 0,0,0), 21) -
      3.20359957168517e-18*pow(OPS_ACC(x1_B0, 0,0,0), 42) - 0.0037399214502528*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) -
      1.19041952735479e-10*pow(OPS_ACC(x1_B0, 0,0,0), 28) - 1.62610179290494e-5*pow(OPS_ACC(x1_B0, 0,0,0), 19) -
      0.000525101058483408*pow(OPS_ACC(x1_B0, 0,0,0), 15) - 3.03740635176385e-20*pow(OPS_ACC(x1_B0, 0,0,0), 45) -
      1.15705905931138*pow(OPS_ACC(x1_B0, 0,0,0), 10) - 4.43597629138548e-6*pow(OPS_ACC(x1_B0, 0,0,0), 20) -
      5.15676788952549*pow(OPS_ACC(x1_B0, 0,0,0), 8) - 0.338659488930541*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) -
      6.16209661908411e-16*pow(OPS_ACC(x1_B0, 0,0,0), 37) - 2.65285464174594e-9*pow(OPS_ACC(x1_B0, 0,0,0), 26) -
      4.18364197030384e-14*pow(OPS_ACC(x1_B0, 0,0,0), 35) - 2.75755111469832e-9*pow(OPS_ACC(x1_B0, 0,0,0), 25) -
      8.2958200408048e-10*pow(OPS_ACC(x1_B0, 0,0,0), 27)
)
: (
   0.999999408165728
));

    rhou1 = ((OPS_ACC(x1_B0, 0,0,0) < 3.47434743474347) ? (
   -3.80679683270553e-8 + 6.17437190708395e-8*pow(OPS_ACC(x1_B0, 0,0,0), 18) +
      7.98844798973513e-14*pow(OPS_ACC(x1_B0, 0,0,0), 29) + 0.00108954905836295*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) +
      0.00117080257732117*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) +
      0.0243865952440656*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) +
      1.2544013801972e-14*pow(OPS_ACC(x1_B0, 0,0,0), 32) + 1.06115104000346e-19*pow(OPS_ACC(x1_B0, 0,0,0), 41) +
      7.68574113729758e-24*pow(OPS_ACC(x1_B0, 0,0,0), 48) + 6.1051360242979e-14*pow(OPS_ACC(x1_B0, 0,0,0), 31) +
      4.13310784400092e-6*OPS_ACC(x1_B0, 0,0,0) + 2.61275509277859e-10*pow(OPS_ACC(x1_B0, 0,0,0), 24) +
      2.24860630110554e-6*pow(OPS_ACC(x1_B0, 0,0,0), 17) + 4.24813157066436e-18*pow(OPS_ACC(x1_B0, 0,0,0), 38) +
      0.00121959012162624*pow(OPS_ACC(x1_B0, 0,0,0), 12) + 2.15865801047236e-24*pow(OPS_ACC(x1_B0, 0,0,0), 50) +
      0.0823410741549325*pow(OPS_ACC(x1_B0, 0,0,0), 7) + 1.61740789629939e-13*pow(OPS_ACC(x1_B0, 0,0,0), 30) +
      1.35323978446153e-9*pow(OPS_ACC(x1_B0, 0,0,0), 23) + 3.29846676501425e-16*pow(OPS_ACC(x1_B0, 0,0,0), 33) +
      0.0477784801337204*pow(OPS_ACC(x1_B0, 0,0,0), 9) + 2.89430210932789e-9*pow(OPS_ACC(x1_B0, 0,0,0), 22) +
      2.69890057447216e-18*pow(OPS_ACC(x1_B0, 0,0,0), 39) + 1.7055391487583e-22*pow(OPS_ACC(x1_B0, 0,0,0), 47) +
      6.1877361855565e-6*pow(OPS_ACC(x1_B0, 0,0,0), 16) + 3.81994771390975e-22*pow(OPS_ACC(x1_B0, 0,0,0), 46) +
      7.95464046126323e-19*pow(OPS_ACC(x1_B0, 0,0,0), 40) - 8.98633672109457e-12*pow(OPS_ACC(x1_B0, 0,0,0), 27) -
      0.000100734047354864*pow(OPS_ACC(x1_B0, 0,0,0), 14) -
      0.0553962785044558*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) -
      5.39132582911632e-8*pow(OPS_ACC(x1_B0, 0,0,0), 20) - 8.91370364440569e-16*pow(OPS_ACC(x1_B0, 0,0,0), 34) -
      4.19966155397138e-9*pow(OPS_ACC(x1_B0, 0,0,0), 21) - 0.0798165116789603*pow(OPS_ACC(x1_B0, 0,0,0), 8) -
      1.95905283896047e-20*pow(OPS_ACC(x1_B0, 0,0,0), 43) - 1.02381592894008e-17*pow(OPS_ACC(x1_B0, 0,0,0), 37) -
      0.0065291150198612*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) - 4.10642443126274e-16*pow(OPS_ACC(x1_B0, 0,0,0),
      35) - 0.0144672034577952*pow(OPS_ACC(x1_B0, 0,0,0), 10) - 1.03104386401594e-16*pow(OPS_ACC(x1_B0, 0,0,0), 36) -
      4.25687501595231e-22*pow(OPS_ACC(x1_B0, 0,0,0), 45) - 1.63208286958713e-7*pow(OPS_ACC(x1_B0, 0,0,0), 19) -
      0.000172963130675947*pow(OPS_ACC(x1_B0, 0,0,0), 11) - 1.03892000788701e-11*pow(OPS_ACC(x1_B0, 0,0,0), 25) -
      1.89304810551059e-23*pow(OPS_ACC(x1_B0, 0,0,0), 49) - 1.1378430342786e-5*pow(OPS_ACC(x1_B0, 0,0,0), 15) -
      1.24342987020385e-5*pow(OPS_ACC(x1_B0, 0,0,0), 13) - 5.70270018671184e-21*pow(OPS_ACC(x1_B0, 0,0,0), 44) -
      2.49689949922651e-11*pow(OPS_ACC(x1_B0, 0,0,0), 26) - 1.58801109347899e-12*pow(OPS_ACC(x1_B0, 0,0,0), 28) -
      2.46652489644593e-20*pow(OPS_ACC(x1_B0, 0,0,0), 42)
)
: (
   0.00564965542946911
));

    T = ((OPS_ACC(x1_B0, 0,0,0) < 3.47434743474347) ? (
   1.6761935358689 + 3.06271483864277e-12*pow(OPS_ACC(x1_B0, 0,0,0), 28) +
      2.79501807927091e-7*pow(OPS_ACC(x1_B0, 0,0,0), 20) + 0.00248603775823404*pow(OPS_ACC(x1_B0, 0,0,0), 13) +
      5.25705556202282e-6*pow(OPS_ACC(x1_B0, 0,0,0), 18) + 4.19441885278622e-10*pow(OPS_ACC(x1_B0, 0,0,0), 26) +
      1.03697988973593e-15*pow(OPS_ACC(x1_B0, 0,0,0), 36) + 2.23763761894274e-6*pow(OPS_ACC(x1_B0, 0,0,0), 19) +
      1.89606475958188e-14*pow(OPS_ACC(x1_B0, 0,0,0), 34) + 0.026058157490231*pow(OPS_ACC(x1_B0, 0,0,0), 9) +
      2.85584693354611e-14*pow(OPS_ACC(x1_B0, 0,0,0), 33) + 0.015991867493063*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) +
      0.0005690725244923*pow(OPS_ACC(x1_B0, 0,0,0), 14) + 7.67501678614382e-20*pow(OPS_ACC(x1_B0, 0,0,0), 44) +
      3.08132092448187e-22*pow(OPS_ACC(x1_B0, 0,0,0), 49) + 9.11642836523477e-11*pow(OPS_ACC(x1_B0, 0,0,0), 27) +
      0.0548594064582554*pow(OPS_ACC(x1_B0, 0,0,0), 10) + 9.68279103389392e-10*pow(OPS_ACC(x1_B0, 0,0,0), 25) +
      0.267013266890081*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) +
      7.42471367623149e-5*OPS_ACC(x1_B0, 0,0,0) + 2.60932186295564e-22*pow(OPS_ACC(x1_B0, 0,0,0), 45) +
      3.30298013300648e-19*pow(OPS_ACC(x1_B0, 0,0,0), 43) + 6.69000978601176e-19*pow(OPS_ACC(x1_B0, 0,0,0), 42) +
      5.96572790520319e-15*pow(OPS_ACC(x1_B0, 0,0,0), 35) + 0.461494982556074*pow(OPS_ACC(x1_B0, 0,0,0), 7) -
      0.103275520631868*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) - 1.09723055742956e-16*pow(OPS_ACC(x1_B0, 0,0,0),
      38) - 7.62484344426692e-14*pow(OPS_ACC(x1_B0, 0,0,0), 32) - 1.00465393403514e-17*pow(OPS_ACC(x1_B0, 0,0,0), 40) -
      0.0232212941855831*pow(OPS_ACC(x1_B0, 0,0,0), 11) - 9.35036870885335e-8*pow(OPS_ACC(x1_B0, 0,0,0), 21) -
      4.75320969485837e-17*pow(OPS_ACC(x1_B0, 0,0,0), 37) - 1.33864284194856e-8*pow(OPS_ACC(x1_B0, 0,0,0), 23) -
      7.24235209743116e-21*pow(OPS_ACC(x1_B0, 0,0,0), 46) - 5.06193774226224e-19*pow(OPS_ACC(x1_B0, 0,0,0), 41) -
      0.000147531418293449*pow(OPS_ACC(x1_B0, 0,0,0), 15) - 3.7998675019817e-23*pow(OPS_ACC(x1_B0, 0,0,0), 50) -
      6.28278116396064e-12*pow(OPS_ACC(x1_B0, 0,0,0), 29) - 0.00342181201749505*pow(OPS_ACC(x1_B0, 0,0,0), 12) -
      5.70558210049695e-8*pow(OPS_ACC(x1_B0, 0,0,0), 22) - 0.262070265688791*pow(OPS_ACC(x1_B0, 0,0,0), 8) -
      0.291740706219782*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) - 8.17081805890689e-24*pow(OPS_ACC(x1_B0, 0,0,0), 48) -
      8.31714025029611e-5*pow(OPS_ACC(x1_B0, 0,0,0), 16) - 2.58561171573909e-21*pow(OPS_ACC(x1_B0, 0,0,0), 47) -
      3.6991053156892e-10*pow(OPS_ACC(x1_B0, 0,0,0), 24) - 4.44270004249955e-17*pow(OPS_ACC(x1_B0, 0,0,0), 39) -
      2.9329528860808e-12*pow(OPS_ACC(x1_B0, 0,0,0), 30) - 7.39485082875593e-13*pow(OPS_ACC(x1_B0, 0,0,0), 31) -
      0.425422766143187*(OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)*OPS_ACC(x1_B0, 0,0,0)) -
      7.3582999408868e-6*pow(OPS_ACC(x1_B0, 0,0,0), 17)
)
: (
   1.00000058888713
));

   rho = 1.0/T;

   OPS_ACC(rho_B0, 0,0,0) = rho;

   OPS_ACC(rhou0_B0, 0,0,0) = rhou0;

   OPS_ACC(rhou1_B0, 0,0,0) = rhou1;

   OPS_ACC(rhoE_B0, 0,0,0) = (0.5*(rhou0*rhou0) + 0.5*(rhou1*rhou1))/rho + invgama*inv2Minf*inv_gamma_m1*T*rho;

   OPS_ACC(rhou2_B0, 0,0,0) = 0.0;

}


void opensbliblock00Kernel067_c_wrapper(
  double *p_a0,
  double *p_a1,
  double *p_a2,
  double *p_a3,
  double *p_a4,
  double *p_a5,
  double *p_a6,
  double *p_a7,
  int *p_a8,
  int arg_idx0, int arg_idx1, int arg_idx2,
  int x_size, int y_size, int z_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1,p_a2,p_a3,p_a4,p_a5,p_a6,p_a7)
  #pragma acc loop
  #endif
  for ( int n_z=0; n_z<z_size; n_z++ ){
    #ifdef OPS_GPU
    #pragma acc loop
    #endif
    for ( int n_y=0; n_y<y_size; n_y++ ){
      #ifdef OPS_GPU
      #pragma acc loop
      #endif
      for ( int n_x=0; n_x<x_size; n_x++ ){
        int arg_idx[] = {arg_idx0+n_x, arg_idx1+n_y, arg_idx2+n_z};
        ptr_double ptr0 = {  p_a0 + n_x*1*1 + n_y*xdim0_opensbliblock00Kernel067*1*1 + n_z*xdim0_opensbliblock00Kernel067*ydim0_opensbliblock00Kernel067*1*1, xdim0_opensbliblock00Kernel067, ydim0_opensbliblock00Kernel067};
        ptr_double ptr1 = {  p_a1 + n_x*1*1 + n_y*xdim1_opensbliblock00Kernel067*1*1 + n_z*xdim1_opensbliblock00Kernel067*ydim1_opensbliblock00Kernel067*1*1, xdim1_opensbliblock00Kernel067, ydim1_opensbliblock00Kernel067};
        ptr_double ptr2 = {  p_a2 + n_x*1*1 + n_y*xdim2_opensbliblock00Kernel067*1*1 + n_z*xdim2_opensbliblock00Kernel067*ydim2_opensbliblock00Kernel067*1*1, xdim2_opensbliblock00Kernel067, ydim2_opensbliblock00Kernel067};
        ptr_double ptr3 = {  p_a3 + n_x*1*1 + n_y*xdim3_opensbliblock00Kernel067*1*1 + n_z*xdim3_opensbliblock00Kernel067*ydim3_opensbliblock00Kernel067*1*1, xdim3_opensbliblock00Kernel067, ydim3_opensbliblock00Kernel067};
        ptr_double ptr4 = {  p_a4 + n_x*1*1 + n_y*xdim4_opensbliblock00Kernel067*1*1 + n_z*xdim4_opensbliblock00Kernel067*ydim4_opensbliblock00Kernel067*1*1, xdim4_opensbliblock00Kernel067, ydim4_opensbliblock00Kernel067};
        ptr_double ptr5 = {  p_a5 + n_x*1*1 + n_y*xdim5_opensbliblock00Kernel067*1*1 + n_z*xdim5_opensbliblock00Kernel067*ydim5_opensbliblock00Kernel067*1*1, xdim5_opensbliblock00Kernel067, ydim5_opensbliblock00Kernel067};
        ptr_double ptr6 = {  p_a6 + n_x*1*1 + n_y*xdim6_opensbliblock00Kernel067*1*1 + n_z*xdim6_opensbliblock00Kernel067*ydim6_opensbliblock00Kernel067*1*1, xdim6_opensbliblock00Kernel067, ydim6_opensbliblock00Kernel067};
        ptr_double ptr7 = {  p_a7 + n_x*1*1 + n_y*xdim7_opensbliblock00Kernel067*1*1 + n_z*xdim7_opensbliblock00Kernel067*ydim7_opensbliblock00Kernel067*1*1, xdim7_opensbliblock00Kernel067, ydim7_opensbliblock00Kernel067};
        opensbliblock00Kernel067( ptr0, ptr1, ptr2, ptr3,
           ptr4, ptr5, ptr6, ptr7,
          arg_idx);
      }
    }
  }
}
