//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel002;
int ydim0_opensbliblock00Kernel002;
int xdim1_opensbliblock00Kernel002;
int ydim1_opensbliblock00Kernel002;
int xdim2_opensbliblock00Kernel002;
int ydim2_opensbliblock00Kernel002;
int xdim3_opensbliblock00Kernel002;
int ydim3_opensbliblock00Kernel002;
int xdim4_opensbliblock00Kernel002;
int ydim4_opensbliblock00Kernel002;
int xdim5_opensbliblock00Kernel002;
int ydim5_opensbliblock00Kernel002;
int xdim6_opensbliblock00Kernel002;
int ydim6_opensbliblock00Kernel002;
int xdim7_opensbliblock00Kernel002;
int ydim7_opensbliblock00Kernel002;
int xdim8_opensbliblock00Kernel002;
int ydim8_opensbliblock00Kernel002;
int xdim9_opensbliblock00Kernel002;
int ydim9_opensbliblock00Kernel002;
int xdim10_opensbliblock00Kernel002;
int ydim10_opensbliblock00Kernel002;
int xdim11_opensbliblock00Kernel002;
int ydim11_opensbliblock00Kernel002;
int xdim12_opensbliblock00Kernel002;
int ydim12_opensbliblock00Kernel002;
int xdim13_opensbliblock00Kernel002;
int ydim13_opensbliblock00Kernel002;
int xdim14_opensbliblock00Kernel002;
int ydim14_opensbliblock00Kernel002;
int xdim15_opensbliblock00Kernel002;
int ydim15_opensbliblock00Kernel002;
int xdim16_opensbliblock00Kernel002;
int ydim16_opensbliblock00Kernel002;


//user function



void opensbliblock00Kernel002_c_wrapper(
  double * restrict u0_B0_p,
  double * restrict u2_B0_p,
  double * restrict detJ_B0_p,
  double * restrict u1_B0_p,
  double * restrict rho_B0_p,
  double * restrict rhou1_B0_p,
  double * restrict a_B0_p,
  double * restrict rhoE_B0_p,
  double * restrict U2_B0_p,
  double * restrict rhou2_B0_p,
  double * restrict p_B0_p,
  double * restrict rhou0_B0_p,
  double * restrict wk10_B0_p,
  double * restrict wk13_B0_p,
  double * restrict wk11_B0_p,
  double * restrict wk12_B0_p,
  double * restrict wk14_B0_p,
  int x_size, int y_size, int z_size) {
  #pragma omp parallel for
  for ( int n_z=0; n_z<z_size; n_z++ ){
    for ( int n_y=0; n_y<y_size; n_y++ ){
      for ( int n_x=0; n_x<x_size; n_x++ ){
        const ptr_double u0_B0 = { u0_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel002*1 + n_z * xdim0_opensbliblock00Kernel002 * ydim0_opensbliblock00Kernel002*1, xdim0_opensbliblock00Kernel002, ydim0_opensbliblock00Kernel002};
        const ptr_double u2_B0 = { u2_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel002*1 + n_z * xdim1_opensbliblock00Kernel002 * ydim1_opensbliblock00Kernel002*1, xdim1_opensbliblock00Kernel002, ydim1_opensbliblock00Kernel002};
        const ptr_double detJ_B0 = { detJ_B0_p + n_x*1 + n_y * xdim2_opensbliblock00Kernel002*1 + n_z * xdim2_opensbliblock00Kernel002 * ydim2_opensbliblock00Kernel002*1, xdim2_opensbliblock00Kernel002, ydim2_opensbliblock00Kernel002};
        const ptr_double u1_B0 = { u1_B0_p + n_x*1 + n_y * xdim3_opensbliblock00Kernel002*1 + n_z * xdim3_opensbliblock00Kernel002 * ydim3_opensbliblock00Kernel002*1, xdim3_opensbliblock00Kernel002, ydim3_opensbliblock00Kernel002};
        const ptr_double rho_B0 = { rho_B0_p + n_x*1 + n_y * xdim4_opensbliblock00Kernel002*1 + n_z * xdim4_opensbliblock00Kernel002 * ydim4_opensbliblock00Kernel002*1, xdim4_opensbliblock00Kernel002, ydim4_opensbliblock00Kernel002};
        const ptr_double rhou1_B0 = { rhou1_B0_p + n_x*1 + n_y * xdim5_opensbliblock00Kernel002*1 + n_z * xdim5_opensbliblock00Kernel002 * ydim5_opensbliblock00Kernel002*1, xdim5_opensbliblock00Kernel002, ydim5_opensbliblock00Kernel002};
        const ptr_double a_B0 = { a_B0_p + n_x*1 + n_y * xdim6_opensbliblock00Kernel002*1 + n_z * xdim6_opensbliblock00Kernel002 * ydim6_opensbliblock00Kernel002*1, xdim6_opensbliblock00Kernel002, ydim6_opensbliblock00Kernel002};
        const ptr_double rhoE_B0 = { rhoE_B0_p + n_x*1 + n_y * xdim7_opensbliblock00Kernel002*1 + n_z * xdim7_opensbliblock00Kernel002 * ydim7_opensbliblock00Kernel002*1, xdim7_opensbliblock00Kernel002, ydim7_opensbliblock00Kernel002};
        const ptr_double U2_B0 = { U2_B0_p + n_x*1 + n_y * xdim8_opensbliblock00Kernel002*1 + n_z * xdim8_opensbliblock00Kernel002 * ydim8_opensbliblock00Kernel002*1, xdim8_opensbliblock00Kernel002, ydim8_opensbliblock00Kernel002};
        const ptr_double rhou2_B0 = { rhou2_B0_p + n_x*1 + n_y * xdim9_opensbliblock00Kernel002*1 + n_z * xdim9_opensbliblock00Kernel002 * ydim9_opensbliblock00Kernel002*1, xdim9_opensbliblock00Kernel002, ydim9_opensbliblock00Kernel002};
        const ptr_double p_B0 = { p_B0_p + n_x*1 + n_y * xdim10_opensbliblock00Kernel002*1 + n_z * xdim10_opensbliblock00Kernel002 * ydim10_opensbliblock00Kernel002*1, xdim10_opensbliblock00Kernel002, ydim10_opensbliblock00Kernel002};
        const ptr_double rhou0_B0 = { rhou0_B0_p + n_x*1 + n_y * xdim11_opensbliblock00Kernel002*1 + n_z * xdim11_opensbliblock00Kernel002 * ydim11_opensbliblock00Kernel002*1, xdim11_opensbliblock00Kernel002, ydim11_opensbliblock00Kernel002};
        ptr_double wk10_B0 = { wk10_B0_p + n_x*1 + n_y * xdim12_opensbliblock00Kernel002*1 + n_z * xdim12_opensbliblock00Kernel002 * ydim12_opensbliblock00Kernel002*1, xdim12_opensbliblock00Kernel002, ydim12_opensbliblock00Kernel002};
        ptr_double wk13_B0 = { wk13_B0_p + n_x*1 + n_y * xdim13_opensbliblock00Kernel002*1 + n_z * xdim13_opensbliblock00Kernel002 * ydim13_opensbliblock00Kernel002*1, xdim13_opensbliblock00Kernel002, ydim13_opensbliblock00Kernel002};
        ptr_double wk11_B0 = { wk11_B0_p + n_x*1 + n_y * xdim14_opensbliblock00Kernel002*1 + n_z * xdim14_opensbliblock00Kernel002 * ydim14_opensbliblock00Kernel002*1, xdim14_opensbliblock00Kernel002, ydim14_opensbliblock00Kernel002};
        ptr_double wk12_B0 = { wk12_B0_p + n_x*1 + n_y * xdim15_opensbliblock00Kernel002*1 + n_z * xdim15_opensbliblock00Kernel002 * ydim15_opensbliblock00Kernel002*1, xdim15_opensbliblock00Kernel002, ydim15_opensbliblock00Kernel002};
        ptr_double wk14_B0 = { wk14_B0_p + n_x*1 + n_y * xdim16_opensbliblock00Kernel002*1 + n_z * xdim16_opensbliblock00Kernel002 * ydim16_opensbliblock00Kernel002*1, xdim16_opensbliblock00Kernel002, ydim16_opensbliblock00Kernel002};
        
   double CF_24 = 0.0;
   double CF_03 = 0.0;
   double AVG_2_2_LEV_23 = 0.0;
   double CF_23 = 0.0;
   double AVG_2_2_LEV_10 = 0.0;
   double AVG_2_2_LEV_42 = 0.0;
   double max_lambda_2_44 = 0.0;
   double CF_10 = 0.0;
   double AVG_2_rho = 0.0;
   double AVG_2_u2 = 0.0;
   double AVG_2_a = 0.0;
   double AVG_2_u1 = 0.0;
   double AVG_2_2_LEV_24 = 0.0;
   double CF_11 = 0.0;
   double CF_21 = 0.0;
   double CF_05 = 0.0;
   double CS_05 = 0.0;
   double CS_31 = 0.0;
   double alpha_1 = 0.0;
   double AVG_2_2_LEV_20 = 0.0;
   double Recon_0 = 0.0;
   double AVG_2_2_LEV_31 = 0.0;
   double CS_30 = 0.0;
   double AVG_2_2_LEV_40 = 0.0;
   double beta_2 = 0.0;
   double omega_0 = 0.0;
   double CF_42 = 0.0;
   double CS_11 = 0.0;
   double CS_02 = 0.0;
   double AVG_2_2_LEV_30 = 0.0;
   double CS_32 = 0.0;
   double CF_22 = 0.0;
   double CS_33 = 0.0;
   double CS_45 = 0.0;
   double CS_40 = 0.0;
   double CS_15 = 0.0;
   double AVG_2_2_LEV_02 = 0.0;
   double CS_35 = 0.0;
   double CS_43 = 0.0;
   double CF_35 = 0.0;
   double alpha_0 = 0.0;
   double CS_13 = 0.0;
   double AVG_2_2_LEV_34 = 0.0;
   double CF_32 = 0.0;
   double CF_34 = 0.0;
   double CF_44 = 0.0;
   double CF_40 = 0.0;
   double CS_20 = 0.0;
   double CS_34 = 0.0;
   double CF_00 = 0.0;
   double CF_30 = 0.0;
   double CS_00 = 0.0;
   double CS_12 = 0.0;
   double AVG_2_2_LEV_43 = 0.0;
   double CS_21 = 0.0;
   double CS_23 = 0.0;
   double CS_25 = 0.0;
   double AVG_2_u0 = 0.0;
   double CS_01 = 0.0;
   double CF_04 = 0.0;
   double CS_14 = 0.0;
   double CS_04 = 0.0;
   double CF_02 = 0.0;
   double CF_13 = 0.0;
   double alpha_2 = 0.0;
   double omega_2 = 0.0;
   double CF_01 = 0.0;
   double CF_41 = 0.0;
   double omega_1 = 0.0;
   double max_lambda_2_33 = 0.0;
   double AVG_2_2_LEV_41 = 0.0;
   double CF_15 = 0.0;
   double CS_22 = 0.0;
   double AVG_2_2_LEV_11 = 0.0;
   double beta_0 = 0.0;
   double AVG_2_2_LEV_32 = 0.0;
   double CS_24 = 0.0;
   double max_lambda_2_22 = 0.0;
   double max_lambda_2_00 = 0.0;
   double CF_33 = 0.0;
   double Recon_3 = 0.0;
   double AVG_2_2_LEV_33 = 0.0;
   double max_lambda_2_11 = 0.0;
   double Recon_2 = 0.0;
   double CF_12 = 0.0;
   double AVG_2_2_LEV_44 = 0.0;
   double CF_25 = 0.0;
   double beta_1 = 0.0;
   double CF_20 = 0.0;
   double CF_31 = 0.0;
   double CS_41 = 0.0;
   double CF_14 = 0.0;
   double Recon_1 = 0.0;
   double AVG_2_2_LEV_21 = 0.0;
   double inv_AVG_rho = 0.0;
   double AVG_2_2_LEV_22 = 0.0;
   double CF_45 = 0.0;
   double CS_44 = 0.0;
   double CS_10 = 0.0;
   double CF_43 = 0.0;
   double CS_03 = 0.0;
   double AVG_2_2_LEV_00 = 0.0;
   double CS_42 = 0.0;
   double inv_AVG_a = 0.0;
   double inv_alpha_sum = 0.0;
   double Recon_4 = 0.0;
   AVG_2_rho = (rc9)*(OPS_ACC(rho_B0, 0,0,1) + OPS_ACC(rho_B0, 0,0,0));

   AVG_2_a = (rc9)*(OPS_ACC(a_B0, 0,0,1) + OPS_ACC(a_B0, 0,0,0));

   AVG_2_u1 = (rc9)*(OPS_ACC(u1_B0, 0,0,1) + OPS_ACC(u1_B0, 0,0,0));

   AVG_2_u0 = (rc9)*(OPS_ACC(u0_B0, 0,0,0) + OPS_ACC(u0_B0, 0,0,1));

   AVG_2_u2 = (rc9)*(OPS_ACC(u2_B0, 0,0,0) + OPS_ACC(u2_B0, 0,0,1));

   inv_AVG_a = 1.0/AVG_2_a;

   inv_AVG_rho = 1.0/AVG_2_rho;

   AVG_2_2_LEV_00 = -AVG_2_u1*inv_AVG_rho;

   AVG_2_2_LEV_02 = inv_AVG_rho;

   AVG_2_2_LEV_10 = AVG_2_u0*inv_AVG_rho;

   AVG_2_2_LEV_11 = -inv_AVG_rho;

    AVG_2_2_LEV_20 = -rc9*(gama*pow(AVG_2_u0, 2)*pow(inv_AVG_a, 2) + gama*pow(AVG_2_u1, 2)*pow(inv_AVG_a, 2) +
      gama*pow(AVG_2_u2, 2)*pow(inv_AVG_a, 2) - pow(AVG_2_u0, 2)*pow(inv_AVG_a, 2) - pow(AVG_2_u1, 2)*pow(inv_AVG_a, 2)
      - pow(AVG_2_u2, 2)*pow(inv_AVG_a, 2) - 2);

   AVG_2_2_LEV_21 = gamma_m1*AVG_2_u0*pow(inv_AVG_a, 2);

   AVG_2_2_LEV_22 = gamma_m1*AVG_2_u1*pow(inv_AVG_a, 2);

   AVG_2_2_LEV_23 = gamma_m1*AVG_2_u2*pow(inv_AVG_a, 2);

   AVG_2_2_LEV_24 = -gamma_m1*pow(inv_AVG_a, 2);

    AVG_2_2_LEV_30 = -0.353553390593274*inv_AVG_a*inv_AVG_rho*(-gama*pow(AVG_2_u0, 2) - gama*pow(AVG_2_u1, 2) -
      gama*pow(AVG_2_u2, 2) + 2*AVG_2_a*AVG_2_u2 + pow(AVG_2_u0, 2) + pow(AVG_2_u1, 2) + pow(AVG_2_u2, 2));

   AVG_2_2_LEV_31 = -0.707106781186547*gamma_m1*AVG_2_u0*inv_AVG_a*inv_AVG_rho;

   AVG_2_2_LEV_32 = -0.707106781186547*gamma_m1*AVG_2_u1*inv_AVG_a*inv_AVG_rho;

   AVG_2_2_LEV_33 = 0.707106781186547*inv_AVG_a*inv_AVG_rho*(-gama*AVG_2_u2 + AVG_2_a + AVG_2_u2);

   AVG_2_2_LEV_34 = 0.707106781186547*gamma_m1*inv_AVG_a*inv_AVG_rho;

    AVG_2_2_LEV_40 = 0.353553390593274*inv_AVG_a*inv_AVG_rho*(gama*pow(AVG_2_u0, 2) + gama*pow(AVG_2_u1, 2) +
      gama*pow(AVG_2_u2, 2) + 2*AVG_2_a*AVG_2_u2 - pow(AVG_2_u0, 2) - pow(AVG_2_u1, 2) - pow(AVG_2_u2, 2));

   AVG_2_2_LEV_41 = -0.707106781186547*gamma_m1*AVG_2_u0*inv_AVG_a*inv_AVG_rho;

   AVG_2_2_LEV_42 = -0.707106781186547*gamma_m1*AVG_2_u1*inv_AVG_a*inv_AVG_rho;

   AVG_2_2_LEV_43 = -0.707106781186547*inv_AVG_a*inv_AVG_rho*(gama*AVG_2_u2 + AVG_2_a - AVG_2_u2);

   AVG_2_2_LEV_44 = 0.707106781186547*gamma_m1*inv_AVG_a*inv_AVG_rho;

    CF_00 = (AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,-2) +
      AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,-2))*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(detJ_B0, 0,0,-2);

    CF_10 = (AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,-2) +
      AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,-2))*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(detJ_B0, 0,0,-2);

    CF_20 = (AVG_2_2_LEV_20*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rho_B0, 0,0,-2) +
      AVG_2_2_LEV_21*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou0_B0, 0,0,-2) +
      AVG_2_2_LEV_22*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou1_B0, 0,0,-2) +
      AVG_2_2_LEV_23*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou2_B0, 0,0,-2) + AVG_2_2_LEV_23*OPS_ACC(p_B0, 0,0,-2) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(p_B0, 0,0,-2) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhoE_B0, 0,0,-2))*OPS_ACC(detJ_B0, 0,0,-2);

    CF_30 = (AVG_2_2_LEV_30*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rho_B0, 0,0,-2) +
      AVG_2_2_LEV_31*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou0_B0, 0,0,-2) +
      AVG_2_2_LEV_32*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou1_B0, 0,0,-2) +
      AVG_2_2_LEV_33*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou2_B0, 0,0,-2) + AVG_2_2_LEV_33*OPS_ACC(p_B0, 0,0,-2) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(p_B0, 0,0,-2) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhoE_B0, 0,0,-2))*OPS_ACC(detJ_B0, 0,0,-2);

    CF_40 = (AVG_2_2_LEV_40*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rho_B0, 0,0,-2) +
      AVG_2_2_LEV_41*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou0_B0, 0,0,-2) +
      AVG_2_2_LEV_42*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou1_B0, 0,0,-2) +
      AVG_2_2_LEV_43*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhou2_B0, 0,0,-2) + AVG_2_2_LEV_43*OPS_ACC(p_B0, 0,0,-2) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(p_B0, 0,0,-2) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,-2)*OPS_ACC(rhoE_B0, 0,0,-2))*OPS_ACC(detJ_B0, 0,0,-2);

    CF_01 = (AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,-1) +
      AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,-1))*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(detJ_B0, 0,0,-1);

    CF_11 = (AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,-1) +
      AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,-1))*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(detJ_B0, 0,0,-1);

    CF_21 = (AVG_2_2_LEV_20*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rho_B0, 0,0,-1) +
      AVG_2_2_LEV_21*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou0_B0, 0,0,-1) +
      AVG_2_2_LEV_22*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou1_B0, 0,0,-1) +
      AVG_2_2_LEV_23*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou2_B0, 0,0,-1) + AVG_2_2_LEV_23*OPS_ACC(p_B0, 0,0,-1) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(p_B0, 0,0,-1) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhoE_B0, 0,0,-1))*OPS_ACC(detJ_B0, 0,0,-1);

    CF_31 = (AVG_2_2_LEV_30*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rho_B0, 0,0,-1) +
      AVG_2_2_LEV_31*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou0_B0, 0,0,-1) +
      AVG_2_2_LEV_32*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou1_B0, 0,0,-1) +
      AVG_2_2_LEV_33*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou2_B0, 0,0,-1) + AVG_2_2_LEV_33*OPS_ACC(p_B0, 0,0,-1) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(p_B0, 0,0,-1) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhoE_B0, 0,0,-1))*OPS_ACC(detJ_B0, 0,0,-1);

    CF_41 = (AVG_2_2_LEV_40*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rho_B0, 0,0,-1) +
      AVG_2_2_LEV_41*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou0_B0, 0,0,-1) +
      AVG_2_2_LEV_42*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou1_B0, 0,0,-1) +
      AVG_2_2_LEV_43*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhou2_B0, 0,0,-1) + AVG_2_2_LEV_43*OPS_ACC(p_B0, 0,0,-1) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(p_B0, 0,0,-1) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,-1)*OPS_ACC(rhoE_B0, 0,0,-1))*OPS_ACC(detJ_B0, 0,0,-1);

    CF_02 = (AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,0) +
      AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,0))*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(detJ_B0, 0,0,0);

    CF_12 = (AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,0) +
      AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,0))*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(detJ_B0, 0,0,0);

    CF_22 = (AVG_2_2_LEV_20*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rho_B0, 0,0,0) +
      AVG_2_2_LEV_21*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou0_B0, 0,0,0) +
      AVG_2_2_LEV_22*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou1_B0, 0,0,0) +
      AVG_2_2_LEV_23*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou2_B0, 0,0,0) + AVG_2_2_LEV_23*OPS_ACC(p_B0, 0,0,0) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(p_B0, 0,0,0) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhoE_B0, 0,0,0))*OPS_ACC(detJ_B0, 0,0,0);

    CF_32 = (AVG_2_2_LEV_30*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rho_B0, 0,0,0) +
      AVG_2_2_LEV_31*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou0_B0, 0,0,0) +
      AVG_2_2_LEV_32*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou1_B0, 0,0,0) +
      AVG_2_2_LEV_33*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou2_B0, 0,0,0) + AVG_2_2_LEV_33*OPS_ACC(p_B0, 0,0,0) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(p_B0, 0,0,0) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhoE_B0, 0,0,0))*OPS_ACC(detJ_B0, 0,0,0);

    CF_42 = (AVG_2_2_LEV_40*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rho_B0, 0,0,0) +
      AVG_2_2_LEV_41*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou0_B0, 0,0,0) +
      AVG_2_2_LEV_42*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou1_B0, 0,0,0) +
      AVG_2_2_LEV_43*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhou2_B0, 0,0,0) + AVG_2_2_LEV_43*OPS_ACC(p_B0, 0,0,0) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(p_B0, 0,0,0) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,0)*OPS_ACC(rhoE_B0, 0,0,0))*OPS_ACC(detJ_B0, 0,0,0);

    CF_03 = (AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,1) +
      AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,1))*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(detJ_B0, 0,0,1);

    CF_13 = (AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,1) +
      AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,1))*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(detJ_B0, 0,0,1);

    CF_23 = (AVG_2_2_LEV_20*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rho_B0, 0,0,1) +
      AVG_2_2_LEV_21*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou0_B0, 0,0,1) +
      AVG_2_2_LEV_22*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou1_B0, 0,0,1) +
      AVG_2_2_LEV_23*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou2_B0, 0,0,1) + AVG_2_2_LEV_23*OPS_ACC(p_B0, 0,0,1) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(p_B0, 0,0,1) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhoE_B0, 0,0,1))*OPS_ACC(detJ_B0, 0,0,1);

    CF_33 = (AVG_2_2_LEV_30*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rho_B0, 0,0,1) +
      AVG_2_2_LEV_31*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou0_B0, 0,0,1) +
      AVG_2_2_LEV_32*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou1_B0, 0,0,1) +
      AVG_2_2_LEV_33*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou2_B0, 0,0,1) + AVG_2_2_LEV_33*OPS_ACC(p_B0, 0,0,1) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(p_B0, 0,0,1) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhoE_B0, 0,0,1))*OPS_ACC(detJ_B0, 0,0,1);

    CF_43 = (AVG_2_2_LEV_40*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rho_B0, 0,0,1) +
      AVG_2_2_LEV_41*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou0_B0, 0,0,1) +
      AVG_2_2_LEV_42*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou1_B0, 0,0,1) +
      AVG_2_2_LEV_43*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhou2_B0, 0,0,1) + AVG_2_2_LEV_43*OPS_ACC(p_B0, 0,0,1) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(p_B0, 0,0,1) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,1)*OPS_ACC(rhoE_B0, 0,0,1))*OPS_ACC(detJ_B0, 0,0,1);

    CF_04 = (AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,2) +
      AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,2))*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(detJ_B0, 0,0,2);

    CF_14 = (AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,2) +
      AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,2))*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(detJ_B0, 0,0,2);

    CF_24 = (AVG_2_2_LEV_20*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rho_B0, 0,0,2) +
      AVG_2_2_LEV_21*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou0_B0, 0,0,2) +
      AVG_2_2_LEV_22*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou1_B0, 0,0,2) +
      AVG_2_2_LEV_23*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou2_B0, 0,0,2) + AVG_2_2_LEV_23*OPS_ACC(p_B0, 0,0,2) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(p_B0, 0,0,2) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhoE_B0, 0,0,2))*OPS_ACC(detJ_B0, 0,0,2);

    CF_34 = (AVG_2_2_LEV_30*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rho_B0, 0,0,2) +
      AVG_2_2_LEV_31*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou0_B0, 0,0,2) +
      AVG_2_2_LEV_32*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou1_B0, 0,0,2) +
      AVG_2_2_LEV_33*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou2_B0, 0,0,2) + AVG_2_2_LEV_33*OPS_ACC(p_B0, 0,0,2) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(p_B0, 0,0,2) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhoE_B0, 0,0,2))*OPS_ACC(detJ_B0, 0,0,2);

    CF_44 = (AVG_2_2_LEV_40*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rho_B0, 0,0,2) +
      AVG_2_2_LEV_41*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou0_B0, 0,0,2) +
      AVG_2_2_LEV_42*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou1_B0, 0,0,2) +
      AVG_2_2_LEV_43*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhou2_B0, 0,0,2) + AVG_2_2_LEV_43*OPS_ACC(p_B0, 0,0,2) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(p_B0, 0,0,2) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,2)*OPS_ACC(rhoE_B0, 0,0,2))*OPS_ACC(detJ_B0, 0,0,2);

    CF_05 = (AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,3) +
      AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,3))*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(detJ_B0, 0,0,3);

    CF_15 = (AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,3) +
      AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,3))*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(detJ_B0, 0,0,3);

    CF_25 = (AVG_2_2_LEV_20*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rho_B0, 0,0,3) +
      AVG_2_2_LEV_21*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou0_B0, 0,0,3) +
      AVG_2_2_LEV_22*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou1_B0, 0,0,3) +
      AVG_2_2_LEV_23*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou2_B0, 0,0,3) + AVG_2_2_LEV_23*OPS_ACC(p_B0, 0,0,3) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(p_B0, 0,0,3) +
      AVG_2_2_LEV_24*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhoE_B0, 0,0,3))*OPS_ACC(detJ_B0, 0,0,3);

    CF_35 = (AVG_2_2_LEV_30*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rho_B0, 0,0,3) +
      AVG_2_2_LEV_31*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou0_B0, 0,0,3) +
      AVG_2_2_LEV_32*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou1_B0, 0,0,3) +
      AVG_2_2_LEV_33*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou2_B0, 0,0,3) + AVG_2_2_LEV_33*OPS_ACC(p_B0, 0,0,3) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(p_B0, 0,0,3) +
      AVG_2_2_LEV_34*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhoE_B0, 0,0,3))*OPS_ACC(detJ_B0, 0,0,3);

    CF_45 = (AVG_2_2_LEV_40*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rho_B0, 0,0,3) +
      AVG_2_2_LEV_41*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou0_B0, 0,0,3) +
      AVG_2_2_LEV_42*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou1_B0, 0,0,3) +
      AVG_2_2_LEV_43*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhou2_B0, 0,0,3) + AVG_2_2_LEV_43*OPS_ACC(p_B0, 0,0,3) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(p_B0, 0,0,3) +
      AVG_2_2_LEV_44*OPS_ACC(U2_B0, 0,0,3)*OPS_ACC(rhoE_B0, 0,0,3))*OPS_ACC(detJ_B0, 0,0,3);

   CS_00 = AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,-2) + AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,-2);

   CS_01 = AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,-1) + AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,-1);

   CS_02 = AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,0) + AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,0);

   CS_03 = AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,1) + AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,1);

   CS_04 = AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,2) + AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,2);

   CS_05 = AVG_2_2_LEV_00*OPS_ACC(rho_B0, 0,0,3) + AVG_2_2_LEV_02*OPS_ACC(rhou1_B0, 0,0,3);

   CS_10 = AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,-2) + AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,-2);

   CS_11 = AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,-1) + AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,-1);

   CS_12 = AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,0) + AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,0);

   CS_13 = AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,1) + AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,1);

   CS_14 = AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,2) + AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,2);

   CS_15 = AVG_2_2_LEV_10*OPS_ACC(rho_B0, 0,0,3) + AVG_2_2_LEV_11*OPS_ACC(rhou0_B0, 0,0,3);

    CS_20 = AVG_2_2_LEV_20*OPS_ACC(rho_B0, 0,0,-2) + AVG_2_2_LEV_21*OPS_ACC(rhou0_B0, 0,0,-2) +
      AVG_2_2_LEV_22*OPS_ACC(rhou1_B0, 0,0,-2) + AVG_2_2_LEV_23*OPS_ACC(rhou2_B0, 0,0,-2) +
      AVG_2_2_LEV_24*OPS_ACC(rhoE_B0, 0,0,-2);

    CS_21 = AVG_2_2_LEV_20*OPS_ACC(rho_B0, 0,0,-1) + AVG_2_2_LEV_21*OPS_ACC(rhou0_B0, 0,0,-1) +
      AVG_2_2_LEV_22*OPS_ACC(rhou1_B0, 0,0,-1) + AVG_2_2_LEV_23*OPS_ACC(rhou2_B0, 0,0,-1) +
      AVG_2_2_LEV_24*OPS_ACC(rhoE_B0, 0,0,-1);

    CS_22 = AVG_2_2_LEV_20*OPS_ACC(rho_B0, 0,0,0) + AVG_2_2_LEV_21*OPS_ACC(rhou0_B0, 0,0,0) +
      AVG_2_2_LEV_22*OPS_ACC(rhou1_B0, 0,0,0) + AVG_2_2_LEV_23*OPS_ACC(rhou2_B0, 0,0,0) +
      AVG_2_2_LEV_24*OPS_ACC(rhoE_B0, 0,0,0);

    CS_23 = AVG_2_2_LEV_20*OPS_ACC(rho_B0, 0,0,1) + AVG_2_2_LEV_21*OPS_ACC(rhou0_B0, 0,0,1) +
      AVG_2_2_LEV_22*OPS_ACC(rhou1_B0, 0,0,1) + AVG_2_2_LEV_23*OPS_ACC(rhou2_B0, 0,0,1) +
      AVG_2_2_LEV_24*OPS_ACC(rhoE_B0, 0,0,1);

    CS_24 = AVG_2_2_LEV_20*OPS_ACC(rho_B0, 0,0,2) + AVG_2_2_LEV_21*OPS_ACC(rhou0_B0, 0,0,2) +
      AVG_2_2_LEV_22*OPS_ACC(rhou1_B0, 0,0,2) + AVG_2_2_LEV_23*OPS_ACC(rhou2_B0, 0,0,2) +
      AVG_2_2_LEV_24*OPS_ACC(rhoE_B0, 0,0,2);

    CS_25 = AVG_2_2_LEV_20*OPS_ACC(rho_B0, 0,0,3) + AVG_2_2_LEV_21*OPS_ACC(rhou0_B0, 0,0,3) +
      AVG_2_2_LEV_22*OPS_ACC(rhou1_B0, 0,0,3) + AVG_2_2_LEV_23*OPS_ACC(rhou2_B0, 0,0,3) +
      AVG_2_2_LEV_24*OPS_ACC(rhoE_B0, 0,0,3);

    CS_30 = AVG_2_2_LEV_30*OPS_ACC(rho_B0, 0,0,-2) + AVG_2_2_LEV_31*OPS_ACC(rhou0_B0, 0,0,-2) +
      AVG_2_2_LEV_32*OPS_ACC(rhou1_B0, 0,0,-2) + AVG_2_2_LEV_33*OPS_ACC(rhou2_B0, 0,0,-2) +
      AVG_2_2_LEV_34*OPS_ACC(rhoE_B0, 0,0,-2);

    CS_31 = AVG_2_2_LEV_30*OPS_ACC(rho_B0, 0,0,-1) + AVG_2_2_LEV_31*OPS_ACC(rhou0_B0, 0,0,-1) +
      AVG_2_2_LEV_32*OPS_ACC(rhou1_B0, 0,0,-1) + AVG_2_2_LEV_33*OPS_ACC(rhou2_B0, 0,0,-1) +
      AVG_2_2_LEV_34*OPS_ACC(rhoE_B0, 0,0,-1);

    CS_32 = AVG_2_2_LEV_30*OPS_ACC(rho_B0, 0,0,0) + AVG_2_2_LEV_31*OPS_ACC(rhou0_B0, 0,0,0) +
      AVG_2_2_LEV_32*OPS_ACC(rhou1_B0, 0,0,0) + AVG_2_2_LEV_33*OPS_ACC(rhou2_B0, 0,0,0) +
      AVG_2_2_LEV_34*OPS_ACC(rhoE_B0, 0,0,0);

    CS_33 = AVG_2_2_LEV_30*OPS_ACC(rho_B0, 0,0,1) + AVG_2_2_LEV_31*OPS_ACC(rhou0_B0, 0,0,1) +
      AVG_2_2_LEV_32*OPS_ACC(rhou1_B0, 0,0,1) + AVG_2_2_LEV_33*OPS_ACC(rhou2_B0, 0,0,1) +
      AVG_2_2_LEV_34*OPS_ACC(rhoE_B0, 0,0,1);

    CS_34 = AVG_2_2_LEV_30*OPS_ACC(rho_B0, 0,0,2) + AVG_2_2_LEV_31*OPS_ACC(rhou0_B0, 0,0,2) +
      AVG_2_2_LEV_32*OPS_ACC(rhou1_B0, 0,0,2) + AVG_2_2_LEV_33*OPS_ACC(rhou2_B0, 0,0,2) +
      AVG_2_2_LEV_34*OPS_ACC(rhoE_B0, 0,0,2);

    CS_35 = AVG_2_2_LEV_30*OPS_ACC(rho_B0, 0,0,3) + AVG_2_2_LEV_31*OPS_ACC(rhou0_B0, 0,0,3) +
      AVG_2_2_LEV_32*OPS_ACC(rhou1_B0, 0,0,3) + AVG_2_2_LEV_33*OPS_ACC(rhou2_B0, 0,0,3) +
      AVG_2_2_LEV_34*OPS_ACC(rhoE_B0, 0,0,3);

    CS_40 = AVG_2_2_LEV_40*OPS_ACC(rho_B0, 0,0,-2) + AVG_2_2_LEV_41*OPS_ACC(rhou0_B0, 0,0,-2) +
      AVG_2_2_LEV_42*OPS_ACC(rhou1_B0, 0,0,-2) + AVG_2_2_LEV_43*OPS_ACC(rhou2_B0, 0,0,-2) +
      AVG_2_2_LEV_44*OPS_ACC(rhoE_B0, 0,0,-2);

    CS_41 = AVG_2_2_LEV_40*OPS_ACC(rho_B0, 0,0,-1) + AVG_2_2_LEV_41*OPS_ACC(rhou0_B0, 0,0,-1) +
      AVG_2_2_LEV_42*OPS_ACC(rhou1_B0, 0,0,-1) + AVG_2_2_LEV_43*OPS_ACC(rhou2_B0, 0,0,-1) +
      AVG_2_2_LEV_44*OPS_ACC(rhoE_B0, 0,0,-1);

    CS_42 = AVG_2_2_LEV_40*OPS_ACC(rho_B0, 0,0,0) + AVG_2_2_LEV_41*OPS_ACC(rhou0_B0, 0,0,0) +
      AVG_2_2_LEV_42*OPS_ACC(rhou1_B0, 0,0,0) + AVG_2_2_LEV_43*OPS_ACC(rhou2_B0, 0,0,0) +
      AVG_2_2_LEV_44*OPS_ACC(rhoE_B0, 0,0,0);

    CS_43 = AVG_2_2_LEV_40*OPS_ACC(rho_B0, 0,0,1) + AVG_2_2_LEV_41*OPS_ACC(rhou0_B0, 0,0,1) +
      AVG_2_2_LEV_42*OPS_ACC(rhou1_B0, 0,0,1) + AVG_2_2_LEV_43*OPS_ACC(rhou2_B0, 0,0,1) +
      AVG_2_2_LEV_44*OPS_ACC(rhoE_B0, 0,0,1);

    CS_44 = AVG_2_2_LEV_40*OPS_ACC(rho_B0, 0,0,2) + AVG_2_2_LEV_41*OPS_ACC(rhou0_B0, 0,0,2) +
      AVG_2_2_LEV_42*OPS_ACC(rhou1_B0, 0,0,2) + AVG_2_2_LEV_43*OPS_ACC(rhou2_B0, 0,0,2) +
      AVG_2_2_LEV_44*OPS_ACC(rhoE_B0, 0,0,2);

    CS_45 = AVG_2_2_LEV_40*OPS_ACC(rho_B0, 0,0,3) + AVG_2_2_LEV_41*OPS_ACC(rhou0_B0, 0,0,3) +
      AVG_2_2_LEV_42*OPS_ACC(rhou1_B0, 0,0,3) + AVG_2_2_LEV_43*OPS_ACC(rhou2_B0, 0,0,3) +
      AVG_2_2_LEV_44*OPS_ACC(rhoE_B0, 0,0,3);

    max_lambda_2_00 = fmax(fabs(OPS_ACC(u2_B0, 0,0,-2)), fmax(fabs(OPS_ACC(u2_B0, 0,0,-1)),
      fmax(fabs(OPS_ACC(u2_B0, 0,0,3)), fmax(fabs(OPS_ACC(u2_B0, 0,0,0)), fmax(fabs(OPS_ACC(u2_B0, 0,0,1)),
      fabs(OPS_ACC(u2_B0, 0,0,2)))))));

   max_lambda_2_11 = max_lambda_2_00;

   max_lambda_2_22 = max_lambda_2_00;

    max_lambda_2_33 = fmax(fabs(OPS_ACC(a_B0, 0,0,2) + OPS_ACC(u2_B0, 0,0,2)), fmax(fabs(OPS_ACC(a_B0, 0,0,0) +
      OPS_ACC(u2_B0, 0,0,0)), fmax(fabs(OPS_ACC(a_B0, 0,0,-1) + OPS_ACC(u2_B0, 0,0,-1)),
      fmax(fabs(OPS_ACC(a_B0, 0,0,-2) + OPS_ACC(u2_B0, 0,0,-2)), fmax(fabs(OPS_ACC(a_B0, 0,0,3) +
      OPS_ACC(u2_B0, 0,0,3)), fabs(OPS_ACC(a_B0, 0,0,1) + OPS_ACC(u2_B0, 0,0,1)))))));

    max_lambda_2_44 = fmax(fabs(OPS_ACC(a_B0, 0,0,0) - OPS_ACC(u2_B0, 0,0,0)), fmax(fabs(OPS_ACC(a_B0, 0,0,3) -
      OPS_ACC(u2_B0, 0,0,3)), fmax(fabs(OPS_ACC(a_B0, 0,0,-1) - OPS_ACC(u2_B0, 0,0,-1)),
      fmax(fabs(OPS_ACC(a_B0, 0,0,-2) - OPS_ACC(u2_B0, 0,0,-2)), fmax(fabs(OPS_ACC(a_B0, 0,0,1) -
      OPS_ACC(u2_B0, 0,0,1)), fabs(OPS_ACC(a_B0, 0,0,2) - OPS_ACC(u2_B0, 0,0,2)))))));

    beta_0 = (rc9)*(CF_02 + CS_02*max_lambda_2_00)*((rc20)*(CF_02 + CS_02*max_lambda_2_00) - rc21*(CF_03 +
      CS_03*max_lambda_2_00) + (rc22)*(CF_04 + CS_04*max_lambda_2_00)) + (rc9)*(CF_03 +
      CS_03*max_lambda_2_00)*((rc23)*(CF_03 + CS_03*max_lambda_2_00) - rc24*(CF_04 + CS_04*max_lambda_2_00)) +
      (rc25)*pow(CF_04 + CS_04*max_lambda_2_00, 2);

    beta_1 = (rc9)*(CF_01 + CS_01*max_lambda_2_00)*((rc26)*(CF_01 + CS_01*max_lambda_2_00) - rc27*(CF_02 +
      CS_02*max_lambda_2_00) + (rc28)*(CF_03 + CS_03*max_lambda_2_00)) + (rc9)*(CF_02 +
      CS_02*max_lambda_2_00)*((rc27)*(CF_02 + CS_02*max_lambda_2_00) - rc27*(CF_03 + CS_03*max_lambda_2_00)) +
      (rc25)*pow(CF_03 + CS_03*max_lambda_2_00, 2);

    beta_2 = (rc9)*(CF_00 + CS_00*max_lambda_2_00)*((rc26)*(CF_00 + CS_00*max_lambda_2_00) + (rc22)*(CF_02 +
      CS_02*max_lambda_2_00)) + (rc9)*(CF_01 + CS_01*max_lambda_2_00)*(-rc24*(CF_00 + CS_00*max_lambda_2_00) +
      (rc23)*(CF_01 + CS_01*max_lambda_2_00) - rc21*(CF_02 + CS_02*max_lambda_2_00)) + (rc28)*pow(CF_02 +
      CS_02*max_lambda_2_00, 2);

   alpha_0 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_0 = Recon_0 + omega_0*((rc32)*(CF_02 + CS_02*max_lambda_2_00) + (rc33)*(CF_03 + CS_03*max_lambda_2_00) -
      rc16*(CF_04 + CS_04*max_lambda_2_00)) + omega_1*(-rc16*(CF_01 + CS_01*max_lambda_2_00) + (rc33)*(CF_02 +
      CS_02*max_lambda_2_00) + (rc32)*(CF_03 + CS_03*max_lambda_2_00)) + omega_2*((rc32)*(CF_00 + CS_00*max_lambda_2_00)
      - rc34*(CF_01 + CS_01*max_lambda_2_00) + (rc35)*(CF_02 + CS_02*max_lambda_2_00));

    beta_0 = (rc9)*(CF_03 - CS_03*max_lambda_2_00)*((rc20)*(CF_03 - CS_03*max_lambda_2_00) - rc21*(CF_04 -
      CS_04*max_lambda_2_00) + (rc22)*(CF_05 - CS_05*max_lambda_2_00)) + (rc9)*(CF_04 -
      CS_04*max_lambda_2_00)*((rc23)*(CF_04 - CS_04*max_lambda_2_00) - rc24*(CF_05 - CS_05*max_lambda_2_00)) +
      (rc25)*pow(CF_05 - CS_05*max_lambda_2_00, 2);

    beta_1 = (rc9)*(CF_02 - CS_02*max_lambda_2_00)*((rc26)*(CF_02 - CS_02*max_lambda_2_00) - rc27*(CF_03 -
      CS_03*max_lambda_2_00) + (rc28)*(CF_04 - CS_04*max_lambda_2_00)) + (rc9)*(CF_03 -
      CS_03*max_lambda_2_00)*((rc27)*(CF_03 - CS_03*max_lambda_2_00) - rc27*(CF_04 - CS_04*max_lambda_2_00)) +
      (rc25)*pow(CF_04 - CS_04*max_lambda_2_00, 2);

    beta_2 = (rc9)*(CF_01 - CS_01*max_lambda_2_00)*((rc26)*(CF_01 - CS_01*max_lambda_2_00) - rc24*(CF_02 -
      CS_02*max_lambda_2_00) + (rc22)*(CF_03 - CS_03*max_lambda_2_00)) + (rc9)*(CF_02 -
      CS_02*max_lambda_2_00)*((rc23)*(CF_02 - CS_02*max_lambda_2_00) - rc21*(CF_03 - CS_03*max_lambda_2_00)) +
      (rc28)*pow(CF_03 - CS_03*max_lambda_2_00, 2);

   alpha_0 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_0 = Recon_0 + omega_0*((rc35)*(CF_03 - CS_03*max_lambda_2_00) - rc34*(CF_04 - CS_04*max_lambda_2_00) +
      (rc32)*(CF_05 - CS_05*max_lambda_2_00)) + omega_1*((rc32)*(CF_02 - CS_02*max_lambda_2_00) + (rc33)*(CF_03 -
      CS_03*max_lambda_2_00) - rc16*(CF_04 - CS_04*max_lambda_2_00)) + omega_2*(-rc16*(CF_01 - CS_01*max_lambda_2_00) +
      (rc33)*(CF_02 - CS_02*max_lambda_2_00) + (rc32)*(CF_03 - CS_03*max_lambda_2_00));

    beta_0 = (rc9)*(CF_12 + CS_12*max_lambda_2_11)*((rc20)*(CF_12 + CS_12*max_lambda_2_11) - rc21*(CF_13 +
      CS_13*max_lambda_2_11) + (rc22)*(CF_14 + CS_14*max_lambda_2_11)) + (rc9)*(CF_13 +
      CS_13*max_lambda_2_11)*((rc23)*(CF_13 + CS_13*max_lambda_2_11) - rc24*(CF_14 + CS_14*max_lambda_2_11)) +
      (rc25)*pow(CF_14 + CS_14*max_lambda_2_11, 2);

    beta_1 = (rc9)*(CF_11 + CS_11*max_lambda_2_11)*((rc26)*(CF_11 + CS_11*max_lambda_2_11) - rc27*(CF_12 +
      CS_12*max_lambda_2_11) + (rc28)*(CF_13 + CS_13*max_lambda_2_11)) + (rc9)*(CF_12 +
      CS_12*max_lambda_2_11)*((rc27)*(CF_12 + CS_12*max_lambda_2_11) - rc27*(CF_13 + CS_13*max_lambda_2_11)) +
      (rc25)*pow(CF_13 + CS_13*max_lambda_2_11, 2);

    beta_2 = (rc9)*(CF_10 + CS_10*max_lambda_2_11)*((rc26)*(CF_10 + CS_10*max_lambda_2_11) + (rc22)*(CF_12 +
      CS_12*max_lambda_2_11)) + (rc9)*(CF_11 + CS_11*max_lambda_2_11)*(-rc24*(CF_10 + CS_10*max_lambda_2_11) +
      (rc23)*(CF_11 + CS_11*max_lambda_2_11) - rc21*(CF_12 + CS_12*max_lambda_2_11)) + (rc28)*pow(CF_12 +
      CS_12*max_lambda_2_11, 2);

   alpha_0 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_1 = Recon_1 + omega_0*((rc32)*(CF_12 + CS_12*max_lambda_2_11) + (rc33)*(CF_13 + CS_13*max_lambda_2_11) -
      rc16*(CF_14 + CS_14*max_lambda_2_11)) + omega_1*(-rc16*(CF_11 + CS_11*max_lambda_2_11) + (rc33)*(CF_12 +
      CS_12*max_lambda_2_11) + (rc32)*(CF_13 + CS_13*max_lambda_2_11)) + omega_2*((rc32)*(CF_10 + CS_10*max_lambda_2_11)
      - rc34*(CF_11 + CS_11*max_lambda_2_11) + (rc35)*(CF_12 + CS_12*max_lambda_2_11));

    beta_0 = (rc9)*(CF_13 - CS_13*max_lambda_2_11)*((rc20)*(CF_13 - CS_13*max_lambda_2_11) - rc21*(CF_14 -
      CS_14*max_lambda_2_11) + (rc22)*(CF_15 - CS_15*max_lambda_2_11)) + (rc9)*(CF_14 -
      CS_14*max_lambda_2_11)*((rc23)*(CF_14 - CS_14*max_lambda_2_11) - rc24*(CF_15 - CS_15*max_lambda_2_11)) +
      (rc25)*pow(CF_15 - CS_15*max_lambda_2_11, 2);

    beta_1 = (rc9)*(CF_12 - CS_12*max_lambda_2_11)*((rc26)*(CF_12 - CS_12*max_lambda_2_11) - rc27*(CF_13 -
      CS_13*max_lambda_2_11) + (rc28)*(CF_14 - CS_14*max_lambda_2_11)) + (rc9)*(CF_13 -
      CS_13*max_lambda_2_11)*((rc27)*(CF_13 - CS_13*max_lambda_2_11) - rc27*(CF_14 - CS_14*max_lambda_2_11)) +
      (rc25)*pow(CF_14 - CS_14*max_lambda_2_11, 2);

    beta_2 = (rc9)*(CF_11 - CS_11*max_lambda_2_11)*((rc26)*(CF_11 - CS_11*max_lambda_2_11) - rc24*(CF_12 -
      CS_12*max_lambda_2_11) + (rc22)*(CF_13 - CS_13*max_lambda_2_11)) + (rc9)*(CF_12 -
      CS_12*max_lambda_2_11)*((rc23)*(CF_12 - CS_12*max_lambda_2_11) - rc21*(CF_13 - CS_13*max_lambda_2_11)) +
      (rc28)*pow(CF_13 - CS_13*max_lambda_2_11, 2);

   alpha_0 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_1 = Recon_1 + omega_0*((rc35)*(CF_13 - CS_13*max_lambda_2_11) - rc34*(CF_14 - CS_14*max_lambda_2_11) +
      (rc32)*(CF_15 - CS_15*max_lambda_2_11)) + omega_1*((rc32)*(CF_12 - CS_12*max_lambda_2_11) + (rc33)*(CF_13 -
      CS_13*max_lambda_2_11) - rc16*(CF_14 - CS_14*max_lambda_2_11)) + omega_2*(-rc16*(CF_11 - CS_11*max_lambda_2_11) +
      (rc33)*(CF_12 - CS_12*max_lambda_2_11) + (rc32)*(CF_13 - CS_13*max_lambda_2_11));

    beta_0 = (rc9)*(CF_22 + CS_22*max_lambda_2_22)*((rc20)*(CF_22 + CS_22*max_lambda_2_22) - rc21*(CF_23 +
      CS_23*max_lambda_2_22) + (rc22)*(CF_24 + CS_24*max_lambda_2_22)) + (rc9)*(CF_23 +
      CS_23*max_lambda_2_22)*((rc23)*(CF_23 + CS_23*max_lambda_2_22) - rc24*(CF_24 + CS_24*max_lambda_2_22)) +
      (rc25)*pow(CF_24 + CS_24*max_lambda_2_22, 2);

    beta_1 = (rc9)*(CF_21 + CS_21*max_lambda_2_22)*((rc26)*(CF_21 + CS_21*max_lambda_2_22) - rc27*(CF_22 +
      CS_22*max_lambda_2_22) + (rc28)*(CF_23 + CS_23*max_lambda_2_22)) + (rc9)*(CF_22 +
      CS_22*max_lambda_2_22)*((rc27)*(CF_22 + CS_22*max_lambda_2_22) - rc27*(CF_23 + CS_23*max_lambda_2_22)) +
      (rc25)*pow(CF_23 + CS_23*max_lambda_2_22, 2);

    beta_2 = (rc9)*(CF_20 + CS_20*max_lambda_2_22)*((rc26)*(CF_20 + CS_20*max_lambda_2_22) + (rc22)*(CF_22 +
      CS_22*max_lambda_2_22)) + (rc9)*(CF_21 + CS_21*max_lambda_2_22)*(-rc24*(CF_20 + CS_20*max_lambda_2_22) +
      (rc23)*(CF_21 + CS_21*max_lambda_2_22) - rc21*(CF_22 + CS_22*max_lambda_2_22)) + (rc28)*pow(CF_22 +
      CS_22*max_lambda_2_22, 2);

   alpha_0 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_2 = Recon_2 + omega_0*((rc32)*(CF_22 + CS_22*max_lambda_2_22) + (rc33)*(CF_23 + CS_23*max_lambda_2_22) -
      rc16*(CF_24 + CS_24*max_lambda_2_22)) + omega_1*(-rc16*(CF_21 + CS_21*max_lambda_2_22) + (rc33)*(CF_22 +
      CS_22*max_lambda_2_22) + (rc32)*(CF_23 + CS_23*max_lambda_2_22)) + omega_2*((rc32)*(CF_20 + CS_20*max_lambda_2_22)
      - rc34*(CF_21 + CS_21*max_lambda_2_22) + (rc35)*(CF_22 + CS_22*max_lambda_2_22));

    beta_0 = (rc9)*(CF_23 - CS_23*max_lambda_2_22)*((rc20)*(CF_23 - CS_23*max_lambda_2_22) - rc21*(CF_24 -
      CS_24*max_lambda_2_22) + (rc22)*(CF_25 - CS_25*max_lambda_2_22)) + (rc9)*(CF_24 -
      CS_24*max_lambda_2_22)*((rc23)*(CF_24 - CS_24*max_lambda_2_22) - rc24*(CF_25 - CS_25*max_lambda_2_22)) +
      (rc25)*pow(CF_25 - CS_25*max_lambda_2_22, 2);

    beta_1 = (rc9)*(CF_22 - CS_22*max_lambda_2_22)*((rc26)*(CF_22 - CS_22*max_lambda_2_22) - rc27*(CF_23 -
      CS_23*max_lambda_2_22) + (rc28)*(CF_24 - CS_24*max_lambda_2_22)) + (rc9)*(CF_23 -
      CS_23*max_lambda_2_22)*((rc27)*(CF_23 - CS_23*max_lambda_2_22) - rc27*(CF_24 - CS_24*max_lambda_2_22)) +
      (rc25)*pow(CF_24 - CS_24*max_lambda_2_22, 2);

    beta_2 = (rc9)*(CF_21 - CS_21*max_lambda_2_22)*((rc26)*(CF_21 - CS_21*max_lambda_2_22) - rc24*(CF_22 -
      CS_22*max_lambda_2_22) + (rc22)*(CF_23 - CS_23*max_lambda_2_22)) + (rc9)*(CF_22 -
      CS_22*max_lambda_2_22)*((rc23)*(CF_22 - CS_22*max_lambda_2_22) - rc21*(CF_23 - CS_23*max_lambda_2_22)) +
      (rc28)*pow(CF_23 - CS_23*max_lambda_2_22, 2);

   alpha_0 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_2 = Recon_2 + omega_0*((rc35)*(CF_23 - CS_23*max_lambda_2_22) - rc34*(CF_24 - CS_24*max_lambda_2_22) +
      (rc32)*(CF_25 - CS_25*max_lambda_2_22)) + omega_1*((rc32)*(CF_22 - CS_22*max_lambda_2_22) + (rc33)*(CF_23 -
      CS_23*max_lambda_2_22) - rc16*(CF_24 - CS_24*max_lambda_2_22)) + omega_2*(-rc16*(CF_21 - CS_21*max_lambda_2_22) +
      (rc33)*(CF_22 - CS_22*max_lambda_2_22) + (rc32)*(CF_23 - CS_23*max_lambda_2_22));

    beta_0 = (rc9)*(CF_32 + CS_32*max_lambda_2_33)*((rc20)*(CF_32 + CS_32*max_lambda_2_33) - rc21*(CF_33 +
      CS_33*max_lambda_2_33) + (rc22)*(CF_34 + CS_34*max_lambda_2_33)) + (rc9)*(CF_33 +
      CS_33*max_lambda_2_33)*((rc23)*(CF_33 + CS_33*max_lambda_2_33) - rc24*(CF_34 + CS_34*max_lambda_2_33)) +
      (rc25)*pow(CF_34 + CS_34*max_lambda_2_33, 2);

    beta_1 = (rc9)*(CF_31 + CS_31*max_lambda_2_33)*((rc26)*(CF_31 + CS_31*max_lambda_2_33) - rc27*(CF_32 +
      CS_32*max_lambda_2_33) + (rc28)*(CF_33 + CS_33*max_lambda_2_33)) + (rc9)*(CF_32 +
      CS_32*max_lambda_2_33)*((rc27)*(CF_32 + CS_32*max_lambda_2_33) - rc27*(CF_33 + CS_33*max_lambda_2_33)) +
      (rc25)*pow(CF_33 + CS_33*max_lambda_2_33, 2);

    beta_2 = (rc9)*(CF_30 + CS_30*max_lambda_2_33)*((rc26)*(CF_30 + CS_30*max_lambda_2_33) + (rc22)*(CF_32 +
      CS_32*max_lambda_2_33)) + (rc9)*(CF_31 + CS_31*max_lambda_2_33)*(-rc24*(CF_30 + CS_30*max_lambda_2_33) +
      (rc23)*(CF_31 + CS_31*max_lambda_2_33) - rc21*(CF_32 + CS_32*max_lambda_2_33)) + (rc28)*pow(CF_32 +
      CS_32*max_lambda_2_33, 2);

   alpha_0 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_3 = Recon_3 + omega_0*((rc32)*(CF_32 + CS_32*max_lambda_2_33) + (rc33)*(CF_33 + CS_33*max_lambda_2_33) -
      rc16*(CF_34 + CS_34*max_lambda_2_33)) + omega_1*(-rc16*(CF_31 + CS_31*max_lambda_2_33) + (rc33)*(CF_32 +
      CS_32*max_lambda_2_33) + (rc32)*(CF_33 + CS_33*max_lambda_2_33)) + omega_2*((rc32)*(CF_30 + CS_30*max_lambda_2_33)
      - rc34*(CF_31 + CS_31*max_lambda_2_33) + (rc35)*(CF_32 + CS_32*max_lambda_2_33));

    beta_0 = (rc9)*(CF_33 - CS_33*max_lambda_2_33)*((rc20)*(CF_33 - CS_33*max_lambda_2_33) - rc21*(CF_34 -
      CS_34*max_lambda_2_33) + (rc22)*(CF_35 - CS_35*max_lambda_2_33)) + (rc9)*(CF_34 -
      CS_34*max_lambda_2_33)*((rc23)*(CF_34 - CS_34*max_lambda_2_33) - rc24*(CF_35 - CS_35*max_lambda_2_33)) +
      (rc25)*pow(CF_35 - CS_35*max_lambda_2_33, 2);

    beta_1 = (rc9)*(CF_32 - CS_32*max_lambda_2_33)*((rc26)*(CF_32 - CS_32*max_lambda_2_33) - rc27*(CF_33 -
      CS_33*max_lambda_2_33) + (rc28)*(CF_34 - CS_34*max_lambda_2_33)) + (rc9)*(CF_33 -
      CS_33*max_lambda_2_33)*((rc27)*(CF_33 - CS_33*max_lambda_2_33) - rc27*(CF_34 - CS_34*max_lambda_2_33)) +
      (rc25)*pow(CF_34 - CS_34*max_lambda_2_33, 2);

    beta_2 = (rc9)*(CF_31 - CS_31*max_lambda_2_33)*((rc26)*(CF_31 - CS_31*max_lambda_2_33) - rc24*(CF_32 -
      CS_32*max_lambda_2_33) + (rc22)*(CF_33 - CS_33*max_lambda_2_33)) + (rc9)*(CF_32 -
      CS_32*max_lambda_2_33)*((rc23)*(CF_32 - CS_32*max_lambda_2_33) - rc21*(CF_33 - CS_33*max_lambda_2_33)) +
      (rc28)*pow(CF_33 - CS_33*max_lambda_2_33, 2);

   alpha_0 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_3 = Recon_3 + omega_0*((rc35)*(CF_33 - CS_33*max_lambda_2_33) - rc34*(CF_34 - CS_34*max_lambda_2_33) +
      (rc32)*(CF_35 - CS_35*max_lambda_2_33)) + omega_1*((rc32)*(CF_32 - CS_32*max_lambda_2_33) + (rc33)*(CF_33 -
      CS_33*max_lambda_2_33) - rc16*(CF_34 - CS_34*max_lambda_2_33)) + omega_2*(-rc16*(CF_31 - CS_31*max_lambda_2_33) +
      (rc33)*(CF_32 - CS_32*max_lambda_2_33) + (rc32)*(CF_33 - CS_33*max_lambda_2_33));

    beta_0 = (rc9)*(CF_42 + CS_42*max_lambda_2_44)*((rc20)*(CF_42 + CS_42*max_lambda_2_44) - rc21*(CF_43 +
      CS_43*max_lambda_2_44) + (rc22)*(CF_44 + CS_44*max_lambda_2_44)) + (rc9)*(CF_43 +
      CS_43*max_lambda_2_44)*((rc23)*(CF_43 + CS_43*max_lambda_2_44) - rc24*(CF_44 + CS_44*max_lambda_2_44)) +
      (rc25)*pow(CF_44 + CS_44*max_lambda_2_44, 2);

    beta_1 = (rc9)*(CF_41 + CS_41*max_lambda_2_44)*((rc26)*(CF_41 + CS_41*max_lambda_2_44) - rc27*(CF_42 +
      CS_42*max_lambda_2_44) + (rc28)*(CF_43 + CS_43*max_lambda_2_44)) + (rc9)*(CF_42 +
      CS_42*max_lambda_2_44)*((rc27)*(CF_42 + CS_42*max_lambda_2_44) - rc27*(CF_43 + CS_43*max_lambda_2_44)) +
      (rc25)*pow(CF_43 + CS_43*max_lambda_2_44, 2);

    beta_2 = (rc9)*(CF_40 + CS_40*max_lambda_2_44)*((rc26)*(CF_40 + CS_40*max_lambda_2_44) + (rc22)*(CF_42 +
      CS_42*max_lambda_2_44)) + (rc9)*(CF_41 + CS_41*max_lambda_2_44)*(-rc24*(CF_40 + CS_40*max_lambda_2_44) +
      (rc23)*(CF_41 + CS_41*max_lambda_2_44) - rc21*(CF_42 + CS_42*max_lambda_2_44)) + (rc28)*pow(CF_42 +
      CS_42*max_lambda_2_44, 2);

   alpha_0 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_4 = Recon_4 + omega_0*((rc32)*(CF_42 + CS_42*max_lambda_2_44) + (rc33)*(CF_43 + CS_43*max_lambda_2_44) -
      rc16*(CF_44 + CS_44*max_lambda_2_44)) + omega_1*(-rc16*(CF_41 + CS_41*max_lambda_2_44) + (rc33)*(CF_42 +
      CS_42*max_lambda_2_44) + (rc32)*(CF_43 + CS_43*max_lambda_2_44)) + omega_2*((rc32)*(CF_40 + CS_40*max_lambda_2_44)
      - rc34*(CF_41 + CS_41*max_lambda_2_44) + (rc35)*(CF_42 + CS_42*max_lambda_2_44));

    beta_0 = (rc9)*(CF_43 - CS_43*max_lambda_2_44)*((rc20)*(CF_43 - CS_43*max_lambda_2_44) - rc21*(CF_44 -
      CS_44*max_lambda_2_44) + (rc22)*(CF_45 - CS_45*max_lambda_2_44)) + (rc9)*(CF_44 -
      CS_44*max_lambda_2_44)*((rc23)*(CF_44 - CS_44*max_lambda_2_44) - rc24*(CF_45 - CS_45*max_lambda_2_44)) +
      (rc25)*pow(CF_45 - CS_45*max_lambda_2_44, 2);

    beta_1 = (rc9)*(CF_42 - CS_42*max_lambda_2_44)*((rc26)*(CF_42 - CS_42*max_lambda_2_44) - rc27*(CF_43 -
      CS_43*max_lambda_2_44) + (rc28)*(CF_44 - CS_44*max_lambda_2_44)) + (rc9)*(CF_43 -
      CS_43*max_lambda_2_44)*((rc27)*(CF_43 - CS_43*max_lambda_2_44) - rc27*(CF_44 - CS_44*max_lambda_2_44)) +
      (rc25)*pow(CF_44 - CS_44*max_lambda_2_44, 2);

    beta_2 = (rc9)*(CF_41 - CS_41*max_lambda_2_44)*((rc26)*(CF_41 - CS_41*max_lambda_2_44) - rc24*(CF_42 -
      CS_42*max_lambda_2_44) + (rc22)*(CF_43 - CS_43*max_lambda_2_44)) + (rc9)*(CF_42 -
      CS_42*max_lambda_2_44)*((rc23)*(CF_42 - CS_42*max_lambda_2_44) - rc21*(CF_43 - CS_43*max_lambda_2_44)) +
      (rc28)*pow(CF_43 - CS_43*max_lambda_2_44, 2);

   alpha_0 = 0.1 + (rc31)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_0 + 1.0e-14, 2);

   alpha_1 = 0.6 + (rc30)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_1 + 1.0e-14, 2);

   alpha_2 = 0.3 + (rc29)*pow(fabs(beta_0 - beta_2), 2)/pow(beta_2 + 1.0e-14, 2);

   inv_alpha_sum = 1.0/(alpha_0 + alpha_1 + alpha_2);

   omega_0 = alpha_0*inv_alpha_sum;

   omega_1 = alpha_1*inv_alpha_sum;

   omega_2 = alpha_2*inv_alpha_sum;

    Recon_4 = Recon_4 + omega_0*((rc35)*(CF_43 - CS_43*max_lambda_2_44) - rc34*(CF_44 - CS_44*max_lambda_2_44) +
      (rc32)*(CF_45 - CS_45*max_lambda_2_44)) + omega_1*((rc32)*(CF_42 - CS_42*max_lambda_2_44) + (rc33)*(CF_43 -
      CS_43*max_lambda_2_44) - rc16*(CF_44 - CS_44*max_lambda_2_44)) + omega_2*(-rc16*(CF_41 - CS_41*max_lambda_2_44) +
      (rc33)*(CF_42 - CS_42*max_lambda_2_44) + (rc32)*(CF_43 - CS_43*max_lambda_2_44));

    OPS_ACC(wk10_B0, 0,0,0) = 0.707106781186547*AVG_2_rho*Recon_3*inv_AVG_a +
      0.707106781186547*AVG_2_rho*Recon_4*inv_AVG_a + Recon_2;

    OPS_ACC(wk11_B0, 0,0,0) = 0.707106781186547*AVG_2_rho*AVG_2_u0*Recon_3*inv_AVG_a +
      0.707106781186547*AVG_2_rho*AVG_2_u0*Recon_4*inv_AVG_a - AVG_2_rho*Recon_1 + AVG_2_u0*Recon_2;

    OPS_ACC(wk12_B0, 0,0,0) = 0.707106781186547*AVG_2_rho*AVG_2_u1*Recon_3*inv_AVG_a +
      0.707106781186547*AVG_2_rho*AVG_2_u1*Recon_4*inv_AVG_a + AVG_2_rho*Recon_0 + AVG_2_u1*Recon_2;

    OPS_ACC(wk13_B0, 0,0,0) = 0.707106781186547*AVG_2_rho*Recon_3*inv_AVG_a*(AVG_2_a + AVG_2_u2) +
      0.707106781186547*AVG_2_rho*Recon_4*inv_AVG_a*(-AVG_2_a + AVG_2_u2) + AVG_2_u2*Recon_2;

    OPS_ACC(wk14_B0, 0,0,0) = -AVG_2_rho*AVG_2_u0*Recon_1 + AVG_2_rho*AVG_2_u1*Recon_0 +
      0.707106781186547*AVG_2_rho*Recon_3*inv_AVG_a*(rcinv36*((rc9)*gamma_m1*(pow(AVG_2_u0, 2) + pow(AVG_2_u1, 2) +
      pow(AVG_2_u2, 2)) + pow(AVG_2_a, 2)) + AVG_2_a*AVG_2_u2) +
      0.707106781186547*AVG_2_rho*Recon_4*inv_AVG_a*(rcinv36*((rc9)*gamma_m1*(pow(AVG_2_u0, 2) + pow(AVG_2_u1, 2) +
      pow(AVG_2_u2, 2)) + pow(AVG_2_a, 2)) - AVG_2_a*AVG_2_u2) + Recon_2*((rc9)*pow(AVG_2_u0, 2) + (rc9)*pow(AVG_2_u1,
      2) + (rc9)*pow(AVG_2_u2, 2));


      }
    }
  }
}
