//
// auto-generated by ops.py
//

//user function

// host stub function
#ifndef OPS_LAZY
void ops_par_loop_opensbliblock00Kernel061(char const *name, ops_block block, int dim, int* range,
 ops_arg arg0, ops_arg arg1, ops_arg arg2, ops_arg arg3,
 ops_arg arg4, ops_arg arg5, ops_arg arg6, ops_arg arg7,
 ops_arg arg8, ops_arg arg9, ops_arg arg10, ops_arg arg11,
 ops_arg arg12) {
#else
void ops_par_loop_opensbliblock00Kernel061_execute(ops_kernel_descriptor *desc) {
  ops_block block = desc->block;
  int dim = desc->dim;
  int *range = desc->range;
  ops_arg arg0 = desc->args[0];
  ops_arg arg1 = desc->args[1];
  ops_arg arg2 = desc->args[2];
  ops_arg arg3 = desc->args[3];
  ops_arg arg4 = desc->args[4];
  ops_arg arg5 = desc->args[5];
  ops_arg arg6 = desc->args[6];
  ops_arg arg7 = desc->args[7];
  ops_arg arg8 = desc->args[8];
  ops_arg arg9 = desc->args[9];
  ops_arg arg10 = desc->args[10];
  ops_arg arg11 = desc->args[11];
  ops_arg arg12 = desc->args[12];
  #endif

  //Timing
  double __t1,__t2,__c1,__c2;

  ops_arg args[13] = { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12};



  #if defined(CHECKPOINTING) && !defined(OPS_LAZY)
  if (!ops_checkpointing_before(args,13,range,6)) return;
  #endif

  if (block->instance->OPS_diags > 1) {
    ops_timing_realloc(block->instance,6,"opensbliblock00Kernel061");
    block->instance->OPS_kernels[6].count++;
    ops_timers_core(&__c2,&__t2);
  }

  #ifdef OPS_DEBUG
  ops_register_args(block->instance, args, "opensbliblock00Kernel061");
  #endif


  //compute locally allocated range for the sub-block
  int start[2];
  int end[2];
  int arg_idx[2];
  #if defined(OPS_LAZY) || !defined(OPS_MPI)
  for ( int n=0; n<2; n++ ){
    start[n] = range[2*n];end[n] = range[2*n+1];
  }
  #else
  if (compute_ranges(args, 13,block, range, start, end, arg_idx) < 0) return;
  #endif

  int start0 = start[0];
  int end0 = end[0];
  int start1 = start[1];
  int end1 = end[1];

  #if defined(OPS_MPI)
  #if defined(OPS_LAZY)
  sub_block_list sb = OPS_sub_block_list[block->index];
  arg_idx[0] = sb->decomp_disp[0];
  arg_idx[1] = sb->decomp_disp[1];
  #else
  arg_idx[0] -= start[0];
  arg_idx[1] -= start[1];
  #endif
  #else //OPS_MPI
  arg_idx[0] = 0;
  arg_idx[1] = 0;
  #endif //OPS_MPI

  //initialize global variable with the dimension of dats
  int xdim0_opensbliblock00Kernel061 = args[0].dat->size[0];
  int xdim1_opensbliblock00Kernel061 = args[1].dat->size[0];
  int xdim2_opensbliblock00Kernel061 = args[2].dat->size[0];
  int xdim3_opensbliblock00Kernel061 = args[3].dat->size[0];
  int xdim4_opensbliblock00Kernel061 = args[4].dat->size[0];
  int xdim5_opensbliblock00Kernel061 = args[5].dat->size[0];
  int xdim6_opensbliblock00Kernel061 = args[6].dat->size[0];
  int xdim7_opensbliblock00Kernel061 = args[7].dat->size[0];
  int xdim8_opensbliblock00Kernel061 = args[8].dat->size[0];
  int xdim9_opensbliblock00Kernel061 = args[9].dat->size[0];
  int xdim10_opensbliblock00Kernel061 = args[10].dat->size[0];
  int xdim11_opensbliblock00Kernel061 = args[11].dat->size[0];

  //set up initial pointers and exchange halos if necessary
  int base0 = args[0].dat->base_offset;
  double * __restrict__ D00_B0_p = (double *)(args[0].data_d + base0);

  int base1 = args[1].dat->base_offset;
  double * __restrict__ D01_B0_p = (double *)(args[1].data_d + base1);

  int base2 = args[2].dat->base_offset;
  double * __restrict__ D10_B0_p = (double *)(args[2].data_d + base2);

  int base3 = args[3].dat->base_offset;
  double * __restrict__ D11_B0_p = (double *)(args[3].data_d + base3);

  int base4 = args[4].dat->base_offset;
  double * __restrict__ SD000_B0_p = (double *)(args[4].data_d + base4);

  int base5 = args[5].dat->base_offset;
  double * __restrict__ SD001_B0_p = (double *)(args[5].data_d + base5);

  int base6 = args[6].dat->base_offset;
  double * __restrict__ SD010_B0_p = (double *)(args[6].data_d + base6);

  int base7 = args[7].dat->base_offset;
  double * __restrict__ SD011_B0_p = (double *)(args[7].data_d + base7);

  int base8 = args[8].dat->base_offset;
  double * __restrict__ SD100_B0_p = (double *)(args[8].data_d + base8);

  int base9 = args[9].dat->base_offset;
  double * __restrict__ SD101_B0_p = (double *)(args[9].data_d + base9);

  int base10 = args[10].dat->base_offset;
  double * __restrict__ SD110_B0_p = (double *)(args[10].data_d + base10);

  int base11 = args[11].dat->base_offset;
  double * __restrict__ SD111_B0_p = (double *)(args[11].data_d + base11);




  #ifndef OPS_LAZY
  //Halo Exchanges
  ops_H_D_exchanges_device(args, 13);
  ops_halo_exchanges(args,13,range);
  ops_H_D_exchanges_device(args, 13);
  #endif

  if (block->instance->OPS_diags > 1) {
    ops_timers_core(&__c1,&__t1);
    block->instance->OPS_kernels[6].mpi_time += __t1-__t2;
  }

  #pragma omp target teams distribute parallel for collapse(2)
  for ( int n_y=start1; n_y<end1; n_y++ ){
    for ( int n_x=start0; n_x<end0; n_x++ ){
      int idx[] = {arg_idx[0]+n_x, arg_idx[1]+n_y};
      const ACC<double> D00_B0(xdim0_opensbliblock00Kernel061, D00_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel061*1);
      const ACC<double> D01_B0(xdim1_opensbliblock00Kernel061, D01_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel061*1);
      const ACC<double> D10_B0(xdim2_opensbliblock00Kernel061, D10_B0_p + n_x*1 + n_y * xdim2_opensbliblock00Kernel061*1);
      const ACC<double> D11_B0(xdim3_opensbliblock00Kernel061, D11_B0_p + n_x*1 + n_y * xdim3_opensbliblock00Kernel061*1);
      ACC<double> SD000_B0(xdim4_opensbliblock00Kernel061, SD000_B0_p + n_x*1 + n_y * xdim4_opensbliblock00Kernel061*1);
      ACC<double> SD001_B0(xdim5_opensbliblock00Kernel061, SD001_B0_p + n_x*1 + n_y * xdim5_opensbliblock00Kernel061*1);
      ACC<double> SD010_B0(xdim6_opensbliblock00Kernel061, SD010_B0_p + n_x*1 + n_y * xdim6_opensbliblock00Kernel061*1);
      ACC<double> SD011_B0(xdim7_opensbliblock00Kernel061, SD011_B0_p + n_x*1 + n_y * xdim7_opensbliblock00Kernel061*1);
      ACC<double> SD100_B0(xdim8_opensbliblock00Kernel061, SD100_B0_p + n_x*1 + n_y * xdim8_opensbliblock00Kernel061*1);
      ACC<double> SD101_B0(xdim9_opensbliblock00Kernel061, SD101_B0_p + n_x*1 + n_y * xdim9_opensbliblock00Kernel061*1);
      ACC<double> SD110_B0(xdim10_opensbliblock00Kernel061, SD110_B0_p + n_x*1 + n_y * xdim10_opensbliblock00Kernel061*1);
      ACC<double> SD111_B0(xdim11_opensbliblock00Kernel061, SD111_B0_p + n_x*1 + n_y * xdim11_opensbliblock00Kernel061*1);
      
   double d1_D00_dx = 0.0;
   double d1_D00_dy = 0.0;
   double d1_D01_dx = 0.0;
   double d1_D01_dy = 0.0;
   double d1_D10_dx = 0.0;
   double d1_D10_dy = 0.0;
   double d1_D11_dx = 0.0;
   double d1_D11_dy = 0.0;
    d1_D00_dy = invDelta1block0*((idx[1] == 0) ? (
   3.0*D00_B0(0,1) + 0.333333333333333*D00_B0(0,3) - 1.5*D00_B0(0,2)
      - 1.83333333333333*D00_B0(0,0)
)
: ((idx[1] == 1) ? (
   0.0394168524399447*D00_B0(0,2) +
      0.00571369039775442*D00_B0(0,4) + 0.719443173328855*D00_B0(0,1) - 0.322484932882161*D00_B0(0,0) -
      0.0658051057710389*D00_B0(0,3) - 0.376283677513354*D00_B0(0,-1)
)
: ((idx[1] == 2) ? (

      0.197184333887745*D00_B0(0,0) + 0.521455851089587*D00_B0(0,1) + 0.113446470384241*D00_B0(0,-2) -
      0.00412637789557492*D00_B0(0,3) - 0.0367146847001261*D00_B0(0,2) - 0.791245592765872*D00_B0(0,-1)
)
: ((idx[1] ==
      3) ? (
   0.0451033223343881*D00_B0(0,0) + 0.652141084861241*D00_B0(0,1) + 0.121937153224065*D00_B0(0,-2) -
      0.00932597985049999*D00_B0(0,-3) - 0.727822147724592*D00_B0(0,-1) - 0.082033432844602*D00_B0(0,2)
)
: (

      -(2.0/3.0)*D00_B0(0,-1) - (1.0/12.0)*D00_B0(0,2) + ((1.0/12.0))*D00_B0(0,-2) + ((2.0/3.0))*D00_B0(0,1)
)))));

    d1_D10_dx = invDelta0block0*((idx[0] == 0) ? (
   3.0*D10_B0(1,0) + 0.333333333333333*D10_B0(3,0) - 1.5*D10_B0(2,0)
      - 1.83333333333333*D10_B0(0,0)
)
: ((idx[0] == 1) ? (
   0.0394168524399447*D10_B0(2,0) +
      0.00571369039775442*D10_B0(4,0) + 0.719443173328855*D10_B0(1,0) - 0.322484932882161*D10_B0(0,0) -
      0.0658051057710389*D10_B0(3,0) - 0.376283677513354*D10_B0(-1,0)
)
: ((idx[0] == 2) ? (

      0.197184333887745*D10_B0(0,0) + 0.521455851089587*D10_B0(1,0) + 0.113446470384241*D10_B0(-2,0) -
      0.00412637789557492*D10_B0(3,0) - 0.0367146847001261*D10_B0(2,0) - 0.791245592765872*D10_B0(-1,0)
)
: ((idx[0] ==
      3) ? (
   0.0451033223343881*D10_B0(0,0) + 0.652141084861241*D10_B0(1,0) + 0.121937153224065*D10_B0(-2,0) -
      0.00932597985049999*D10_B0(-3,0) - 0.727822147724592*D10_B0(-1,0) - 0.082033432844602*D10_B0(2,0)
)
: ((idx[0] ==
      -1 + block0np0) ? (
   1.5*D10_B0(-2,0) + 1.83333333333333*D10_B0(0,0) - 3.0*D10_B0(-1,0) -
      0.333333333333333*D10_B0(-3,0)
)
: ((idx[0] == -2 + block0np0) ? (
   0.322484932882161*D10_B0(0,0) +
      0.0658051057710389*D10_B0(-3,0) + 0.376283677513354*D10_B0(1,0) - 0.0394168524399447*D10_B0(-2,0) -
      0.00571369039775442*D10_B0(-4,0) - 0.719443173328855*D10_B0(-1,0)
)
: ((idx[0] == -3 + block0np0) ? (

      0.00412637789557492*D10_B0(-3,0) + 0.0367146847001261*D10_B0(-2,0) + 0.791245592765872*D10_B0(1,0) -
      0.197184333887745*D10_B0(0,0) - 0.521455851089587*D10_B0(-1,0) - 0.113446470384241*D10_B0(2,0)
)
: ((idx[0] == -4
      + block0np0) ? (
   0.00932597985049999*D10_B0(3,0) + 0.727822147724592*D10_B0(1,0) +
      0.082033432844602*D10_B0(-2,0) - 0.0451033223343881*D10_B0(0,0) - 0.652141084861241*D10_B0(-1,0) -
      0.121937153224065*D10_B0(2,0)
)
: (
   -(2.0/3.0)*D10_B0(-1,0) - (1.0/12.0)*D10_B0(2,0) +
      ((1.0/12.0))*D10_B0(-2,0) + ((2.0/3.0))*D10_B0(1,0)
)))))))));

    d1_D11_dx = invDelta0block0*((idx[0] == 0) ? (
   3.0*D11_B0(1,0) + 0.333333333333333*D11_B0(3,0) - 1.5*D11_B0(2,0)
      - 1.83333333333333*D11_B0(0,0)
)
: ((idx[0] == 1) ? (
   0.0394168524399447*D11_B0(2,0) +
      0.00571369039775442*D11_B0(4,0) + 0.719443173328855*D11_B0(1,0) - 0.322484932882161*D11_B0(0,0) -
      0.0658051057710389*D11_B0(3,0) - 0.376283677513354*D11_B0(-1,0)
)
: ((idx[0] == 2) ? (

      0.197184333887745*D11_B0(0,0) + 0.521455851089587*D11_B0(1,0) + 0.113446470384241*D11_B0(-2,0) -
      0.00412637789557492*D11_B0(3,0) - 0.0367146847001261*D11_B0(2,0) - 0.791245592765872*D11_B0(-1,0)
)
: ((idx[0] ==
      3) ? (
   0.0451033223343881*D11_B0(0,0) + 0.652141084861241*D11_B0(1,0) + 0.121937153224065*D11_B0(-2,0) -
      0.00932597985049999*D11_B0(-3,0) - 0.727822147724592*D11_B0(-1,0) - 0.082033432844602*D11_B0(2,0)
)
: ((idx[0] ==
      -1 + block0np0) ? (
   1.5*D11_B0(-2,0) + 1.83333333333333*D11_B0(0,0) - 3.0*D11_B0(-1,0) -
      0.333333333333333*D11_B0(-3,0)
)
: ((idx[0] == -2 + block0np0) ? (
   0.322484932882161*D11_B0(0,0) +
      0.0658051057710389*D11_B0(-3,0) + 0.376283677513354*D11_B0(1,0) - 0.0394168524399447*D11_B0(-2,0) -
      0.00571369039775442*D11_B0(-4,0) - 0.719443173328855*D11_B0(-1,0)
)
: ((idx[0] == -3 + block0np0) ? (

      0.00412637789557492*D11_B0(-3,0) + 0.0367146847001261*D11_B0(-2,0) + 0.791245592765872*D11_B0(1,0) -
      0.197184333887745*D11_B0(0,0) - 0.521455851089587*D11_B0(-1,0) - 0.113446470384241*D11_B0(2,0)
)
: ((idx[0] == -4
      + block0np0) ? (
   0.00932597985049999*D11_B0(3,0) + 0.727822147724592*D11_B0(1,0) +
      0.082033432844602*D11_B0(-2,0) - 0.0451033223343881*D11_B0(0,0) - 0.652141084861241*D11_B0(-1,0) -
      0.121937153224065*D11_B0(2,0)
)
: (
   -(2.0/3.0)*D11_B0(-1,0) - (1.0/12.0)*D11_B0(2,0) +
      ((1.0/12.0))*D11_B0(-2,0) + ((2.0/3.0))*D11_B0(1,0)
)))))))));

    d1_D00_dx = invDelta0block0*((idx[0] == 0) ? (
   3.0*D00_B0(1,0) + 0.333333333333333*D00_B0(3,0) - 1.5*D00_B0(2,0)
      - 1.83333333333333*D00_B0(0,0)
)
: ((idx[0] == 1) ? (
   0.0394168524399447*D00_B0(2,0) +
      0.00571369039775442*D00_B0(4,0) + 0.719443173328855*D00_B0(1,0) - 0.322484932882161*D00_B0(0,0) -
      0.0658051057710389*D00_B0(3,0) - 0.376283677513354*D00_B0(-1,0)
)
: ((idx[0] == 2) ? (

      0.197184333887745*D00_B0(0,0) + 0.521455851089587*D00_B0(1,0) + 0.113446470384241*D00_B0(-2,0) -
      0.00412637789557492*D00_B0(3,0) - 0.0367146847001261*D00_B0(2,0) - 0.791245592765872*D00_B0(-1,0)
)
: ((idx[0] ==
      3) ? (
   0.0451033223343881*D00_B0(0,0) + 0.652141084861241*D00_B0(1,0) + 0.121937153224065*D00_B0(-2,0) -
      0.00932597985049999*D00_B0(-3,0) - 0.727822147724592*D00_B0(-1,0) - 0.082033432844602*D00_B0(2,0)
)
: ((idx[0] ==
      -1 + block0np0) ? (
   1.5*D00_B0(-2,0) + 1.83333333333333*D00_B0(0,0) - 3.0*D00_B0(-1,0) -
      0.333333333333333*D00_B0(-3,0)
)
: ((idx[0] == -2 + block0np0) ? (
   0.322484932882161*D00_B0(0,0) +
      0.0658051057710389*D00_B0(-3,0) + 0.376283677513354*D00_B0(1,0) - 0.0394168524399447*D00_B0(-2,0) -
      0.00571369039775442*D00_B0(-4,0) - 0.719443173328855*D00_B0(-1,0)
)
: ((idx[0] == -3 + block0np0) ? (

      0.00412637789557492*D00_B0(-3,0) + 0.0367146847001261*D00_B0(-2,0) + 0.791245592765872*D00_B0(1,0) -
      0.197184333887745*D00_B0(0,0) - 0.521455851089587*D00_B0(-1,0) - 0.113446470384241*D00_B0(2,0)
)
: ((idx[0] == -4
      + block0np0) ? (
   0.00932597985049999*D00_B0(3,0) + 0.727822147724592*D00_B0(1,0) +
      0.082033432844602*D00_B0(-2,0) - 0.0451033223343881*D00_B0(0,0) - 0.652141084861241*D00_B0(-1,0) -
      0.121937153224065*D00_B0(2,0)
)
: (
   -(2.0/3.0)*D00_B0(-1,0) - (1.0/12.0)*D00_B0(2,0) +
      ((1.0/12.0))*D00_B0(-2,0) + ((2.0/3.0))*D00_B0(1,0)
)))))))));

    d1_D10_dy = invDelta1block0*((idx[1] == 0) ? (
   3.0*D10_B0(0,1) + 0.333333333333333*D10_B0(0,3) - 1.5*D10_B0(0,2)
      - 1.83333333333333*D10_B0(0,0)
)
: ((idx[1] == 1) ? (
   0.0394168524399447*D10_B0(0,2) +
      0.00571369039775442*D10_B0(0,4) + 0.719443173328855*D10_B0(0,1) - 0.322484932882161*D10_B0(0,0) -
      0.0658051057710389*D10_B0(0,3) - 0.376283677513354*D10_B0(0,-1)
)
: ((idx[1] == 2) ? (

      0.197184333887745*D10_B0(0,0) + 0.521455851089587*D10_B0(0,1) + 0.113446470384241*D10_B0(0,-2) -
      0.00412637789557492*D10_B0(0,3) - 0.0367146847001261*D10_B0(0,2) - 0.791245592765872*D10_B0(0,-1)
)
: ((idx[1] ==
      3) ? (
   0.0451033223343881*D10_B0(0,0) + 0.652141084861241*D10_B0(0,1) + 0.121937153224065*D10_B0(0,-2) -
      0.00932597985049999*D10_B0(0,-3) - 0.727822147724592*D10_B0(0,-1) - 0.082033432844602*D10_B0(0,2)
)
: (

      -(2.0/3.0)*D10_B0(0,-1) - (1.0/12.0)*D10_B0(0,2) + ((1.0/12.0))*D10_B0(0,-2) + ((2.0/3.0))*D10_B0(0,1)
)))));

    d1_D11_dy = invDelta1block0*((idx[1] == 0) ? (
   3.0*D11_B0(0,1) + 0.333333333333333*D11_B0(0,3) - 1.5*D11_B0(0,2)
      - 1.83333333333333*D11_B0(0,0)
)
: ((idx[1] == 1) ? (
   0.0394168524399447*D11_B0(0,2) +
      0.00571369039775442*D11_B0(0,4) + 0.719443173328855*D11_B0(0,1) - 0.322484932882161*D11_B0(0,0) -
      0.0658051057710389*D11_B0(0,3) - 0.376283677513354*D11_B0(0,-1)
)
: ((idx[1] == 2) ? (

      0.197184333887745*D11_B0(0,0) + 0.521455851089587*D11_B0(0,1) + 0.113446470384241*D11_B0(0,-2) -
      0.00412637789557492*D11_B0(0,3) - 0.0367146847001261*D11_B0(0,2) - 0.791245592765872*D11_B0(0,-1)
)
: ((idx[1] ==
      3) ? (
   0.0451033223343881*D11_B0(0,0) + 0.652141084861241*D11_B0(0,1) + 0.121937153224065*D11_B0(0,-2) -
      0.00932597985049999*D11_B0(0,-3) - 0.727822147724592*D11_B0(0,-1) - 0.082033432844602*D11_B0(0,2)
)
: (

      -(2.0/3.0)*D11_B0(0,-1) - (1.0/12.0)*D11_B0(0,2) + ((1.0/12.0))*D11_B0(0,-2) + ((2.0/3.0))*D11_B0(0,1)
)))));

    d1_D01_dx = invDelta0block0*((idx[0] == 0) ? (
   3.0*D01_B0(1,0) + 0.333333333333333*D01_B0(3,0) - 1.5*D01_B0(2,0)
      - 1.83333333333333*D01_B0(0,0)
)
: ((idx[0] == 1) ? (
   0.0394168524399447*D01_B0(2,0) +
      0.00571369039775442*D01_B0(4,0) + 0.719443173328855*D01_B0(1,0) - 0.322484932882161*D01_B0(0,0) -
      0.0658051057710389*D01_B0(3,0) - 0.376283677513354*D01_B0(-1,0)
)
: ((idx[0] == 2) ? (

      0.197184333887745*D01_B0(0,0) + 0.521455851089587*D01_B0(1,0) + 0.113446470384241*D01_B0(-2,0) -
      0.00412637789557492*D01_B0(3,0) - 0.0367146847001261*D01_B0(2,0) - 0.791245592765872*D01_B0(-1,0)
)
: ((idx[0] ==
      3) ? (
   0.0451033223343881*D01_B0(0,0) + 0.652141084861241*D01_B0(1,0) + 0.121937153224065*D01_B0(-2,0) -
      0.00932597985049999*D01_B0(-3,0) - 0.727822147724592*D01_B0(-1,0) - 0.082033432844602*D01_B0(2,0)
)
: ((idx[0] ==
      -1 + block0np0) ? (
   1.5*D01_B0(-2,0) + 1.83333333333333*D01_B0(0,0) - 3.0*D01_B0(-1,0) -
      0.333333333333333*D01_B0(-3,0)
)
: ((idx[0] == -2 + block0np0) ? (
   0.322484932882161*D01_B0(0,0) +
      0.0658051057710389*D01_B0(-3,0) + 0.376283677513354*D01_B0(1,0) - 0.0394168524399447*D01_B0(-2,0) -
      0.00571369039775442*D01_B0(-4,0) - 0.719443173328855*D01_B0(-1,0)
)
: ((idx[0] == -3 + block0np0) ? (

      0.00412637789557492*D01_B0(-3,0) + 0.0367146847001261*D01_B0(-2,0) + 0.791245592765872*D01_B0(1,0) -
      0.197184333887745*D01_B0(0,0) - 0.521455851089587*D01_B0(-1,0) - 0.113446470384241*D01_B0(2,0)
)
: ((idx[0] == -4
      + block0np0) ? (
   0.00932597985049999*D01_B0(3,0) + 0.727822147724592*D01_B0(1,0) +
      0.082033432844602*D01_B0(-2,0) - 0.0451033223343881*D01_B0(0,0) - 0.652141084861241*D01_B0(-1,0) -
      0.121937153224065*D01_B0(2,0)
)
: (
   -(2.0/3.0)*D01_B0(-1,0) - (1.0/12.0)*D01_B0(2,0) +
      ((1.0/12.0))*D01_B0(-2,0) + ((2.0/3.0))*D01_B0(1,0)
)))))))));

    d1_D01_dy = invDelta1block0*((idx[1] == 0) ? (
   3.0*D01_B0(0,1) + 0.333333333333333*D01_B0(0,3) - 1.5*D01_B0(0,2)
      - 1.83333333333333*D01_B0(0,0)
)
: ((idx[1] == 1) ? (
   0.0394168524399447*D01_B0(0,2) +
      0.00571369039775442*D01_B0(0,4) + 0.719443173328855*D01_B0(0,1) - 0.322484932882161*D01_B0(0,0) -
      0.0658051057710389*D01_B0(0,3) - 0.376283677513354*D01_B0(0,-1)
)
: ((idx[1] == 2) ? (

      0.197184333887745*D01_B0(0,0) + 0.521455851089587*D01_B0(0,1) + 0.113446470384241*D01_B0(0,-2) -
      0.00412637789557492*D01_B0(0,3) - 0.0367146847001261*D01_B0(0,2) - 0.791245592765872*D01_B0(0,-1)
)
: ((idx[1] ==
      3) ? (
   0.0451033223343881*D01_B0(0,0) + 0.652141084861241*D01_B0(0,1) + 0.121937153224065*D01_B0(0,-2) -
      0.00932597985049999*D01_B0(0,-3) - 0.727822147724592*D01_B0(0,-1) - 0.082033432844602*D01_B0(0,2)
)
: (

      -(2.0/3.0)*D01_B0(0,-1) - (1.0/12.0)*D01_B0(0,2) + ((1.0/12.0))*D01_B0(0,-2) + ((2.0/3.0))*D01_B0(0,1)
)))));

   SD000_B0(0,0) = d1_D00_dx;

   SD001_B0(0,0) = d1_D00_dy;

   SD010_B0(0,0) = d1_D01_dx;

   SD011_B0(0,0) = d1_D01_dy;

   SD100_B0(0,0) = d1_D10_dx;

   SD101_B0(0,0) = d1_D10_dy;

   SD110_B0(0,0) = d1_D11_dx;

   SD111_B0(0,0) = d1_D11_dy;


    }
  }
  if (block->instance->OPS_diags > 1) {
    ops_timers_core(&__c2,&__t2);
    block->instance->OPS_kernels[6].time += __t2-__t1;
  }
  #ifndef OPS_LAZY
  ops_set_dirtybit_device(args, 13);
  ops_set_halo_dirtybit3(&args[4],range);
  ops_set_halo_dirtybit3(&args[5],range);
  ops_set_halo_dirtybit3(&args[6],range);
  ops_set_halo_dirtybit3(&args[7],range);
  ops_set_halo_dirtybit3(&args[8],range);
  ops_set_halo_dirtybit3(&args[9],range);
  ops_set_halo_dirtybit3(&args[10],range);
  ops_set_halo_dirtybit3(&args[11],range);
  #endif

  if (block->instance->OPS_diags > 1) {
    //Update kernel record
    ops_timers_core(&__c1,&__t1);
    block->instance->OPS_kernels[6].mpi_time += __t1-__t2;
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg0);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg1);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg2);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg3);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg4);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg5);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg6);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg7);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg8);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg9);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg10);
    block->instance->OPS_kernels[6].transfer += ops_compute_transfer(dim, start, end, &arg11);
  }
}


#ifdef OPS_LAZY
void ops_par_loop_opensbliblock00Kernel061(char const *name, ops_block block, int dim, int* range,
 ops_arg arg0, ops_arg arg1, ops_arg arg2, ops_arg arg3,
 ops_arg arg4, ops_arg arg5, ops_arg arg6, ops_arg arg7,
 ops_arg arg8, ops_arg arg9, ops_arg arg10, ops_arg arg11,
 ops_arg arg12) {
  ops_arg args[13] = { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12 };

  //create kernel descriptor and pass it to ops_enqueue_kernel
  create_kerneldesc_and_enque(name, args, 13, 6, dim, 0, range, block, ops_par_loop_opensbliblock00Kernel061_execute);
}
#endif
