//
// auto-generated by ops.py
//

#define OPS_GPU

int xdim0_opensbliblock00Kernel010;
int xdim1_opensbliblock00Kernel010;

//user function
inline 
void opensbliblock00Kernel010(const ptr_double wk13_B0,
  ptr_double wk5_B0,
  const int *idx)
{
    OPS_ACC(wk5_B0, 0) = inv_0*((idx[0] == 0) ? (
   3.00000000000002*OPS_ACC(wk13_B0, 1) -
      8.34657956545823e-15*OPS_ACC(wk13_B0, 4) - 1.83333333333334*OPS_ACC(wk13_B0, 0) +
      0.333333333333356*OPS_ACC(wk13_B0, 3) - 1.50000000000003*OPS_ACC(wk13_B0, 2) +
      1.06910315192207e-15*OPS_ACC(wk13_B0, 5)
)
: ((idx[0] == 1) ? (
   0.719443173328855*OPS_ACC(wk13_B0, 1) +
      0.00571369039775442*OPS_ACC(wk13_B0, 4) - 0.322484932882161*OPS_ACC(wk13_B0, 0) -
      0.0658051057710389*OPS_ACC(wk13_B0, 3) + 0.0394168524399447*OPS_ACC(wk13_B0, 2) -
      0.376283677513354*OPS_ACC(wk13_B0, -1)
)
: ((idx[0] == 2) ? (
   0.521455851089587*OPS_ACC(wk13_B0, 1) +
      0.197184333887745*OPS_ACC(wk13_B0, 0) - 0.791245592765872*OPS_ACC(wk13_B0, -1) -
      0.00412637789557492*OPS_ACC(wk13_B0, 3) - 0.0367146847001261*OPS_ACC(wk13_B0, 2) +
      0.113446470384241*OPS_ACC(wk13_B0, -2)
)
: ((idx[0] == 3) ? (
   0.652141084861241*OPS_ACC(wk13_B0, 1) -
      0.00932597985049999*OPS_ACC(wk13_B0, -3) + 0.0451033223343881*OPS_ACC(wk13_B0, 0) +
      0.121937153224065*OPS_ACC(wk13_B0, -2) - 0.082033432844602*OPS_ACC(wk13_B0, 2) -
      0.727822147724592*OPS_ACC(wk13_B0, -1)
)
: ((idx[0] == block0np0 - 1) ? (

      -0.333333333333356*OPS_ACC(wk13_B0, -3) + 1.83333333333334*OPS_ACC(wk13_B0, 0) +
      8.34657956545823e-15*OPS_ACC(wk13_B0, -4) - 3.00000000000002*OPS_ACC(wk13_B0, -1) -
      1.06910315192207e-15*OPS_ACC(wk13_B0, -5) + 1.50000000000003*OPS_ACC(wk13_B0, -2)
)
: ((idx[0] == block0np0 - 2)
      ? (
   0.376283677513354*OPS_ACC(wk13_B0, 1) + 0.0658051057710389*OPS_ACC(wk13_B0, -3) +
      0.322484932882161*OPS_ACC(wk13_B0, 0) - 0.00571369039775442*OPS_ACC(wk13_B0, -4) -
      0.719443173328855*OPS_ACC(wk13_B0, -1) - 0.0394168524399447*OPS_ACC(wk13_B0, -2)
)
: ((idx[0] == block0np0 - 3)
      ? (
   0.791245592765872*OPS_ACC(wk13_B0, 1) + 0.00412637789557492*OPS_ACC(wk13_B0, -3) -
      0.197184333887745*OPS_ACC(wk13_B0, 0) + 0.0367146847001261*OPS_ACC(wk13_B0, -2) -
      0.113446470384241*OPS_ACC(wk13_B0, 2) - 0.521455851089587*OPS_ACC(wk13_B0, -1)
)
: ((idx[0] == block0np0 - 4) ?
      (
   0.727822147724592*OPS_ACC(wk13_B0, 1) - 0.0451033223343881*OPS_ACC(wk13_B0, 0) +
      0.082033432844602*OPS_ACC(wk13_B0, -2) + 0.00932597985049999*OPS_ACC(wk13_B0, 3) -
      0.121937153224065*OPS_ACC(wk13_B0, 2) - 0.652141084861241*OPS_ACC(wk13_B0, -1)
)
: (

      (rc2)*OPS_ACC(wk13_B0, 1) - rc3*OPS_ACC(wk13_B0, 2) - rc2*OPS_ACC(wk13_B0, -1) +
      (rc3)*OPS_ACC(wk13_B0, -2)
)))))))));

}


void opensbliblock00Kernel010_c_wrapper(
  double *p_a0,
  double *p_a1,
  int *p_a2,
  int arg_idx0,
  int x_size) {
  #ifdef OPS_GPU
  #pragma acc parallel deviceptr(p_a0,p_a1)
  #pragma acc loop
  #endif
  for ( int n_x=0; n_x<x_size; n_x++ ){
    int arg_idx[] = {arg_idx0+n_x};
    const ptr_double ptr0 = {  p_a0 + n_x*1*1 };
    ptr_double ptr1 = {  p_a1 + n_x*1*1 };
    opensbliblock00Kernel010( ptr0,
          ptr1,arg_idx );

  }
}
