//
// auto-generated by ops.py
//

int xdim0_opensbliblock00Kernel031;
int xdim1_opensbliblock00Kernel031;


//user function



void opensbliblock00Kernel031_c_wrapper(
  double * restrict u1_B0_p,
  double * restrict wk2_B0_p,
  int * restrict idx,
  int arg_idx0, int arg_idx1,
  int x_size, int y_size) {
  #pragma omp parallel for
  for ( int n_y=0; n_y<y_size; n_y++ ){
    for ( int n_x=0; n_x<x_size; n_x++ ){
      int idx[] = {arg_idx0+n_x, arg_idx1+n_y};
      const ptr_double u1_B0 = { u1_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel031*1, xdim0_opensbliblock00Kernel031};
      ptr_double wk2_B0 = { wk2_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel031*1, xdim1_opensbliblock00Kernel031};
      
    OPS_ACC(wk2_B0, 0,0) = ((idx[1] == 0) ? (
   inv_0*(-3*OPS_ACC(u1_B0, 0,2) + 4*OPS_ACC(u1_B0, 0,1) -
      rc9*OPS_ACC(u1_B0, 0,0) - rc8*OPS_ACC(u1_B0, 0,4) + (rc7)*OPS_ACC(u1_B0, 0,3))
)
: ((idx[1] == 1) ? (

      (rc10)*inv_0*(-6*OPS_ACC(u1_B0, 0,2) + 18*OPS_ACC(u1_B0, 0,1) - 3*OPS_ACC(u1_B0, 0,-1) -
      10*OPS_ACC(u1_B0, 0,0) + OPS_ACC(u1_B0, 0,3))
)
: (
   (rc10)*inv_0*(OPS_ACC(u1_B0, 0,-2) -
      8*OPS_ACC(u1_B0, 0,-1) - OPS_ACC(u1_B0, 0,2) + 8*OPS_ACC(u1_B0, 0,1))
)));


    }
  }
}
