//
// auto-generated by ops.py
//

//user function

// host stub function
#ifndef OPS_LAZY
void ops_par_loop_opensbliblock00Kernel064(char const *name, ops_block block, int dim, int* range,
 ops_arg arg0, ops_arg arg1, ops_arg arg2, ops_arg arg3,
 ops_arg arg4, ops_arg arg5, ops_arg arg6, ops_arg arg7,
 ops_arg arg8, ops_arg arg9, ops_arg arg10, ops_arg arg11,
 ops_arg arg12, ops_arg arg13, ops_arg arg14, ops_arg arg15,
 ops_arg arg16, ops_arg arg17) {
#else
void ops_par_loop_opensbliblock00Kernel064_execute(ops_kernel_descriptor *desc) {
  ops_block block = desc->block;
  int dim = desc->dim;
  int *range = desc->range;
  ops_arg arg0 = desc->args[0];
  ops_arg arg1 = desc->args[1];
  ops_arg arg2 = desc->args[2];
  ops_arg arg3 = desc->args[3];
  ops_arg arg4 = desc->args[4];
  ops_arg arg5 = desc->args[5];
  ops_arg arg6 = desc->args[6];
  ops_arg arg7 = desc->args[7];
  ops_arg arg8 = desc->args[8];
  ops_arg arg9 = desc->args[9];
  ops_arg arg10 = desc->args[10];
  ops_arg arg11 = desc->args[11];
  ops_arg arg12 = desc->args[12];
  ops_arg arg13 = desc->args[13];
  ops_arg arg14 = desc->args[14];
  ops_arg arg15 = desc->args[15];
  ops_arg arg16 = desc->args[16];
  ops_arg arg17 = desc->args[17];
  #endif

  //Timing
  double __t1,__t2,__c1,__c2;

  ops_arg args[18] = { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17};



  #if defined(CHECKPOINTING) && !defined(OPS_LAZY)
  if (!ops_checkpointing_before(args,18,range,36)) return;
  #endif

  if (block->instance->OPS_diags > 1) {
    ops_timing_realloc(block->instance,36,"opensbliblock00Kernel064");
    block->instance->OPS_kernels[36].count++;
    ops_timers_core(&__c2,&__t2);
  }

  #ifdef OPS_DEBUG
  ops_register_args(block->instance, args, "opensbliblock00Kernel064");
  #endif


  //compute locally allocated range for the sub-block
  int start[3];
  int end[3];
  #if defined(OPS_MPI) && !defined(OPS_LAZY)
  int arg_idx[3];
  #endif
  #if defined(OPS_LAZY) || !defined(OPS_MPI)
  for ( int n=0; n<3; n++ ){
    start[n] = range[2*n];end[n] = range[2*n+1];
  }
  #else
  if (compute_ranges(args, 18,block, range, start, end, arg_idx) < 0) return;
  #endif



  //initialize global variable with the dimension of dats
  int xdim0_opensbliblock00Kernel064 = args[0].dat->size[0];
  int ydim0_opensbliblock00Kernel064 = args[0].dat->size[1];
  int xdim1_opensbliblock00Kernel064 = args[1].dat->size[0];
  int ydim1_opensbliblock00Kernel064 = args[1].dat->size[1];
  int xdim2_opensbliblock00Kernel064 = args[2].dat->size[0];
  int ydim2_opensbliblock00Kernel064 = args[2].dat->size[1];
  int xdim3_opensbliblock00Kernel064 = args[3].dat->size[0];
  int ydim3_opensbliblock00Kernel064 = args[3].dat->size[1];
  int xdim4_opensbliblock00Kernel064 = args[4].dat->size[0];
  int ydim4_opensbliblock00Kernel064 = args[4].dat->size[1];
  int xdim5_opensbliblock00Kernel064 = args[5].dat->size[0];
  int ydim5_opensbliblock00Kernel064 = args[5].dat->size[1];
  int xdim6_opensbliblock00Kernel064 = args[6].dat->size[0];
  int ydim6_opensbliblock00Kernel064 = args[6].dat->size[1];
  int xdim7_opensbliblock00Kernel064 = args[7].dat->size[0];
  int ydim7_opensbliblock00Kernel064 = args[7].dat->size[1];
  int xdim8_opensbliblock00Kernel064 = args[8].dat->size[0];
  int ydim8_opensbliblock00Kernel064 = args[8].dat->size[1];
  int xdim9_opensbliblock00Kernel064 = args[9].dat->size[0];
  int ydim9_opensbliblock00Kernel064 = args[9].dat->size[1];
  int xdim10_opensbliblock00Kernel064 = args[10].dat->size[0];
  int ydim10_opensbliblock00Kernel064 = args[10].dat->size[1];
  int xdim11_opensbliblock00Kernel064 = args[11].dat->size[0];
  int ydim11_opensbliblock00Kernel064 = args[11].dat->size[1];
  int xdim12_opensbliblock00Kernel064 = args[12].dat->size[0];
  int ydim12_opensbliblock00Kernel064 = args[12].dat->size[1];
  int xdim13_opensbliblock00Kernel064 = args[13].dat->size[0];
  int ydim13_opensbliblock00Kernel064 = args[13].dat->size[1];
  int xdim14_opensbliblock00Kernel064 = args[14].dat->size[0];
  int ydim14_opensbliblock00Kernel064 = args[14].dat->size[1];
  int xdim15_opensbliblock00Kernel064 = args[15].dat->size[0];
  int ydim15_opensbliblock00Kernel064 = args[15].dat->size[1];
  int xdim16_opensbliblock00Kernel064 = args[16].dat->size[0];
  int ydim16_opensbliblock00Kernel064 = args[16].dat->size[1];
  int xdim17_opensbliblock00Kernel064 = args[17].dat->size[0];
  int ydim17_opensbliblock00Kernel064 = args[17].dat->size[1];

  //set up initial pointers and exchange halos if necessary
  int base0 = args[0].dat->base_offset;
  double * __restrict__ D00_B0_p = (double *)(args[0].data + base0);

  int base1 = args[1].dat->base_offset;
  double * __restrict__ D01_B0_p = (double *)(args[1].data + base1);

  int base2 = args[2].dat->base_offset;
  double * __restrict__ a_B0_p = (double *)(args[2].data + base2);

  int base3 = args[3].dat->base_offset;
  double * __restrict__ detJ_B0_p = (double *)(args[3].data + base3);

  int base4 = args[4].dat->base_offset;
  double * __restrict__ kappa_B0_p = (double *)(args[4].data + base4);

  int base5 = args[5].dat->base_offset;
  double * __restrict__ rhoE_B0_p = (double *)(args[5].data + base5);

  int base6 = args[6].dat->base_offset;
  double * __restrict__ rho_B0_p = (double *)(args[6].data + base6);

  int base7 = args[7].dat->base_offset;
  double * __restrict__ rhou0_B0_p = (double *)(args[7].data + base7);

  int base8 = args[8].dat->base_offset;
  double * __restrict__ rhou1_B0_p = (double *)(args[8].data + base8);

  int base9 = args[9].dat->base_offset;
  double * __restrict__ rhou2_B0_p = (double *)(args[9].data + base9);

  int base10 = args[10].dat->base_offset;
  double * __restrict__ u0_B0_p = (double *)(args[10].data + base10);

  int base11 = args[11].dat->base_offset;
  double * __restrict__ u1_B0_p = (double *)(args[11].data + base11);

  int base12 = args[12].dat->base_offset;
  double * __restrict__ u2_B0_p = (double *)(args[12].data + base12);

  int base13 = args[13].dat->base_offset;
  double * __restrict__ wk0_B0_p = (double *)(args[13].data + base13);

  int base14 = args[14].dat->base_offset;
  double * __restrict__ wk1_B0_p = (double *)(args[14].data + base14);

  int base15 = args[15].dat->base_offset;
  double * __restrict__ wk2_B0_p = (double *)(args[15].data + base15);

  int base16 = args[16].dat->base_offset;
  double * __restrict__ wk3_B0_p = (double *)(args[16].data + base16);

  int base17 = args[17].dat->base_offset;
  double * __restrict__ wk4_B0_p = (double *)(args[17].data + base17);



  #ifndef OPS_LAZY
  //Halo Exchanges
  ops_H_D_exchanges_host(args, 18);
  ops_halo_exchanges(args,18,range);
  ops_H_D_exchanges_host(args, 18);
  #endif

  if (block->instance->OPS_diags > 1) {
    ops_timers_core(&__c1,&__t1);
    block->instance->OPS_kernels[36].mpi_time += __t1-__t2;
  }

  #pragma omp parallel for collapse(2)
  for ( int n_z=start[2]; n_z<end[2]; n_z++ ){
    for ( int n_y=start[1]; n_y<end[1]; n_y++ ){
      #ifdef __INTEL_COMPILER
      #pragma loop_count(10000)
      #pragma omp simd
      #elif defined(__clang__)
      #pragma clang loop vectorize(assume_safety)
      #elif defined(__GNUC__)
      #pragma GCC ivdep
      #else
      #pragma simd
      #endif
      for ( int n_x=start[0]; n_x<end[0]; n_x++ ){
        const ACC<double> D00_B0(xdim0_opensbliblock00Kernel064, ydim0_opensbliblock00Kernel064, D00_B0_p + n_x*1 + n_y * xdim0_opensbliblock00Kernel064*1 + n_z * xdim0_opensbliblock00Kernel064 * ydim0_opensbliblock00Kernel064*1);
        const ACC<double> D01_B0(xdim1_opensbliblock00Kernel064, ydim1_opensbliblock00Kernel064, D01_B0_p + n_x*1 + n_y * xdim1_opensbliblock00Kernel064*1 + n_z * xdim1_opensbliblock00Kernel064 * ydim1_opensbliblock00Kernel064*1);
        const ACC<double> a_B0(xdim2_opensbliblock00Kernel064, ydim2_opensbliblock00Kernel064, a_B0_p + n_x*1 + n_y * xdim2_opensbliblock00Kernel064*1 + n_z * xdim2_opensbliblock00Kernel064 * ydim2_opensbliblock00Kernel064*1);
        const ACC<double> detJ_B0(xdim3_opensbliblock00Kernel064, ydim3_opensbliblock00Kernel064, detJ_B0_p + n_x*1 + n_y * xdim3_opensbliblock00Kernel064*1 + n_z * xdim3_opensbliblock00Kernel064 * ydim3_opensbliblock00Kernel064*1);
        const ACC<double> kappa_B0(xdim4_opensbliblock00Kernel064, ydim4_opensbliblock00Kernel064, kappa_B0_p + n_x*1 + n_y * xdim4_opensbliblock00Kernel064*1 + n_z * xdim4_opensbliblock00Kernel064 * ydim4_opensbliblock00Kernel064*1);
        const ACC<double> rhoE_B0(xdim5_opensbliblock00Kernel064, ydim5_opensbliblock00Kernel064, rhoE_B0_p + n_x*1 + n_y * xdim5_opensbliblock00Kernel064*1 + n_z * xdim5_opensbliblock00Kernel064 * ydim5_opensbliblock00Kernel064*1);
        const ACC<double> rho_B0(xdim6_opensbliblock00Kernel064, ydim6_opensbliblock00Kernel064, rho_B0_p + n_x*1 + n_y * xdim6_opensbliblock00Kernel064*1 + n_z * xdim6_opensbliblock00Kernel064 * ydim6_opensbliblock00Kernel064*1);
        const ACC<double> rhou0_B0(xdim7_opensbliblock00Kernel064, ydim7_opensbliblock00Kernel064, rhou0_B0_p + n_x*1 + n_y * xdim7_opensbliblock00Kernel064*1 + n_z * xdim7_opensbliblock00Kernel064 * ydim7_opensbliblock00Kernel064*1);
        const ACC<double> rhou1_B0(xdim8_opensbliblock00Kernel064, ydim8_opensbliblock00Kernel064, rhou1_B0_p + n_x*1 + n_y * xdim8_opensbliblock00Kernel064*1 + n_z * xdim8_opensbliblock00Kernel064 * ydim8_opensbliblock00Kernel064*1);
        const ACC<double> rhou2_B0(xdim9_opensbliblock00Kernel064, ydim9_opensbliblock00Kernel064, rhou2_B0_p + n_x*1 + n_y * xdim9_opensbliblock00Kernel064*1 + n_z * xdim9_opensbliblock00Kernel064 * ydim9_opensbliblock00Kernel064*1);
        const ACC<double> u0_B0(xdim10_opensbliblock00Kernel064, ydim10_opensbliblock00Kernel064, u0_B0_p + n_x*1 + n_y * xdim10_opensbliblock00Kernel064*1 + n_z * xdim10_opensbliblock00Kernel064 * ydim10_opensbliblock00Kernel064*1);
        const ACC<double> u1_B0(xdim11_opensbliblock00Kernel064, ydim11_opensbliblock00Kernel064, u1_B0_p + n_x*1 + n_y * xdim11_opensbliblock00Kernel064*1 + n_z * xdim11_opensbliblock00Kernel064 * ydim11_opensbliblock00Kernel064*1);
        const ACC<double> u2_B0(xdim12_opensbliblock00Kernel064, ydim12_opensbliblock00Kernel064, u2_B0_p + n_x*1 + n_y * xdim12_opensbliblock00Kernel064*1 + n_z * xdim12_opensbliblock00Kernel064 * ydim12_opensbliblock00Kernel064*1);
        ACC<double> wk0_B0(xdim13_opensbliblock00Kernel064, ydim13_opensbliblock00Kernel064, wk0_B0_p + n_x*1 + n_y * xdim13_opensbliblock00Kernel064*1 + n_z * xdim13_opensbliblock00Kernel064 * ydim13_opensbliblock00Kernel064*1);
        ACC<double> wk1_B0(xdim14_opensbliblock00Kernel064, ydim14_opensbliblock00Kernel064, wk1_B0_p + n_x*1 + n_y * xdim14_opensbliblock00Kernel064*1 + n_z * xdim14_opensbliblock00Kernel064 * ydim14_opensbliblock00Kernel064*1);
        ACC<double> wk2_B0(xdim15_opensbliblock00Kernel064, ydim15_opensbliblock00Kernel064, wk2_B0_p + n_x*1 + n_y * xdim15_opensbliblock00Kernel064*1 + n_z * xdim15_opensbliblock00Kernel064 * ydim15_opensbliblock00Kernel064*1);
        ACC<double> wk3_B0(xdim16_opensbliblock00Kernel064, ydim16_opensbliblock00Kernel064, wk3_B0_p + n_x*1 + n_y * xdim16_opensbliblock00Kernel064*1 + n_z * xdim16_opensbliblock00Kernel064 * ydim16_opensbliblock00Kernel064*1);
        ACC<double> wk4_B0(xdim17_opensbliblock00Kernel064, ydim17_opensbliblock00Kernel064, wk4_B0_p + n_x*1 + n_y * xdim17_opensbliblock00Kernel064*1 + n_z * xdim17_opensbliblock00Kernel064 * ydim17_opensbliblock00Kernel064*1);
        
   double AVG_0_0_LEV_00 = 0.0;
   double AVG_0_0_LEV_01 = 0.0;
   double AVG_0_0_LEV_02 = 0.0;
   double AVG_0_0_LEV_03 = 0.0;
   double AVG_0_0_LEV_04 = 0.0;
   double AVG_0_0_LEV_10 = 0.0;
   double AVG_0_0_LEV_11 = 0.0;
   double AVG_0_0_LEV_12 = 0.0;
   double AVG_0_0_LEV_13 = 0.0;
   double AVG_0_0_LEV_14 = 0.0;
   double AVG_0_0_LEV_20 = 0.0;
   double AVG_0_0_LEV_21 = 0.0;
   double AVG_0_0_LEV_22 = 0.0;
   double AVG_0_0_LEV_30 = 0.0;
   double AVG_0_0_LEV_31 = 0.0;
   double AVG_0_0_LEV_32 = 0.0;
   double AVG_0_0_LEV_33 = 0.0;
   double AVG_0_0_LEV_34 = 0.0;
   double AVG_0_0_LEV_40 = 0.0;
   double AVG_0_0_LEV_41 = 0.0;
   double AVG_0_0_LEV_42 = 0.0;
   double AVG_0_0_LEV_43 = 0.0;
   double AVG_0_0_LEV_44 = 0.0;
   double AVG_0_D00 = 0.0;
   double AVG_0_D01 = 0.0;
   double AVG_0_REV_00 = 0.0;
   double AVG_0_REV_01 = 0.0;
   double AVG_0_REV_03 = 0.0;
   double AVG_0_REV_04 = 0.0;
   double AVG_0_REV_10 = 0.0;
   double AVG_0_REV_11 = 0.0;
   double AVG_0_REV_12 = 0.0;
   double AVG_0_REV_13 = 0.0;
   double AVG_0_REV_14 = 0.0;
   double AVG_0_REV_20 = 0.0;
   double AVG_0_REV_21 = 0.0;
   double AVG_0_REV_22 = 0.0;
   double AVG_0_REV_23 = 0.0;
   double AVG_0_REV_24 = 0.0;
   double AVG_0_REV_30 = 0.0;
   double AVG_0_REV_31 = 0.0;
   double AVG_0_REV_33 = 0.0;
   double AVG_0_REV_34 = 0.0;
   double AVG_0_REV_40 = 0.0;
   double AVG_0_REV_41 = 0.0;
   double AVG_0_REV_42 = 0.0;
   double AVG_0_REV_43 = 0.0;
   double AVG_0_REV_44 = 0.0;
   double AVG_0_a = 0.0;
   double AVG_0_detJ = 0.0;
   double AVG_0_rho = 0.0;
   double AVG_0_u0 = 0.0;
   double AVG_0_u1 = 0.0;
   double AVG_0_u2 = 0.0;
   double S = 0.0;
   double alpha_00 = 0.0;
   double alpha_01 = 0.0;
   double alpha_02 = 0.0;
   double alpha_10 = 0.0;
   double alpha_11 = 0.0;
   double alpha_12 = 0.0;
   double alpha_20 = 0.0;
   double alpha_21 = 0.0;
   double alpha_22 = 0.0;
   double alpha_30 = 0.0;
   double alpha_31 = 0.0;
   double alpha_32 = 0.0;
   double alpha_40 = 0.0;
   double alpha_41 = 0.0;
   double alpha_42 = 0.0;
   double g_00 = 0.0;
   double g_01 = 0.0;
   double g_10 = 0.0;
   double g_11 = 0.0;
   double g_20 = 0.0;
   double g_21 = 0.0;
   double g_30 = 0.0;
   double g_31 = 0.0;
   double g_40 = 0.0;
   double g_41 = 0.0;
   double gamma_0 = 0.0;
   double gamma_1 = 0.0;
   double gamma_2 = 0.0;
   double gamma_3 = 0.0;
   double gamma_4 = 0.0;
   double inv_AVG_a = 0.0;
   double inv_AVG_met_fact = 0.0;
   double inv_AVG_rho = 0.0;
   double phi_0 = 0.0;
   double phi_1 = 0.0;
   double phi_2 = 0.0;
   double phi_3 = 0.0;
   double phi_4 = 0.0;
   double phi_star_0 = 0.0;
   double phi_star_1 = 0.0;
   double phi_star_2 = 0.0;
   double phi_star_3 = 0.0;
   double phi_star_4 = 0.0;
   double sigma_0_0 = 0.0;
   double sigma_0_1 = 0.0;
   double sigma_0_2 = 0.0;
   double sigma_0_3 = 0.0;
   double sigma_0_4 = 0.0;
   double sigma_1_0 = 0.0;
   double sigma_1_1 = 0.0;
   double sigma_1_2 = 0.0;
   double sigma_1_3 = 0.0;
   double sigma_1_4 = 0.0;
   double t1 = 0.0;
   double t2 = 0.0;
   double theta_0 = 0.0;
   double theta_1 = 0.0;
   double theta_2 = 0.0;
   double theta_3 = 0.0;
   double theta_4 = 0.0;
   double theta_hat_00 = 0.0;
   double theta_hat_01 = 0.0;
   double theta_hat_10 = 0.0;
   double theta_hat_11 = 0.0;
   double theta_hat_20 = 0.0;
   double theta_hat_21 = 0.0;
   double theta_hat_30 = 0.0;
   double theta_hat_31 = 0.0;
   double theta_hat_40 = 0.0;
   double theta_hat_41 = 0.0;
   double ws_lambda_00 = 0.0;
   double ws_lambda_11 = 0.0;
   double ws_lambda_22 = 0.0;
   double ws_lambda_33 = 0.0;
   double ws_lambda_44 = 0.0;
    if (fmax(kappa_B0(1,0,0), fmax(kappa_B0(2,0,0), fmax(kappa_B0(-3,0,0), fmax(kappa_B0(-2,0,0), fmax(kappa_B0(-1,0,0),
      kappa_B0(0,0,0)))))) > Ducros_check){

      AVG_0_u0 = ((1.0/2.0))*(u0_B0(0,0,0) + u0_B0(-1,0,0));

      AVG_0_u2 = ((1.0/2.0))*(u2_B0(0,0,0) + u2_B0(-1,0,0));

      AVG_0_rho = ((1.0/2.0))*(rho_B0(0,0,0) + rho_B0(-1,0,0));

      AVG_0_u1 = ((1.0/2.0))*(u1_B0(0,0,0) + u1_B0(-1,0,0));

      AVG_0_a = ((1.0/2.0))*(a_B0(0,0,0) + a_B0(-1,0,0));

      AVG_0_D01 = ((1.0/2.0))*(D01_B0(0,0,0) + D01_B0(1,0,0));

      AVG_0_D00 = ((1.0/2.0))*(D00_B0(0,0,0) + D00_B0(1,0,0));

      AVG_0_detJ = ((1.0/2.0))*(detJ_B0(0,0,0) + detJ_B0(1,0,0));

      inv_AVG_a = 1.0/(AVG_0_a);

      inv_AVG_rho = 1.0/(AVG_0_rho);

      inv_AVG_met_fact = pow((AVG_0_D00*AVG_0_D00) + (AVG_0_D01*AVG_0_D01), (-1.0/2.0));

       AVG_0_0_LEV_00 = -(1.0/2.0)*(-2*AVG_0_D00 - (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 -
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 - (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 -
            2*AVG_0_D01*AVG_0_u2*inv_AVG_rho + (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00 +
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00 +
            (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00)*inv_AVG_met_fact;

      AVG_0_0_LEV_01 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*AVG_0_u0*inv_AVG_met_fact;

      AVG_0_0_LEV_02 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*AVG_0_u1*inv_AVG_met_fact;

       AVG_0_0_LEV_03 = (-AVG_0_D01*inv_AVG_rho - (inv_AVG_a*inv_AVG_a)*AVG_0_D00*AVG_0_u2 +
            (inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00*AVG_0_u2)*inv_AVG_met_fact;

      AVG_0_0_LEV_04 = -(inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*inv_AVG_met_fact;

       AVG_0_0_LEV_10 = -(1.0/2.0)*(-2*AVG_0_D01 - (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 -
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 - (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 +
            2*AVG_0_D00*AVG_0_u2*inv_AVG_rho + (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01 +
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01 +
            (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01)*inv_AVG_met_fact;

      AVG_0_0_LEV_11 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*AVG_0_u0*inv_AVG_met_fact;

      AVG_0_0_LEV_12 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*AVG_0_u1*inv_AVG_met_fact;

       AVG_0_0_LEV_13 = (AVG_0_D00*inv_AVG_rho - (inv_AVG_a*inv_AVG_a)*AVG_0_D01*AVG_0_u2 +
            (inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01*AVG_0_u2)*inv_AVG_met_fact;

      AVG_0_0_LEV_14 = -(inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*inv_AVG_met_fact;

      AVG_0_0_LEV_20 = (AVG_0_D00*AVG_0_u1 - AVG_0_D01*AVG_0_u0)*inv_AVG_met_fact*inv_AVG_rho;

      AVG_0_0_LEV_21 = AVG_0_D01*inv_AVG_met_fact*inv_AVG_rho;

      AVG_0_0_LEV_22 = -AVG_0_D00*inv_AVG_met_fact*inv_AVG_rho;

       AVG_0_0_LEV_30 = -0.353553390593274*((AVG_0_u0*AVG_0_u0) + (AVG_0_u1*AVG_0_u1) + (AVG_0_u2*AVG_0_u2) -
            (AVG_0_u0*AVG_0_u0)*gama - (AVG_0_u1*AVG_0_u1)*gama - (AVG_0_u2*AVG_0_u2)*gama +
            2*AVG_0_D00*AVG_0_a*AVG_0_u0*inv_AVG_met_fact +
            2*AVG_0_D01*AVG_0_a*AVG_0_u1*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_31 = 0.707106781186547*(-gama*AVG_0_u0 + AVG_0_D00*AVG_0_a*inv_AVG_met_fact +
            AVG_0_u0)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_32 = 0.707106781186547*(-gama*AVG_0_u1 + AVG_0_D01*AVG_0_a*inv_AVG_met_fact +
            AVG_0_u1)*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_33 = -0.707106781186547*gamma_m1*AVG_0_u2*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_34 = 0.707106781186547*gamma_m1*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_40 = 0.353553390593274*(-(AVG_0_u0*AVG_0_u0) - (AVG_0_u1*AVG_0_u1) - (AVG_0_u2*AVG_0_u2) +
            (AVG_0_u0*AVG_0_u0)*gama + (AVG_0_u1*AVG_0_u1)*gama + (AVG_0_u2*AVG_0_u2)*gama +
            2*AVG_0_D00*AVG_0_a*AVG_0_u0*inv_AVG_met_fact +
            2*AVG_0_D01*AVG_0_a*AVG_0_u1*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_41 = -0.707106781186547*(-AVG_0_u0 + gama*AVG_0_u0 +
            AVG_0_D00*AVG_0_a*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_42 = -0.707106781186547*(-AVG_0_u1 + gama*AVG_0_u1 +
            AVG_0_D01*AVG_0_a*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_43 = -0.707106781186547*gamma_m1*AVG_0_u2*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_44 = 0.707106781186547*gamma_m1*inv_AVG_a*inv_AVG_rho;

       alpha_00 = (-rho_B0(-1,0,0) + rho_B0(0,0,0))*AVG_0_0_LEV_00 + (-rhoE_B0(-1,0,0) + rhoE_B0(0,0,0))*AVG_0_0_LEV_04
            + (-rhou0_B0(-1,0,0) + rhou0_B0(0,0,0))*AVG_0_0_LEV_01 + (-rhou1_B0(-1,0,0) +
            rhou1_B0(0,0,0))*AVG_0_0_LEV_02 + (-rhou2_B0(-1,0,0) + rhou2_B0(0,0,0))*AVG_0_0_LEV_03;

       alpha_10 = (-rho_B0(-1,0,0) + rho_B0(0,0,0))*AVG_0_0_LEV_10 + (-rhoE_B0(-1,0,0) + rhoE_B0(0,0,0))*AVG_0_0_LEV_14
            + (-rhou0_B0(-1,0,0) + rhou0_B0(0,0,0))*AVG_0_0_LEV_11 + (-rhou1_B0(-1,0,0) +
            rhou1_B0(0,0,0))*AVG_0_0_LEV_12 + (-rhou2_B0(-1,0,0) + rhou2_B0(0,0,0))*AVG_0_0_LEV_13;

       alpha_20 = (-rho_B0(-1,0,0) + rho_B0(0,0,0))*AVG_0_0_LEV_20 + (-rhou0_B0(-1,0,0) +
            rhou0_B0(0,0,0))*AVG_0_0_LEV_21 + (-rhou1_B0(-1,0,0) + rhou1_B0(0,0,0))*AVG_0_0_LEV_22;

       alpha_30 = (-rho_B0(-1,0,0) + rho_B0(0,0,0))*AVG_0_0_LEV_30 + (-rhoE_B0(-1,0,0) + rhoE_B0(0,0,0))*AVG_0_0_LEV_34
            + (-rhou0_B0(-1,0,0) + rhou0_B0(0,0,0))*AVG_0_0_LEV_31 + (-rhou1_B0(-1,0,0) +
            rhou1_B0(0,0,0))*AVG_0_0_LEV_32 + (-rhou2_B0(-1,0,0) + rhou2_B0(0,0,0))*AVG_0_0_LEV_33;

       alpha_40 = (-rho_B0(-1,0,0) + rho_B0(0,0,0))*AVG_0_0_LEV_40 + (-rhoE_B0(-1,0,0) + rhoE_B0(0,0,0))*AVG_0_0_LEV_44
            + (-rhou0_B0(-1,0,0) + rhou0_B0(0,0,0))*AVG_0_0_LEV_41 + (-rhou1_B0(-1,0,0) +
            rhou1_B0(0,0,0))*AVG_0_0_LEV_42 + (-rhou2_B0(-1,0,0) + rhou2_B0(0,0,0))*AVG_0_0_LEV_43;

      AVG_0_u0 = ((1.0/2.0))*(u0_B0(0,0,0) + u0_B0(1,0,0));

      AVG_0_u2 = ((1.0/2.0))*(u2_B0(0,0,0) + u2_B0(1,0,0));

      AVG_0_rho = ((1.0/2.0))*(rho_B0(0,0,0) + rho_B0(1,0,0));

      AVG_0_u1 = ((1.0/2.0))*(u1_B0(0,0,0) + u1_B0(1,0,0));

      AVG_0_a = ((1.0/2.0))*(a_B0(0,0,0) + a_B0(1,0,0));

      AVG_0_D01 = ((1.0/2.0))*(D01_B0(0,0,0) + D01_B0(1,0,0));

      AVG_0_D00 = ((1.0/2.0))*(D00_B0(0,0,0) + D00_B0(1,0,0));

      AVG_0_detJ = ((1.0/2.0))*(detJ_B0(0,0,0) + detJ_B0(1,0,0));

      inv_AVG_a = 1.0/(AVG_0_a);

      inv_AVG_rho = 1.0/(AVG_0_rho);

      inv_AVG_met_fact = pow((AVG_0_D00*AVG_0_D00) + (AVG_0_D01*AVG_0_D01), (-1.0/2.0));

       AVG_0_0_LEV_00 = -(1.0/2.0)*(-2*AVG_0_D00 - (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 -
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 - (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 -
            2*AVG_0_D01*AVG_0_u2*inv_AVG_rho + (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00 +
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00 +
            (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00)*inv_AVG_met_fact;

      AVG_0_0_LEV_01 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*AVG_0_u0*inv_AVG_met_fact;

      AVG_0_0_LEV_02 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*AVG_0_u1*inv_AVG_met_fact;

       AVG_0_0_LEV_03 = (-AVG_0_D01*inv_AVG_rho - (inv_AVG_a*inv_AVG_a)*AVG_0_D00*AVG_0_u2 +
            (inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00*AVG_0_u2)*inv_AVG_met_fact;

      AVG_0_0_LEV_04 = -(inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*inv_AVG_met_fact;

       AVG_0_0_LEV_10 = -(1.0/2.0)*(-2*AVG_0_D01 - (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 -
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 - (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 +
            2*AVG_0_D00*AVG_0_u2*inv_AVG_rho + (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01 +
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01 +
            (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01)*inv_AVG_met_fact;

      AVG_0_0_LEV_11 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*AVG_0_u0*inv_AVG_met_fact;

      AVG_0_0_LEV_12 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*AVG_0_u1*inv_AVG_met_fact;

       AVG_0_0_LEV_13 = (AVG_0_D00*inv_AVG_rho - (inv_AVG_a*inv_AVG_a)*AVG_0_D01*AVG_0_u2 +
            (inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01*AVG_0_u2)*inv_AVG_met_fact;

      AVG_0_0_LEV_14 = -(inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*inv_AVG_met_fact;

      AVG_0_0_LEV_20 = (AVG_0_D00*AVG_0_u1 - AVG_0_D01*AVG_0_u0)*inv_AVG_met_fact*inv_AVG_rho;

      AVG_0_0_LEV_21 = AVG_0_D01*inv_AVG_met_fact*inv_AVG_rho;

      AVG_0_0_LEV_22 = -AVG_0_D00*inv_AVG_met_fact*inv_AVG_rho;

       AVG_0_0_LEV_30 = -0.353553390593274*((AVG_0_u0*AVG_0_u0) + (AVG_0_u1*AVG_0_u1) + (AVG_0_u2*AVG_0_u2) -
            (AVG_0_u0*AVG_0_u0)*gama - (AVG_0_u1*AVG_0_u1)*gama - (AVG_0_u2*AVG_0_u2)*gama +
            2*AVG_0_D00*AVG_0_a*AVG_0_u0*inv_AVG_met_fact +
            2*AVG_0_D01*AVG_0_a*AVG_0_u1*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_31 = 0.707106781186547*(-gama*AVG_0_u0 + AVG_0_D00*AVG_0_a*inv_AVG_met_fact +
            AVG_0_u0)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_32 = 0.707106781186547*(-gama*AVG_0_u1 + AVG_0_D01*AVG_0_a*inv_AVG_met_fact +
            AVG_0_u1)*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_33 = -0.707106781186547*gamma_m1*AVG_0_u2*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_34 = 0.707106781186547*gamma_m1*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_40 = 0.353553390593274*(-(AVG_0_u0*AVG_0_u0) - (AVG_0_u1*AVG_0_u1) - (AVG_0_u2*AVG_0_u2) +
            (AVG_0_u0*AVG_0_u0)*gama + (AVG_0_u1*AVG_0_u1)*gama + (AVG_0_u2*AVG_0_u2)*gama +
            2*AVG_0_D00*AVG_0_a*AVG_0_u0*inv_AVG_met_fact +
            2*AVG_0_D01*AVG_0_a*AVG_0_u1*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_41 = -0.707106781186547*(-AVG_0_u0 + gama*AVG_0_u0 +
            AVG_0_D00*AVG_0_a*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_42 = -0.707106781186547*(-AVG_0_u1 + gama*AVG_0_u1 +
            AVG_0_D01*AVG_0_a*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_43 = -0.707106781186547*gamma_m1*AVG_0_u2*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_44 = 0.707106781186547*gamma_m1*inv_AVG_a*inv_AVG_rho;

       alpha_01 = (-rho_B0(0,0,0) + rho_B0(1,0,0))*AVG_0_0_LEV_00 + (-rhoE_B0(0,0,0) + rhoE_B0(1,0,0))*AVG_0_0_LEV_04 +
            (-rhou0_B0(0,0,0) + rhou0_B0(1,0,0))*AVG_0_0_LEV_01 + (-rhou1_B0(0,0,0) + rhou1_B0(1,0,0))*AVG_0_0_LEV_02 +
            (-rhou2_B0(0,0,0) + rhou2_B0(1,0,0))*AVG_0_0_LEV_03;

       alpha_11 = (-rho_B0(0,0,0) + rho_B0(1,0,0))*AVG_0_0_LEV_10 + (-rhoE_B0(0,0,0) + rhoE_B0(1,0,0))*AVG_0_0_LEV_14 +
            (-rhou0_B0(0,0,0) + rhou0_B0(1,0,0))*AVG_0_0_LEV_11 + (-rhou1_B0(0,0,0) + rhou1_B0(1,0,0))*AVG_0_0_LEV_12 +
            (-rhou2_B0(0,0,0) + rhou2_B0(1,0,0))*AVG_0_0_LEV_13;

       alpha_21 = (-rho_B0(0,0,0) + rho_B0(1,0,0))*AVG_0_0_LEV_20 + (-rhou0_B0(0,0,0) + rhou0_B0(1,0,0))*AVG_0_0_LEV_21
            + (-rhou1_B0(0,0,0) + rhou1_B0(1,0,0))*AVG_0_0_LEV_22;

       alpha_31 = (-rho_B0(0,0,0) + rho_B0(1,0,0))*AVG_0_0_LEV_30 + (-rhoE_B0(0,0,0) + rhoE_B0(1,0,0))*AVG_0_0_LEV_34 +
            (-rhou0_B0(0,0,0) + rhou0_B0(1,0,0))*AVG_0_0_LEV_31 + (-rhou1_B0(0,0,0) + rhou1_B0(1,0,0))*AVG_0_0_LEV_32 +
            (-rhou2_B0(0,0,0) + rhou2_B0(1,0,0))*AVG_0_0_LEV_33;

       alpha_41 = (-rho_B0(0,0,0) + rho_B0(1,0,0))*AVG_0_0_LEV_40 + (-rhoE_B0(0,0,0) + rhoE_B0(1,0,0))*AVG_0_0_LEV_44 +
            (-rhou0_B0(0,0,0) + rhou0_B0(1,0,0))*AVG_0_0_LEV_41 + (-rhou1_B0(0,0,0) + rhou1_B0(1,0,0))*AVG_0_0_LEV_42 +
            (-rhou2_B0(0,0,0) + rhou2_B0(1,0,0))*AVG_0_0_LEV_43;

      ws_lambda_00 = (D00_B0(0,0,0)*AVG_0_u0 + D01_B0(0,0,0)*AVG_0_u1)*detJ_B0(0,0,0);

      ws_lambda_11 = (D00_B0(0,0,0)*AVG_0_u0 + D01_B0(0,0,0)*AVG_0_u1)*detJ_B0(0,0,0);

      ws_lambda_22 = (D00_B0(0,0,0)*AVG_0_u0 + D01_B0(0,0,0)*AVG_0_u1)*detJ_B0(0,0,0);

       ws_lambda_33 = sqrt((D00_B0(0,0,0)*D00_B0(0,0,0))*(detJ_B0(0,0,0)*detJ_B0(0,0,0)) +
            (D01_B0(0,0,0)*D01_B0(0,0,0))*(detJ_B0(0,0,0)*detJ_B0(0,0,0)))*AVG_0_a +
            D00_B0(0,0,0)*detJ_B0(0,0,0)*AVG_0_u0 + D01_B0(0,0,0)*detJ_B0(0,0,0)*AVG_0_u1;

       ws_lambda_44 = -sqrt((D00_B0(0,0,0)*D00_B0(0,0,0))*(detJ_B0(0,0,0)*detJ_B0(0,0,0)) +
            (D01_B0(0,0,0)*D01_B0(0,0,0))*(detJ_B0(0,0,0)*detJ_B0(0,0,0)))*AVG_0_a +
            D00_B0(0,0,0)*detJ_B0(0,0,0)*AVG_0_u0 + D01_B0(0,0,0)*detJ_B0(0,0,0)*AVG_0_u1;

      AVG_0_REV_00 = AVG_0_D00*inv_AVG_met_fact;

      AVG_0_REV_01 = AVG_0_D01*inv_AVG_met_fact;

      AVG_0_REV_03 = 0.707106781186547*AVG_0_rho*inv_AVG_a;

      AVG_0_REV_04 = 0.707106781186547*AVG_0_rho*inv_AVG_a;

      AVG_0_REV_10 = AVG_0_D00*AVG_0_u0*inv_AVG_met_fact;

      AVG_0_REV_11 = AVG_0_D01*AVG_0_u0*inv_AVG_met_fact;

      AVG_0_REV_12 = AVG_0_D01*AVG_0_rho*inv_AVG_met_fact;

      AVG_0_REV_13 = 0.707106781186547*(AVG_0_D00*AVG_0_a*inv_AVG_met_fact + AVG_0_u0)*AVG_0_rho*inv_AVG_a;

      AVG_0_REV_14 = 0.707106781186547*(-AVG_0_D00*AVG_0_a*inv_AVG_met_fact + AVG_0_u0)*AVG_0_rho*inv_AVG_a;

      AVG_0_REV_20 = AVG_0_D00*AVG_0_u1*inv_AVG_met_fact;

      AVG_0_REV_21 = AVG_0_D01*AVG_0_u1*inv_AVG_met_fact;

      AVG_0_REV_22 = -AVG_0_D00*AVG_0_rho*inv_AVG_met_fact;

      AVG_0_REV_23 = 0.707106781186547*(AVG_0_D01*AVG_0_a*inv_AVG_met_fact + AVG_0_u1)*AVG_0_rho*inv_AVG_a;

      AVG_0_REV_24 = 0.707106781186547*(-AVG_0_D01*AVG_0_a*inv_AVG_met_fact + AVG_0_u1)*AVG_0_rho*inv_AVG_a;

      AVG_0_REV_30 = AVG_0_D00*AVG_0_u2*inv_AVG_met_fact - AVG_0_D01*AVG_0_rho*inv_AVG_met_fact;

      AVG_0_REV_31 = AVG_0_D00*AVG_0_rho*inv_AVG_met_fact + AVG_0_D01*AVG_0_u2*inv_AVG_met_fact;

      AVG_0_REV_33 = 0.707106781186547*AVG_0_rho*AVG_0_u2*inv_AVG_a;

      AVG_0_REV_34 = 0.707106781186547*AVG_0_rho*AVG_0_u2*inv_AVG_a;

       AVG_0_REV_40 = ((1.0/2.0))*((AVG_0_u0*AVG_0_u0) + (AVG_0_u1*AVG_0_u1) +
            (AVG_0_u2*AVG_0_u2))*AVG_0_D00*inv_AVG_met_fact - AVG_0_D01*AVG_0_rho*AVG_0_u2*inv_AVG_met_fact;

       AVG_0_REV_41 = ((1.0/2.0))*((AVG_0_u0*AVG_0_u0) + (AVG_0_u1*AVG_0_u1) +
            (AVG_0_u2*AVG_0_u2))*AVG_0_D01*inv_AVG_met_fact + AVG_0_D00*AVG_0_rho*AVG_0_u2*inv_AVG_met_fact;

      AVG_0_REV_42 = (AVG_0_D01*AVG_0_u0*inv_AVG_met_fact - AVG_0_D00*AVG_0_u1*inv_AVG_met_fact)*AVG_0_rho;

       AVG_0_REV_43 = 0.707106781186547*(((AVG_0_a*AVG_0_a) + ((1.0/2.0))*((AVG_0_u0*AVG_0_u0) + (AVG_0_u1*AVG_0_u1) +
            (AVG_0_u2*AVG_0_u2))*gamma_m1)*invgamma_m1 + (AVG_0_D00*AVG_0_u0*inv_AVG_met_fact +
            AVG_0_D01*AVG_0_u1*inv_AVG_met_fact)*AVG_0_a)*AVG_0_rho*inv_AVG_a;

       AVG_0_REV_44 = 0.707106781186547*(((AVG_0_a*AVG_0_a) + ((1.0/2.0))*((AVG_0_u0*AVG_0_u0) + (AVG_0_u1*AVG_0_u1) +
            (AVG_0_u2*AVG_0_u2))*gamma_m1)*invgamma_m1 - (AVG_0_D00*AVG_0_u0*inv_AVG_met_fact +
            AVG_0_D01*AVG_0_u1*inv_AVG_met_fact)*AVG_0_a)*AVG_0_rho*inv_AVG_a;

      AVG_0_u0 = ((1.0/2.0))*(u0_B0(1,0,0) + u0_B0(2,0,0));

      AVG_0_u2 = ((1.0/2.0))*(u2_B0(1,0,0) + u2_B0(2,0,0));

      AVG_0_rho = ((1.0/2.0))*(rho_B0(1,0,0) + rho_B0(2,0,0));

      AVG_0_u1 = ((1.0/2.0))*(u1_B0(1,0,0) + u1_B0(2,0,0));

      AVG_0_a = ((1.0/2.0))*(a_B0(1,0,0) + a_B0(2,0,0));

      AVG_0_D01 = ((1.0/2.0))*(D01_B0(0,0,0) + D01_B0(1,0,0));

      AVG_0_D00 = ((1.0/2.0))*(D00_B0(0,0,0) + D00_B0(1,0,0));

      AVG_0_detJ = ((1.0/2.0))*(detJ_B0(0,0,0) + detJ_B0(1,0,0));

      inv_AVG_a = 1.0/(AVG_0_a);

      inv_AVG_rho = 1.0/(AVG_0_rho);

      inv_AVG_met_fact = pow((AVG_0_D00*AVG_0_D00) + (AVG_0_D01*AVG_0_D01), (-1.0/2.0));

       AVG_0_0_LEV_00 = -(1.0/2.0)*(-2*AVG_0_D00 - (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 -
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 - (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*AVG_0_D00 -
            2*AVG_0_D01*AVG_0_u2*inv_AVG_rho + (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00 +
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00 +
            (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00)*inv_AVG_met_fact;

      AVG_0_0_LEV_01 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*AVG_0_u0*inv_AVG_met_fact;

      AVG_0_0_LEV_02 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*AVG_0_u1*inv_AVG_met_fact;

       AVG_0_0_LEV_03 = (-AVG_0_D01*inv_AVG_rho - (inv_AVG_a*inv_AVG_a)*AVG_0_D00*AVG_0_u2 +
            (inv_AVG_a*inv_AVG_a)*gama*AVG_0_D00*AVG_0_u2)*inv_AVG_met_fact;

      AVG_0_0_LEV_04 = -(inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D00*inv_AVG_met_fact;

       AVG_0_0_LEV_10 = -(1.0/2.0)*(-2*AVG_0_D01 - (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 -
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 - (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*AVG_0_D01 +
            2*AVG_0_D00*AVG_0_u2*inv_AVG_rho + (AVG_0_u0*AVG_0_u0)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01 +
            (AVG_0_u1*AVG_0_u1)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01 +
            (AVG_0_u2*AVG_0_u2)*(inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01)*inv_AVG_met_fact;

      AVG_0_0_LEV_11 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*AVG_0_u0*inv_AVG_met_fact;

      AVG_0_0_LEV_12 = (inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*AVG_0_u1*inv_AVG_met_fact;

       AVG_0_0_LEV_13 = (AVG_0_D00*inv_AVG_rho - (inv_AVG_a*inv_AVG_a)*AVG_0_D01*AVG_0_u2 +
            (inv_AVG_a*inv_AVG_a)*gama*AVG_0_D01*AVG_0_u2)*inv_AVG_met_fact;

      AVG_0_0_LEV_14 = -(inv_AVG_a*inv_AVG_a)*gamma_m1*AVG_0_D01*inv_AVG_met_fact;

      AVG_0_0_LEV_20 = (AVG_0_D00*AVG_0_u1 - AVG_0_D01*AVG_0_u0)*inv_AVG_met_fact*inv_AVG_rho;

      AVG_0_0_LEV_21 = AVG_0_D01*inv_AVG_met_fact*inv_AVG_rho;

      AVG_0_0_LEV_22 = -AVG_0_D00*inv_AVG_met_fact*inv_AVG_rho;

       AVG_0_0_LEV_30 = -0.353553390593274*((AVG_0_u0*AVG_0_u0) + (AVG_0_u1*AVG_0_u1) + (AVG_0_u2*AVG_0_u2) -
            (AVG_0_u0*AVG_0_u0)*gama - (AVG_0_u1*AVG_0_u1)*gama - (AVG_0_u2*AVG_0_u2)*gama +
            2*AVG_0_D00*AVG_0_a*AVG_0_u0*inv_AVG_met_fact +
            2*AVG_0_D01*AVG_0_a*AVG_0_u1*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_31 = 0.707106781186547*(-gama*AVG_0_u0 + AVG_0_D00*AVG_0_a*inv_AVG_met_fact +
            AVG_0_u0)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_32 = 0.707106781186547*(-gama*AVG_0_u1 + AVG_0_D01*AVG_0_a*inv_AVG_met_fact +
            AVG_0_u1)*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_33 = -0.707106781186547*gamma_m1*AVG_0_u2*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_34 = 0.707106781186547*gamma_m1*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_40 = 0.353553390593274*(-(AVG_0_u0*AVG_0_u0) - (AVG_0_u1*AVG_0_u1) - (AVG_0_u2*AVG_0_u2) +
            (AVG_0_u0*AVG_0_u0)*gama + (AVG_0_u1*AVG_0_u1)*gama + (AVG_0_u2*AVG_0_u2)*gama +
            2*AVG_0_D00*AVG_0_a*AVG_0_u0*inv_AVG_met_fact +
            2*AVG_0_D01*AVG_0_a*AVG_0_u1*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_41 = -0.707106781186547*(-AVG_0_u0 + gama*AVG_0_u0 +
            AVG_0_D00*AVG_0_a*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

       AVG_0_0_LEV_42 = -0.707106781186547*(-AVG_0_u1 + gama*AVG_0_u1 +
            AVG_0_D01*AVG_0_a*inv_AVG_met_fact)*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_43 = -0.707106781186547*gamma_m1*AVG_0_u2*inv_AVG_a*inv_AVG_rho;

      AVG_0_0_LEV_44 = 0.707106781186547*gamma_m1*inv_AVG_a*inv_AVG_rho;

       alpha_02 = (-rho_B0(1,0,0) + rho_B0(2,0,0))*AVG_0_0_LEV_00 + (-rhoE_B0(1,0,0) + rhoE_B0(2,0,0))*AVG_0_0_LEV_04 +
            (-rhou0_B0(1,0,0) + rhou0_B0(2,0,0))*AVG_0_0_LEV_01 + (-rhou1_B0(1,0,0) + rhou1_B0(2,0,0))*AVG_0_0_LEV_02 +
            (-rhou2_B0(1,0,0) + rhou2_B0(2,0,0))*AVG_0_0_LEV_03;

       alpha_12 = (-rho_B0(1,0,0) + rho_B0(2,0,0))*AVG_0_0_LEV_10 + (-rhoE_B0(1,0,0) + rhoE_B0(2,0,0))*AVG_0_0_LEV_14 +
            (-rhou0_B0(1,0,0) + rhou0_B0(2,0,0))*AVG_0_0_LEV_11 + (-rhou1_B0(1,0,0) + rhou1_B0(2,0,0))*AVG_0_0_LEV_12 +
            (-rhou2_B0(1,0,0) + rhou2_B0(2,0,0))*AVG_0_0_LEV_13;

       alpha_22 = (-rho_B0(1,0,0) + rho_B0(2,0,0))*AVG_0_0_LEV_20 + (-rhou0_B0(1,0,0) + rhou0_B0(2,0,0))*AVG_0_0_LEV_21
            + (-rhou1_B0(1,0,0) + rhou1_B0(2,0,0))*AVG_0_0_LEV_22;

       alpha_32 = (-rho_B0(1,0,0) + rho_B0(2,0,0))*AVG_0_0_LEV_30 + (-rhoE_B0(1,0,0) + rhoE_B0(2,0,0))*AVG_0_0_LEV_34 +
            (-rhou0_B0(1,0,0) + rhou0_B0(2,0,0))*AVG_0_0_LEV_31 + (-rhou1_B0(1,0,0) + rhou1_B0(2,0,0))*AVG_0_0_LEV_32 +
            (-rhou2_B0(1,0,0) + rhou2_B0(2,0,0))*AVG_0_0_LEV_33;

       alpha_42 = (-rho_B0(1,0,0) + rho_B0(2,0,0))*AVG_0_0_LEV_40 + (-rhoE_B0(1,0,0) + rhoE_B0(2,0,0))*AVG_0_0_LEV_44 +
            (-rhou0_B0(1,0,0) + rhou0_B0(2,0,0))*AVG_0_0_LEV_41 + (-rhou1_B0(1,0,0) + rhou1_B0(2,0,0))*AVG_0_0_LEV_42 +
            (-rhou2_B0(1,0,0) + rhou2_B0(2,0,0))*AVG_0_0_LEV_43;

       sigma_0_0 = ((fabs(ws_lambda_00) >= delta_TVD) ? (
   fabs(ws_lambda_00)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (ws_lambda_00*ws_lambda_00))*invdelta_TVD
));

       sigma_0_1 = ((fabs(ws_lambda_11) >= delta_TVD) ? (
   fabs(ws_lambda_11)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (ws_lambda_11*ws_lambda_11))*invdelta_TVD
));

       sigma_0_2 = ((fabs(ws_lambda_22) >= delta_TVD) ? (
   fabs(ws_lambda_22)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (ws_lambda_22*ws_lambda_22))*invdelta_TVD
));

       sigma_0_3 = ((fabs(ws_lambda_33) >= delta_TVD) ? (
   fabs(ws_lambda_33)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (ws_lambda_33*ws_lambda_33))*invdelta_TVD
));

       sigma_0_4 = ((fabs(ws_lambda_44) >= delta_TVD) ? (
   fabs(ws_lambda_44)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (ws_lambda_44*ws_lambda_44))*invdelta_TVD
));

      S = (alpha_01 > 0) ? 1 : ((alpha_01 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_00, 2*fabs(alpha_01)));

      t2 = fmin(fabs(alpha_01), 2*S*alpha_00);

      g_00 = S*fmax(t1, t2);

      S = (alpha_11 > 0) ? 1 : ((alpha_11 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_10, 2*fabs(alpha_11)));

      t2 = fmin(fabs(alpha_11), 2*S*alpha_10);

      g_10 = S*fmax(t1, t2);

      S = (alpha_21 > 0) ? 1 : ((alpha_21 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_20, 2*fabs(alpha_21)));

      t2 = fmin(fabs(alpha_21), 2*S*alpha_20);

      g_20 = S*fmax(t1, t2);

      S = (alpha_31 > 0) ? 1 : ((alpha_31 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_30, 2*fabs(alpha_31)));

      t2 = fmin(fabs(alpha_31), 2*S*alpha_30);

      g_30 = S*fmax(t1, t2);

      S = (alpha_41 > 0) ? 1 : ((alpha_41 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_40, 2*fabs(alpha_41)));

      t2 = fmin(fabs(alpha_41), 2*S*alpha_40);

      g_40 = S*fmax(t1, t2);

      S = (alpha_02 > 0) ? 1 : ((alpha_02 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_01, 2*fabs(alpha_02)));

      t2 = fmin(fabs(alpha_02), 2*S*alpha_01);

      g_01 = S*fmax(t1, t2);

      S = (alpha_12 > 0) ? 1 : ((alpha_12 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_11, 2*fabs(alpha_12)));

      t2 = fmin(fabs(alpha_12), 2*S*alpha_11);

      g_11 = S*fmax(t1, t2);

      S = (alpha_22 > 0) ? 1 : ((alpha_22 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_21, 2*fabs(alpha_22)));

      t2 = fmin(fabs(alpha_22), 2*S*alpha_21);

      g_21 = S*fmax(t1, t2);

      S = (alpha_32 > 0) ? 1 : ((alpha_32 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_31, 2*fabs(alpha_32)));

      t2 = fmin(fabs(alpha_32), 2*S*alpha_31);

      g_31 = S*fmax(t1, t2);

      S = (alpha_42 > 0) ? 1 : ((alpha_42 < 0) ? -1 : 0);

      t1 = fmax(0.0, fmin(S*alpha_41, 2*fabs(alpha_42)));

      t2 = fmin(fabs(alpha_42), 2*S*alpha_41);

      g_41 = S*fmax(t1, t2);

       gamma_0 = ((alpha_01 == 0) ? (
   0
)
: (
   (-g_00 + g_01)*alpha_01*sigma_0_0/((alpha_01*alpha_01) +
            eps_TVD)
));

       gamma_1 = ((alpha_11 == 0) ? (
   0
)
: (
   (-g_10 + g_11)*alpha_11*sigma_0_1/((alpha_11*alpha_11) +
            eps_TVD)
));

       gamma_2 = ((alpha_21 == 0) ? (
   0
)
: (
   (-g_20 + g_21)*alpha_21*sigma_0_2/((alpha_21*alpha_21) +
            eps_TVD)
));

       gamma_3 = ((alpha_31 == 0) ? (
   0
)
: (
   (-g_30 + g_31)*alpha_31*sigma_0_3/((alpha_31*alpha_31) +
            eps_TVD)
));

       gamma_4 = ((alpha_41 == 0) ? (
   0
)
: (
   (-g_40 + g_41)*alpha_41*sigma_0_4/((alpha_41*alpha_41) +
            eps_TVD)
));

       sigma_1_0 = ((fabs(gamma_0) >= delta_TVD) ? (
   fabs(gamma_0)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (gamma_0*gamma_0))*invdelta_TVD
));

       sigma_1_1 = ((fabs(gamma_1) >= delta_TVD) ? (
   fabs(gamma_1)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (gamma_1*gamma_1))*invdelta_TVD
));

       sigma_1_2 = ((fabs(gamma_2) >= delta_TVD) ? (
   fabs(gamma_2)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (gamma_2*gamma_2))*invdelta_TVD
));

       sigma_1_3 = ((fabs(gamma_3) >= delta_TVD) ? (
   fabs(gamma_3)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (gamma_3*gamma_3))*invdelta_TVD
));

       sigma_1_4 = ((fabs(gamma_4) >= delta_TVD) ? (
   fabs(gamma_4)
)
: (

            ((1.0/2.0))*(1.0/(invdelta_TVD*invdelta_TVD) + (gamma_4*gamma_4))*invdelta_TVD
));

      phi_0 = -fabs(sigma_0_0 + sigma_1_0)*alpha_01 + 0.5*(g_00 + g_01)*sigma_0_0;

      phi_1 = -fabs(sigma_0_1 + sigma_1_1)*alpha_11 + 0.5*(g_10 + g_11)*sigma_0_1;

      phi_2 = -fabs(sigma_0_2 + sigma_1_2)*alpha_21 + 0.5*(g_20 + g_21)*sigma_0_2;

      phi_3 = -fabs(sigma_0_3 + sigma_1_3)*alpha_31 + 0.5*(g_30 + g_31)*sigma_0_3;

      phi_4 = -fabs(sigma_0_4 + sigma_1_4)*alpha_41 + 0.5*(g_40 + g_41)*sigma_0_4;

      t1 = -fabs(alpha_00) + fabs(alpha_01);

      t2 = fabs(alpha_00) + fabs(alpha_01) + eps_TVD;

      theta_hat_00 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_10) + fabs(alpha_11);

      t2 = fabs(alpha_10) + fabs(alpha_11) + eps_TVD;

      theta_hat_10 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_20) + fabs(alpha_21);

      t2 = fabs(alpha_20) + fabs(alpha_21) + eps_TVD;

      theta_hat_20 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_30) + fabs(alpha_31);

      t2 = fabs(alpha_30) + fabs(alpha_31) + eps_TVD;

      theta_hat_30 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_40) + fabs(alpha_41);

      t2 = fabs(alpha_40) + fabs(alpha_41) + eps_TVD;

      theta_hat_40 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_01) + fabs(alpha_02);

      t2 = fabs(alpha_01) + fabs(alpha_02) + eps_TVD;

      theta_hat_01 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_11) + fabs(alpha_12);

      t2 = fabs(alpha_11) + fabs(alpha_12) + eps_TVD;

      theta_hat_11 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_21) + fabs(alpha_22);

      t2 = fabs(alpha_21) + fabs(alpha_22) + eps_TVD;

      theta_hat_21 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_31) + fabs(alpha_32);

      t2 = fabs(alpha_31) + fabs(alpha_32) + eps_TVD;

      theta_hat_31 = (fabs(t1/t2)*fabs(t1/t2));

      t1 = -fabs(alpha_41) + fabs(alpha_42);

      t2 = fabs(alpha_41) + fabs(alpha_42) + eps_TVD;

      theta_hat_41 = (fabs(t1/t2)*fabs(t1/t2));

      theta_0 = fmax(theta_hat_00, theta_hat_01);

      theta_1 = fmax(theta_hat_10, theta_hat_11);

      theta_2 = fmax(theta_hat_20, theta_hat_21);

      theta_3 = fmax(theta_hat_30, theta_hat_31);

      theta_4 = fmax(theta_hat_40, theta_hat_41);

      phi_star_0 = kappa_TVD*phi_0*theta_0;

      phi_star_1 = kappa_TVD*phi_1*theta_1;

      phi_star_2 = kappa_TVD*phi_2*theta_2;

      phi_star_3 = kappa_TVD*phi_3*theta_3;

      phi_star_4 = kappa_TVD*phi_4*theta_4;

       wk0_B0(0,0,0) = 0.5*(AVG_0_REV_00*phi_star_0 + AVG_0_REV_01*phi_star_1 + AVG_0_REV_03*phi_star_3 +
            AVG_0_REV_04*phi_star_4);

       wk1_B0(0,0,0) = 0.5*(AVG_0_REV_10*phi_star_0 + AVG_0_REV_11*phi_star_1 + AVG_0_REV_12*phi_star_2 +
            AVG_0_REV_13*phi_star_3 + AVG_0_REV_14*phi_star_4);

       wk2_B0(0,0,0) = 0.5*(AVG_0_REV_20*phi_star_0 + AVG_0_REV_21*phi_star_1 + AVG_0_REV_22*phi_star_2 +
            AVG_0_REV_23*phi_star_3 + AVG_0_REV_24*phi_star_4);

       wk3_B0(0,0,0) = 0.5*(AVG_0_REV_30*phi_star_0 + AVG_0_REV_31*phi_star_1 + AVG_0_REV_33*phi_star_3 +
            AVG_0_REV_34*phi_star_4);

       wk4_B0(0,0,0) = 0.5*(AVG_0_REV_40*phi_star_0 + AVG_0_REV_41*phi_star_1 + AVG_0_REV_42*phi_star_2 +
            AVG_0_REV_43*phi_star_3 + AVG_0_REV_44*phi_star_4);

   }

   else{

      wk0_B0(0,0,0) = 0.0;

      wk1_B0(0,0,0) = 0.0;

      wk2_B0(0,0,0) = 0.0;

      wk3_B0(0,0,0) = 0.0;

      wk4_B0(0,0,0) = 0.0;

   }


      }
    }
  }
  if (block->instance->OPS_diags > 1) {
    ops_timers_core(&__c2,&__t2);
    block->instance->OPS_kernels[36].time += __t2-__t1;
  }
  #ifndef OPS_LAZY
  ops_set_dirtybit_host(args, 18);
  ops_set_halo_dirtybit3(&args[13],range);
  ops_set_halo_dirtybit3(&args[14],range);
  ops_set_halo_dirtybit3(&args[15],range);
  ops_set_halo_dirtybit3(&args[16],range);
  ops_set_halo_dirtybit3(&args[17],range);
  #endif

  if (block->instance->OPS_diags > 1) {
    //Update kernel record
    ops_timers_core(&__c1,&__t1);
    block->instance->OPS_kernels[36].mpi_time += __t1-__t2;
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg0);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg1);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg2);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg3);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg4);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg5);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg6);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg7);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg8);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg9);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg10);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg11);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg12);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg13);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg14);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg15);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg16);
    block->instance->OPS_kernels[36].transfer += ops_compute_transfer(dim, start, end, &arg17);
  }
}


#ifdef OPS_LAZY
void ops_par_loop_opensbliblock00Kernel064(char const *name, ops_block block, int dim, int* range,
 ops_arg arg0, ops_arg arg1, ops_arg arg2, ops_arg arg3,
 ops_arg arg4, ops_arg arg5, ops_arg arg6, ops_arg arg7,
 ops_arg arg8, ops_arg arg9, ops_arg arg10, ops_arg arg11,
 ops_arg arg12, ops_arg arg13, ops_arg arg14, ops_arg arg15,
 ops_arg arg16, ops_arg arg17) {
  ops_arg args[18] = { arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17 };

  //create kernel descriptor and pass it to ops_enqueue_kernel
  create_kerneldesc_and_enque(name, args, 18, 36, dim, 0, range, block, ops_par_loop_opensbliblock00Kernel064_execute);
}
#endif
