//
// auto-generated by ops.py
//

//user function

// host stub function
#ifndef OPS_LAZY
void ops_par_loop_opensbliblock00Kernel027(char const *name, ops_block block, int dim, int* range,
 ops_arg arg0, ops_arg arg1, ops_arg arg2, ops_arg arg3,
 ops_arg arg4, ops_arg arg5, ops_arg arg6) {
#else
void ops_par_loop_opensbliblock00Kernel027_execute(ops_kernel_descriptor *desc) {
  ops_block block = desc->block;
  int dim = desc->dim;
  int *range = desc->range;
  ops_arg arg0 = desc->args[0];
  ops_arg arg1 = desc->args[1];
  ops_arg arg2 = desc->args[2];
  ops_arg arg3 = desc->args[3];
  ops_arg arg4 = desc->args[4];
  ops_arg arg5 = desc->args[5];
  ops_arg arg6 = desc->args[6];
  #endif

  //Timing
  double __t1,__t2,__c1,__c2;

  ops_arg args[7] = { arg0, arg1, arg2, arg3, arg4,
 arg5, arg6};



  #if defined(CHECKPOINTING) && !defined(OPS_LAZY)
  if (!ops_checkpointing_before(args,7,range,21)) return;
  #endif

  if (block->instance->OPS_diags > 1) {
    ops_timing_realloc(block->instance,21,"opensbliblock00Kernel027");
    block->instance->OPS_kernels[21].count++;
    ops_timers_core(&__c2,&__t2);
  }

  #ifdef OPS_DEBUG
  ops_register_args(block->instance, args, "opensbliblock00Kernel027");
  #endif


  //compute locally allocated range for the sub-block
  int start[1];
  int end[1];
  #if defined(OPS_MPI) && !defined(OPS_LAZY)
  int arg_idx[1];
  #endif
  #if defined(OPS_LAZY) || !defined(OPS_MPI)
  for ( int n=0; n<1; n++ ){
    start[n] = range[2*n];end[n] = range[2*n+1];
  }
  #else
  if (compute_ranges(args, 7,block, range, start, end, arg_idx) < 0) return;
  #endif


  //initialize global variable with the dimension of dats

  //set up initial pointers and exchange halos if necessary
  int base0 = args[0].dat->base_offset/sizeof(double);
  double* rho_B0_p = (double*)args[0].data_d;

  int base1 = args[1].dat->base_offset/sizeof(double);
  double* rhou0_B0_p = (double*)args[1].data_d;

  int base2 = args[2].dat->base_offset/sizeof(double);
  double* rhoE_B0_p = (double*)args[2].data_d;

  int base3 = args[3].dat->base_offset/sizeof(double);
  double* Mach_sensor_B0_p = (double*)args[3].data_d;

  int base4 = args[4].dat->base_offset/sizeof(double);
  double* u0_B0_p = (double*)args[4].data_d;

  int base5 = args[5].dat->base_offset/sizeof(double);
  double* a_B0_p = (double*)args[5].data_d;

  int base6 = args[6].dat->base_offset/sizeof(double);
  double* p_B0_p = (double*)args[6].data_d;



  #ifndef OPS_LAZY
  //Halo Exchanges
  ops_H_D_exchanges_device(args, 7);
  ops_halo_exchanges(args,7,range);
  #endif

  if (block->instance->OPS_diags > 1) {
    ops_timers_core(&__c1,&__t1);
    block->instance->OPS_kernels[21].mpi_time += __t1-__t2;
  }

  int start_0 = start[0];
  int end_0 = end[0];
  if ((end[0]-start[0])>0) {
    block->instance->sycl_instance->queue->submit([&](cl::sycl::handler &cgh) {

      auto gama_sycl = (*gama_p).template get_access<cl::sycl::access::mode::read>(cgh);

      cgh.parallel_for<class opensbliblock00Kernel027_kernel>(cl::sycl::nd_range<1>(cl::sycl::range<1>(
            ((end[0]-start[0]-1)/block->instance->OPS_block_size_x+1)*block->instance->OPS_block_size_x
             ),cl::sycl::range<1>(
      block->instance->OPS_block_size_x
             ))
      , [=](cl::sycl::nd_item<1> item
      ) [[intel::kernel_args_restrict]] {
        int n_x = item.get_global_id(0)+start_0;
        const ACC<double> rho_B0(&rho_B0_p[0] + base0 + n_x*1);
        const ACC<double> rhou0_B0(&rhou0_B0_p[0] + base1 + n_x*1);
        const ACC<double> rhoE_B0(&rhoE_B0_p[0] + base2 + n_x*1);
        ACC<double> Mach_sensor_B0(&Mach_sensor_B0_p[0] + base3 + n_x*1);
        ACC<double> u0_B0(&u0_B0_p[0] + base4 + n_x*1);
        ACC<double> a_B0(&a_B0_p[0] + base5 + n_x*1);
        ACC<double> p_B0(&p_B0_p[0] + base6 + n_x*1);
        //USER CODE
        if (n_x < end_0) {
          
   double M = 0.0;
   double p = 0.0;
   double inv_rho = 0.0;
   double inv_a = 0.0;
   double u0 = 0.0;
   inv_rho = 1.0/rho_B0(0);

   u0_B0(0) = inv_rho*rhou0_B0(0);

   p_B0(0) = (gama_sycl[0] - 1)*(-0.5*inv_rho*pow(rhou0_B0(0), 2) + rhoE_B0(0));

   a_B0(0) = cl::sycl::sqrt(gama_sycl[0]*inv_rho*p_B0(0));

   inv_rho = 1.0/rho_B0(0);

   u0 = inv_rho*rhou0_B0(0);

   p = (gama_sycl[0] - 1)*(-0.5*inv_rho*pow(rhou0_B0(0), 2) + rhoE_B0(0));

   inv_a = 1.0/cl::sycl::sqrt(gama_sycl[0]*inv_rho*p);

   M = inv_a*cl::sycl::sqrt(pow(u0, 2));

   Mach_sensor_B0(0) = cl::sycl::fmin(1, 0.5*pow(M, 2)*cl::sycl::sqrt(pow(-pow(M, 2) + 1, 2) + 4)/(pow(M, 2) + 1));


        }
      });
    });
  }
  if (block->instance->OPS_diags > 1) {
    block->instance->sycl_instance->queue->wait();
    ops_timers_core(&__c2,&__t2);
    block->instance->OPS_kernels[21].time += __t2-__t1;
  }
  #ifndef OPS_LAZY
  ops_set_dirtybit_device(args, 7);
  ops_set_halo_dirtybit3(&args[3],range);
  ops_set_halo_dirtybit3(&args[4],range);
  ops_set_halo_dirtybit3(&args[5],range);
  ops_set_halo_dirtybit3(&args[6],range);
  #endif

  if (block->instance->OPS_diags > 1) {
    //Update kernel record
    ops_timers_core(&__c1,&__t1);
    block->instance->OPS_kernels[21].mpi_time += __t1-__t2;
    block->instance->OPS_kernels[21].transfer += ops_compute_transfer(dim, start, end, &arg0);
    block->instance->OPS_kernels[21].transfer += ops_compute_transfer(dim, start, end, &arg1);
    block->instance->OPS_kernels[21].transfer += ops_compute_transfer(dim, start, end, &arg2);
    block->instance->OPS_kernels[21].transfer += ops_compute_transfer(dim, start, end, &arg3);
    block->instance->OPS_kernels[21].transfer += ops_compute_transfer(dim, start, end, &arg4);
    block->instance->OPS_kernels[21].transfer += ops_compute_transfer(dim, start, end, &arg5);
    block->instance->OPS_kernels[21].transfer += ops_compute_transfer(dim, start, end, &arg6);
  }
}


#ifdef OPS_LAZY
void ops_par_loop_opensbliblock00Kernel027(char const *name, ops_block block, int dim, int* range,
 ops_arg arg0, ops_arg arg1, ops_arg arg2, ops_arg arg3,
 ops_arg arg4, ops_arg arg5, ops_arg arg6) {
  ops_kernel_descriptor *desc = (ops_kernel_descriptor *)calloc(1,sizeof(ops_kernel_descriptor));
  desc->name = name;
  desc->block = block;
  desc->dim = dim;
  desc->device = 1;
  desc->index = 21;
  desc->hash = 5381;
  desc->hash = ((desc->hash << 5) + desc->hash) + 21;
  for ( int i=0; i<2; i++ ){
    desc->range[i] = range[i];
    desc->orig_range[i] = range[i];
    desc->hash = ((desc->hash << 5) + desc->hash) + range[i];
  }
  desc->nargs = 7;
  desc->args = (ops_arg*)ops_malloc(7*sizeof(ops_arg));
  desc->args[0] = arg0;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg0.dat->index;
  desc->args[1] = arg1;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg1.dat->index;
  desc->args[2] = arg2;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg2.dat->index;
  desc->args[3] = arg3;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg3.dat->index;
  desc->args[4] = arg4;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg4.dat->index;
  desc->args[5] = arg5;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg5.dat->index;
  desc->args[6] = arg6;
  desc->hash = ((desc->hash << 5) + desc->hash) + arg6.dat->index;
  desc->function = ops_par_loop_opensbliblock00Kernel027_execute;
  if (block->instance->OPS_diags > 1) {
    ops_timing_realloc(block->instance,21,"opensbliblock00Kernel027");
  }
  ops_enqueue_kernel(desc);
}
#endif
